<div id="select-email">
    <div id="dialog-email"></div>
    <?php if( count( $this->rs ) ):?>
    <form id="formEmail" action="#this">
        <div>
            <label for="subject"><?php echo $this->translate('subject')?>: </label>
                <?php echo $this->formText('subject') ?>
        </div>
        <br>
        <div>
            <textarea id="ds" name="ds" style="height: 150px;width: 100%"></textarea>
        </div>
        <div class="right">
            <br>
            <input type="button" id="view-email" value=" <?=$this->translate('view email')?> " style="margin-left:10px;" />
            <input type="submit" value=" <?=$this->translate('send email')?> " style="margin-left:10px;" />
        </div>
        <div class="clear">&nbsp;</div>
        <div class="right">
            <a href="#this" class="left" id="checkAll" style="margin-right:10px;">Marcar todos</a>
            <a href="#this" class="left" id="uncheckAll">Desmarcar todos</a>
        </div>
        <table id="table-email" class="tablesorter" cellspacing="1">
            <thead>
                <tr>
                    <th style="width:70%;"><?php echo $this->translate("name")?></th>
                    <th style="width:30%;" ><?php echo $this->translate("select")?></th>
                </tr>
            </thead>
                <?php echo $this->formHidden( 'group_id'      , $this->group->id ) ?>
                <?php echo $this->formHidden( 'discipline_id' , $this->group->discipline_id ) ?>
                <?php $count = 0;?>
            <tbody>
                    <?php foreach( $this->rs as $key => $rs ): ?>
                        <?php $class  = $this->changeClass( $key , array( "light_gray" , "white" ) );?>
                        <?php $person = $rs->findParentRow('Person') ?>
                        <?php $checked = null?>

                <tr class="<?=$class?>" border="1">
                    <td style="width:70%;" class="link-preRegistration">
                                <?=mb_strtoupper($person->name, APP_CHARSET)?>
                    </td>
                    <td class="user" style="text-align:center;"><input type="checkbox" name="persons[<?php echo $rs->name?>]" value="<?php echo mb_strtolower($rs->email, APP_CHARSET)?>" /> </td>
                </tr>
                    <?php endforeach;?>
            </tbody>
        </table>
        <div class="clear">&nbsp;</div>
    </form>

    <?php else:?>
    <table class="datatable">
        <tr class="<?=$class?>">
            <td><?=$this->translate( "there are no records" );?></td>
        </tr>
    </table>
    <?php endif;?>
</div>
<script type="text/javascript">
    jQuery( '#formEmail' ).submit( function(){
        Editor_email.saveHTML();
        if(jQuery(".user > input[type='checkbox']:checked").length){
            if(jQuery('#ds').val()){
                if(confirm("<?php echo $this->translate('really want to send this email?')?>")){
                    new Preceptor.util.AjaxUpdate( 'mainemail' , '<?=$this->url?>/email/email/send' , { formId: "formEmail" });
                }
            }else{
                alert('Digite um texto para enviar o email');
            }
        }else{
            alert('Selecione alguem pra enviar o email');
        }
        return false;
    });

    jQuery('#view-email').click( function(){
        Editor_email.saveHTML();
        new Preceptor.util.AjaxUpdate( 'dialog-email' , '<?=$this->url?>/email/email/view' , { formId: "formEmail" });
        jQuery('#dialog-email').dialog('open').show();
    });

    jQuery("#dialog-email")
    .dialog({
        autoOpen: false,
        height: 350,
        width: 610,
        modal: false
    })
    .hide()
    .bind('dialogclose', function(){
        jQuery(this).html('');
    });

    jQuery("#select-email").ready(function() {
        jQuery("#table-email").tablesorter({widthFixed: true, widgets: ['zebra']});
    });

    jQuery('#checkAll').click(function() {
        jQuery("input[type=checkbox]").each(function(j , val) {
            this.checked = true;
        });
    });

    jQuery('#uncheckAll').click(function() {
        jQuery("input[type=checkbox]").each(function() {
            this.checked = false;
        });
    });

    var Editor_email = new Preceptor.widget.Editor("ds");


</script>
