<div>
    <label><?=$this->translate( "visible to" )?>:</label>
	<?php if($this->user->roles[SYSTEM_ID]['current'] != Share_Model_Role::STUDENT ):?>
		<br />

		<div>
		   <div>
				<div>
					<label><?=$this->translate( "course" )?>:</label>
				</div>

				<br />

				<div>
					<span><?=$this->formSelect( "course" , null , array( "id" => "{$this->model}-course" ) , $this->courses )?></span>
					<span><input type="button" id="<?=$this->model?>-course_button" value="<?=$this->translate("add")?>" /></span>
				</div>

			</div>

			<div id="discipline_td<?=$this->model?>"></div>

			<div id="group_td<?=$this->model?>"></div>

			<div id="person_td<?=$this->model?>"></div>
		</div>
	<?php endif; ?>
</div>

<div class="filter padding">
    <div class="legend pos-relative"><?=$this->translate("added")?></div>
    <div id="added-<?=$this->model?>" class="clear"></div>
</div>

<input name="json_relation" id="json_relation_<?=$this->model?>" type="hidden" />

<script>
	relation_<?=$this->model?> = new Relation( '<?=$this->jsonRelation?>' );
	
	<?php if( strlen($this->jsonRelation) == 2 ): ?>
		relation_<?=$this->model?>.add( <?=$this->user->person_id?> , "person_id" , "<?=$this->user->name?>" , "<?=$this->model?>" );
	<?php endif ?>

    $("#<?=$this->model?>-course_button").click(function(){
        relation_<?=$this->model?>.add( $( "#<?=$this->model?>-course" ).val() , "course_id" , $( "#<?=$this->model?>-course" )[0].options[ $( "#<?=$this->model?>-course" )[0].selectedIndex ].innerHTML , "<?=$this->model?>"  );
    });

    $("#<?=$this->model?>-course").change(function(){
        $( "#discipline_td<?=$this->model?>" ).empty();
		$( "#group_td<?=$this->model?>" ).empty();
		$( "#person_td<?=$this->model?>" ).empty();

		if( this.value ){
			new Preceptor.util.AjaxUpdate( "discipline_td<?=$this->model?>" , "<?=$this->url?>/relation/discipline/id/" + this.value );
		}
    });
</script>