<div>
	<label><?=$this->translate( "user" )?>:</label>
</div>

<div>
	<span><?=$this->formSelect( "person" , null , array( "id" => "{$this->model}-person" ) , $this->persons )?></span>
	<span><input type="button" id="<?=$this->model?>-person_button" value="<?=$this->translate("add")?>" /></span>
</div>

<br />

<script>
	YAHOO.util.Event.removeListener( "<?=$this->model?>-person_button" , "click" );

    $("#<?=$this->model?>-person_button").click(function(){
		relation_<?=$this->model?>.add( $( "#<?=$this->model?>-person" ).val , "person_id" , $( "#<?=$this->model?>-person" )[0].options[ $( "#<?=$this->model?>-person" )[0].selectedIndex ].innerHTML , "<?=$this->model?>"  );
	});
</script>