<div style="text-align: right;">
	<?php 
		if( $this->getPermission( "input" ) )
		{
			if( $this->user->role_id == Role::STUDENT )
			{
				if( $this->user->config->forum_student_created_topic == "true" )
				{
					echo $this->ajax( $this->translate("new") , "forum_input" , "/forum/forum/input" , 2 );
				}
			}
			else
			{
				echo $this->ajax( $this->translate("new") , "forum_input" , "/forum/forum/input" , 2 );
			}
		}	
	?>
</div>
<div id="forum_input"></div>
<br />
<div class="filter">
	<form action="#" id="formQForum">
		<div class="legend pos-relative"><?=$this->translate("filter")?></div>
		
		<label><?=$this->translate("word")?>:</label>
		<?=$this->formText( "q"  , $this->q  , array( "style" => "width: 16em" ) )?>
		
		<label><?=$this->translate("status")?>:</label>
		<?=$this->formSelect( "status" , $this->statusQ , null , $this->status )?>
		
		&nbsp; <input type="submit" value="ok" />
	</form>
</div>

<div id="forum_data">
	<?php if( $this->rs->count() ):?>
		<table class="datatable">
			<tr>
				<th colspan="2"><?=$this->translate( "author" )?></th>
				<th><?=$this->translate( "topic" )?></th>
				<th><?=$this->translate( "responses" )?></th>
				<th><?=$this->translate( "last post" )?></th>
				<th><?=$this->translate( "status" )?></th>
                                <?php if( $this->user->role_id != Role::STUDENT ):?>
                                    <th></th>
                                <?endif;?>
			</tr>
			
			<?php foreach( $this->rs as $rs ):?>
				
				<?php 
					$class   = $this->changeClass( $this->rs->key() , array( "gray" , "light_gray" ) );
					$person  = $rs->findParentRow( "Person" );
					$forum   = $rs->findDependentRowSet( "Forum" , null , $rs->getTable()->select()->order( "created DESC" ) );
					$current = $forum->current(); 
					$date 	 = $current->created ? $current->created. " " .$current->time : $rs->created;
				?>
				
				<tr class="<?=$class?>">
					<td width="55">
						<?=$this->image( "../upload/thumb_small" . $person->findParentRow( "File" )->location , array( 'width' => '50' ) )?>
					</td>
					<td width="75"><?=$person->name?></td>
					<td>
						<strong><?=$this->ajax( $this->escape( $rs->title ) , 'forum' , '/forum/forum/view/id/' . $rs->id );?></strong>
					</td>
					<td style="text-align: center;">
						<?=$forum->count()?>
					</td>
					<td><?=$date?></td>
					<td align="center">
						<?php if( $this->user->config->forum_download == "all" || $this->user->config->forum_download == $rs->status ): ?>
							<!-- download --> 
						<?php endif; ?>
						<?=$this->image( "icones/" . strtolower($rs->findParentRow( 'Status' )->name ) . ".gif" );?>
					</td>
                                        <?php if( $this->user->role_id != Role::STUDENT ):?>
                                            <td><?=$this->ajax( $this->translate( 'edit' ) , 'forum_input' , '/forum/forum/input/id/' . $rs->id );?></td>
                                        <?endif;?>
				</tr>
				
			<?php endforeach;?>
		</table>
		
		<br/>
		
		<?=$this->pagination( "forum" , "/forum/forum/index" , $this->to , $this->counts ) ?>
	<?php endif;?>
</div>
<script>
	YAHOO.util.Event.on( "formQForum" , "submit" , function( ev ){
			new Preceptor.util.AjaxUpdate( "forum_data" , "<?=$this->url?>/forum/forum/find/q/" + $( "q" ).value + "/status/" + $( "status" ).value );
			YAHOO.util.Event.stopEvent( ev );
	});
	<?php if( $this->q && $this->status ): ?>
		new Preceptor.util.AjaxUpdate( "forum_data" , "<?=$this->url?>/forum/forum/find/q/<?=$this->q?>/status/<?=$this->statusQ?>" );
	<?php endif; ?>
</script>