<?php if( $this->getPermission( "input" ) ): ?>
	<div class="right"><?=$this->ajax( $this->translate( "new" ) , 'activity-activity' , $this->url . '/activity/activity/input/' , 2 ); ?></div>
<?php endif; ?>

<br /><br />
<div>
	<?php if( ( $this->rs->count() ) || $this->grouped->count() ): ?>
		<table class="tablesorter">
            <thead>
                <tr>
                    <th><?=$this->translate("title")?></th>
                    <th><?=$this->translate("composition type")?></th>
                    <th><?=$this->translate("begin date")?></th>
                    <th><?=$this->translate("end date")?></th>
                    <?php if ( Share_Model_Role::STUDENT == $this->role ) : ?>
                        <th><?=$this->translate("status")?></th>
                    <?php endif; ?>
                    <?php if( $this->getPermission( array( "module" => "activity" , "controller" => "stage" , "action" => "index" ) ) ) : ?>
                        <th></th>
                    <?php endif; ?>
                    <?php if( $this->getPermission( array( "module" => "activity" , "controller" => "correct" , "action" => "index" ) ) ) : ?>
                        <th></th>
                    <?php endif; ?>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ( $this->rs as $rs ): ?>
                    <tr class="<?=$this->changeClass( $key , array( "even" , "odd" ) )?>">
                        <?php if ( $this->role == Share_Model_Role::STUDENT ) : ?>
                            <td width="100"><?=$this->ajax( $rs->title , "activity-activity" , $this->url . "/activity/stage/index/id/" . $rs->id );?></td>
                        <?php else : ?>
                            <td><?=$rs->title?></td>
                        <?php endif; ?>

                        <td><?=$this->translate("individual")?></td>

                        <?php if( $this->getPermission( "input" ) ): ?>
                            <?php $edit = $this->ajax( $this->translate('edit') , 'activity-activity' ,  $this->url . '/activity/activity/input/id/' . $rs->id ); ?>
                        <?php endif;?>

                        <?php if( $this->getPermission( "delete" ) ): ?>
                            <?php $delete = $this->ajax( $this->translate('delete') , 'activity-activity' , $this->url . '/activity/activity/delete/id/' . $rs->id , 1 , $this->translate('want to delete?') );?>
                        <?php endif;?>

                        <?php if( $this->getPermission( array( "module" => "activity" , "controller" => "correct" , "action" => "index" ) ) ) : ?>
                            <?php $correct = $this->ajax( $this->translate('correct') , 'activity-activity' ,  $this->url . '/activity/correct/index/id/' . $rs->id );  ?>
                        <?php endif;?>

                        <td nowrap="nowrap"><?=$this->date( $rs->started )?></td>
                        <td nowrap="nowrap"><?=$this->date( $rs->finished )?></td>
                        <?php if ( Share_Model_Role::STUDENT == $this->role ) : ?>
                            <td nowrap="nowrap">
                                <?php $status = $rs->findDependentRowset( 'Activity_Model_ActivityTextPerson' , null , $rs->select()->where( 'person_id =?' , $this->person_id )->order( 'id DESC' ) )->current()->status  ?>

                                <?php
                                if ( $status ) {
                                    switch ( $status ){
                                        case Activity_Model_ActivityTextPerson::SAVE_STUDENT:echo $this->translate('in progress');break;
                                        case Activity_Model_ActivityTextPerson::FINALITY_STUDENT:echo $this->translate('awaiting correction');break;
                                        case Activity_Model_ActivityTextPerson::SAVE_TEACHER:echo $this->translate('assessed (open)');break;
                                        case Activity_Model_ActivityTextPerson::FINALITY_TEACHER:echo $this->translate('assessed (finalized)');break;
                                    }
                                }
                                else
                                    echo $this->translate('in progress');
                                ?>
                            </td>
                        <?php endif; ?>
                        <?php if( $this->getPermission( array( "module" => "activity" , "controller" => "stage" , "action" => "index" ) ) ) : ?>
                            <td nowrap="nowrap"><?=$this->ajax( $this->translate('stage manage') , 'activity-activity' ,  $this->url . "/activity/stage/index/id/" . $rs->id );  ?>
                        <?php endif;?>

                        <?php if( $this->getPermission( array( "module" => "activity" , "controller" => "correct" , "action" => "index" ) ) ) : ?>
                            <td nowrap="nowrap"><?=$correct?></td>
                        <?php endif;?>

                        <td nowrap="nowrap" width="77"><?=$edit . " " . $delete?></td>
                    </tr>
                <?php endforeach;?>

                <?php foreach ( $this->grouped as $grouped ): ?>
                    <tr class="<?=$this->changeClass( $key , array( "even" , "odd" ) )?>">
                        <?php if ( $this->role == Share_Model_Role::STUDENT ) : ?>
                            <?php $title = $this->ajax( $grouped->title , "activity-activity" , $this->url . "/activity/stage/index/id/" . $grouped->aid . "/group_id/" . $grouped->id );?>
                            <?php $persons = $grouped->findManyToManyRowset( 'Share_Model_Person' , 'Activity_Model_ActivityGroupPerson' ); ?>

                        <?php else : ?>
                            <?php $title = $grouped->title?>
                            <?php if( $this->getPermission( array( "module" => "activity" , "controller" => "group" , "action" => "index"  ) ) ) : ?>
                                <?php  $group = "(" . $this->ajax( $this->translate('manage') , 'activity-activity' ,  $this->url . '/activity/group/index/id/' . $grouped->id ). ")" ?>
                            <?php endif; ?>
                        <?php endif; ?>

                        <?php if( $this->getPermission( "input" ) ): ?>
                            <?php $edit = $this->ajax( $this->translate('edit') , 'activity-activity' ,  $this->url . '/activity/activity/input/id/' . $grouped->id ); ?>
                        <?php endif;?>

                        <?php if( $this->getPermission( "delete" ) ): ?>
                            <?php $delete = $this->ajax( $this->translate('delete') , 'activity-activity' , $this->url . '/activity/activity/delete/id/' . $grouped->id , 1 , $this->translate('want to delete?') );?>
                        <?php endif;?>

                        <?php if( $this->getPermission( array( "module" => "activity" , "controller" => "correct" , "action" => "index" ) ) ) : ?>
                            <?php $correct = $this->ajax( $this->translate('correct') , 'activity-activity' ,  $this->url . '/activity/correct/index/id/' . $grouped->id . "/group_id/1" );  ?>
                        <?php endif;?>

                        <td nowrap="nowrap"><?=$title?></td>
                        <td nowrap="nowrap">
                            <?=$this->translate("grouped") . " " . $group ?>
                            <?php if ( isset( $persons ) ) : ?>
                                <ul>
                                    <?php foreach ( $persons as $person ) : ?>
                                        <li><?=$person->name ?></li>
                                    <?php endforeach;?>
                                </ul>
                            <?php endif; ?>
                        </td>
                        <td nowrap="nowrap"><?=$this->date( $grouped->started )?></td>
                        <td nowrap="nowrap"><?=$this->date( $grouped->finished )?></td>

                        <?php if ( Share_Model_Role::STUDENT == $this->role ) : ?>
                            <td nowrap="nowrap">
                                <?php $status = $grouped->findDependentRowset( 'Activity_Model_ActivityTextGroup' , null , $grouped->select()->where( 'activity_group_id =?' , $grouped->id )->order( 'id DESC' ) )->current()->status  ?>

                                <?php
                                if ( $status ) {
                                    switch ( $status ){
                                        case Activity_Model_ActivityTextPerson::SAVE_STUDENT:echo $this->translate('in progress');break;
                                        case Activity_Model_ActivityTextPerson::FINALITY_STUDENT:echo $this->translate('awaiting correction');break;
                                        case Activity_Model_ActivityTextPerson::SAVE_TEACHER:echo $this->translate('assessed (open)');break;
                                        case Activity_Model_ActivityTextPerson::FINALITY_TEACHER:echo $this->translate('assessed (finalized)');break;
                                    }
                                }
                                else
                                    echo $this->translate('in progress');
                                ?>
                            </td>
                        <?php endif; ?>
                        <?php if( $this->getPermission( array( "module" => "activity" , "controller" => "stage" , "action" => "index" ) ) ) : ?>
                            <td nowrap="nowrap"><?=$this->ajax( $this->translate('stage manage') , 'activity-activity' ,  $this->url . "/activity/stage/index/id/" . $grouped->id );  ?>
                        <?php endif;?>

                        <?php if( $this->getPermission( array( "module" => "activity" , "controller" => "correct" , "action" => "index" ) ) ) : ?>
                            <td nowrap="nowrap"><?=$correct?></td>
                        <?php endif;?>

                        <td nowrap="nowrap" width="77"><?=$edit . " " . $delete?></td>
                    </tr>
                <?php endforeach;?>
            </tbody>
		</table>
	<?php else: ?>
		<div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
	<?php endif; ?>
</div>