<?php if( $this->getPermission( "input" ) ): ?>	
	<div class="right"><?=$this->ajax( $this->translate( "new" ) , 'activity' , '/activity/activity/input/' , 2 ); ?></div>
<?php endif; ?>

<br /><br />
<div>
	<?php if( ( $this->rs->count() ) || $this->grouped->count() ): ?>
		<table class="datatable">
			<tr>
				<th><?=$this->translate("title")?></th>
				<th><?=$this->translate("composition type")?></th>
                <?php if ( Role::STUDENT != $this->role ) : ?>
                    <th><?=$this->translate("begin date")?></th>
                    <th><?=$this->translate("end date")?></th>
                <?php endif; ?>
				<?php if ( Role::STUDENT == $this->role ) : ?>
					<th><?=$this->translate("status")?></th>
				<?php endif; ?>
				<?php if( $this->getPermission( array( "module" => "activity" , "controller" => "stage" , "action" => "index" ) ) && $this->role != Role::STUDENT ) : ?>
					<th></th>
				<?php endif; ?>
				<?php if( $this->getPermission( array( "module" => "activity" , "controller" => "correct" , "action" => "index" ) ) ) : ?>
					<th></th>
				<?php endif; ?>
                <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                    <th></th>
                <?php endif; ?>
			</tr>
			
			<?php foreach ( $this->rs as $rs ): ?>
				<?php $class = $this->changeClass( $this->rs->key() , array( "light_gray" , "white" ) );?>
				<tr class="<?=$class?>">
					<?php if ( $this->role == Role::STUDENT ) : ?>
						<td><?=$this->ajax( $rs->title , "activity" , "/activity/stage/index/id/" . $rs->id );?></td>
					<?php else : ?>
						<td><?=$rs->title?></td>
					<?php endif; ?>
					
					<td><?=$this->translate("individual")?></td>
					
					<?php if( $this->getPermission( "input" ) ): ?>
						<?php $edit = $this->ajax( $this->translate('edit') , 'activity' ,  '/activity/activity/input/id/' . $rs->id ); ?>
					<?php endif;?>
				
					<?php if( $this->getPermission( "delete" ) ): ?>
						<?php $delete = $this->ajax( $this->translate('delete') , 'activity' , '/activity/activity/delete/id/' . $rs->id , 1 , $this->translate('want to delete?') );?>
					<?php endif;?>
					
					<?php if( $this->getPermission( array( "module" => "activity" , "controller" => "correct" , "action" => "index" ) ) ) : ?>
						<?//php $correct = $this->ajax( $this->translate('correct') , 'activity' ,  '/activity/correct/index/id/' . $rs->id );  ?>
					<?php endif;?>

					<?php if ( Role::STUDENT != $this->role ) : ?>
                        <td nowrap="nowrap"><?=$rs->started?></td>
                        <td nowrap="nowrap"><?=$rs->finished?></td>
                    <?php endif;?>
					<?php if ( Role::STUDENT == $this->role ) : ?>
						<td nowrap="nowrap">
							<?php $status = $rs->findDependentRowset( 'ActivityTextPerson' , null , $rs->select()->where( 'person_id =?' , $this->person_id )->order( 'id DESC' ) )->current()->status  ?>
							
							<?php 
							if ( $status ) {
								switch ( $status ){
									case ActivityTextPerson::SAVE_STUDENT:echo $this->translate('in progress');break; 
									case ActivityTextPerson::FINALITY_STUDENT:echo $this->translate('awaiting correction');break;
									case ActivityTextPerson::SAVE_TEACHER:echo $this->translate('assessed (open)');break;
									case ActivityTextPerson::FINALITY_TEACHER:echo $this->translate('assessed (finalized)');break;
								}
							}
							else
								echo $this->translate('in progress');
							?>
						</td>
					<?php endif; ?>
					<?php if( $this->getPermission( array( "module" => "activity" , "controller" => "stage" , "action" => "index" ) ) && $this->role != Role::STUDENT ) : ?>
						<td nowrap="nowrap"><?=$this->ajax( $this->translate('stage manage') , 'activity' ,  "/activity/stage/index/id/" . $rs->id );  ?>
					<?php endif;?>
					
					<?php if( $this->getPermission( array( "module" => "activity" , "controller" => "correct" , "action" => "index" ) ) ) : ?>
						<td nowrap="nowrap">
                                                    <?php echo $correct?>
                                                </td>
                                                
					<?php endif;?>
					<?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                        <td nowrap="nowrap" width="77"><?=$edit . " " . $delete?></td>
                    <?php endif;?>
				</tr>
			<?php endforeach;?>
			
			<?php foreach ( $this->grouped as $grouped ): ?>
				<?php $class = $this->changeClass( $this->grouped->key() , array( "light_gray" , "white" ) );?>
				<tr class="<?=$class?>">
					<?php if ( $this->role == Role::STUDENT ) : ?>
						<?php $title = $this->ajax( $grouped->title , "activity" , "/activity/stage/index/id/" . $grouped->aid . "/group_id/" . $grouped->id );?>
						<?php $persons = $grouped->findManyToManyRowset( 'Person' , 'ActivityGroupPerson' ); ?>
					<?php else : ?>
						<?php $title = $grouped->title?>
						<?php if( $this->getPermission( array( "module" => "activity" , "controller" => "group" , "action" => "index"  ) ) ) : ?>
							<?php $group = "(" . $this->ajax( $this->translate('manage') , 'activity' ,  '/activity/group/index/id/' . $grouped->id ). ")" ?>
						<?php endif; ?>
					<?php endif; ?>
					
					<?php if( $this->getPermission( "input" ) ): ?>
						<?php $edit = $this->ajax( $this->translate('edit') , 'activity' ,  '/activity/activity/input/id/' . $grouped->id ); ?>
					<?php endif;?>
				
					<?php if( $this->getPermission( "delete" ) ): ?>
						<?php $delete = $this->ajax( $this->translate('delete') , 'activity' , '/activity/activity/delete/id/' . $grouped->id , 1 , $this->translate('want to delete?') );?>
					<?php endif;?>
					
					<?php if( $this->getPermission( array( "module" => "activity" , "controller" => "correct" , "action" => "index" ) ) ) : ?>
						<?php $correct = $this->ajax( $this->translate('correct') , 'activity' ,  '/activity/correct/index/id/' . $grouped->id . "/group_id/1" );  ?>
					<?php endif;?>

					<td nowrap="nowrap"><?=$title?></td>
					<td nowrap="nowrap">
						<?=$this->translate("grouped") . " " . $group ?>
						<?php if ( $persons ) : ?>
							<ul>
								<?php foreach ( $persons as $person ) : ?>
									<li><?=$person->name ?></li>
								<?php endforeach;?>
							</ul>	
						<?php endif; ?>
					</td>
					<td nowrap="nowrap"><?=$grouped->started?></td>
					<td nowrap="nowrap"><?=$grouped->finished?></td>
					
					<?php if ( Role::STUDENT == $this->role ) : ?>
						<td nowrap="nowrap">
							<?php $status = $grouped->findDependentRowset( 'ActivityTextGroup' , null , $grouped->select()->where( 'activity_group_id =?' , $grouped->id )->order( 'id DESC' ) )->current()->status  ?>
							
							<?php 
							if ( $status ) {
								switch ( $status ){
									case ActivityTextPerson::SAVE_STUDENT:echo $this->translate('in progress');break; 
									case ActivityTextPerson::FINALITY_STUDENT:echo $this->translate('awaiting correction');break;
									case ActivityTextPerson::SAVE_TEACHER:echo $this->translate('assessed (open)');break;
									case ActivityTextPerson::FINALITY_TEACHER:echo $this->translate('assessed (finalized)');break;
								}
							}
							else
								echo $this->translate('in progress');
							?>
						</td>
					<?php endif; ?>
					<?php if( $this->getPermission( array( "module" => "activity" , "controller" => "stage" , "action" => "index" ) ) ) : ?>
						<td nowrap="nowrap"><?=$this->ajax( $this->translate('stage manage') , 'activity' ,  "/activity/stage/index/id/" . $grouped->id );  ?>
					<?php endif;?>
					
					<?php if( $this->getPermission( array( "module" => "activity" , "controller" => "correct" , "action" => "index" ) ) ) : ?>
						<td nowrap="nowrap"><?=$correct?></td>
					<?php endif;?>
					
					<td nowrap="nowrap" width="77"><?=$edit . " " . $delete?></td>
				</tr>
			<?php endforeach;?>
		</table>
	<?php else: ?>
		<p><?=$this->translate("there are no records");?></p>
	<?php endif; ?>
</div>