<?=$this->element()->startForm();?>

<div class="yui-skin-sam" id="div-form-<?=$this->model?>">
    <?php
        echo $this->element()->formHidden( "id" , $this->data->id , array( "printLabel" => false ) )
                  ->formText( "title" , $this->data->title )
                  ->formText( "started" , $this->date( $this->data->started ) , array( "label" => $this->translate("begin date") , "style" => "width: 115px" ) )
                  ->formText( "finished" , $this->date( $this->data->finished ), array( "label" => $this->translate("end date") , "style" => "width: 115px" )  )
                  ->formSelect( "composition_type" , $this->data->composition_type , array( "label" => $this->translate("composition type") ) , $this->composition )
                  ->formSubmit( "model" , $this->translate("save") , array( "printLabel" => false ) )
    ?>
</div>
<?=$this->formRelation( $this->data->id )?>