<?php if( ( $this->getPermission( "input" ) ) && ( ! $this->rs ) ): ?>	
	<div class="right"><?=$this->ajax( $this->translate( "new") , "certificate" , "/certificate/certificate/input/group_id/{$this->group_id}" , 2 ); ?></div>
<?php endif ?>
<div class="clear"></div>
<br />

<?php if( $this->rs ): ?>
	<table class="datatable">
		<tr>
			<th><?=$this->translate("title")?></th>
			<th><?=$this->translate("hour load (hour)")?></th>
			<th><?=$this->translate("begin date")?></th>
			<th><?=$this->translate("end date")?></th>
			<?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
			 	<th></th>
			<?php endif;?>
		</tr>
		
		<?php if( $this->getPermission( "input" ) ): ?>
			<?php $edit = $this->ajax( $this->translate("edit") , 'certificate' , '/certificate/certificate/input/id/' . $this->rs->id ); ?>
		<?php endif;?>
		
		<?php if( $this->getPermission( "delete" ) ): ?>
			<?php $delete = $this->ajax( $this->translate("delete") , 'certificate' , "/certificate/certificate/delete/id/{$this->rs->id}" , 1 , $this->translate("want to delete?") );?>
		<?php endif;?>
		
		<tr>
			<td nowrap="nowrap"><?=$this->rs->title?></td>
			<td nowrap="nowrap"><?=$this->rs->hours?></td>
			<td nowrap="nowrap"><?=$this->date( $this->rs->started ) ?></td>
			<td nowrap="nowrap"><?=$this->date( $this->rs->finished ) ?></td>
			<?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
				<td nowrap="nowrap"><?=$edit . " " . $delete?></td>
			<?php endif;?>
		</tr>
	</table>
<?php else: ?>
	<table class="datatable">
		<tr class="<?=$class?>">
			<td><?=$this->translate( "there are no records" );?></td>
		</tr>
	</table>
<?php endif; ?>
