<div class="right">
    <?php echo $this->ajax('back', 'exercise/index', 2) ?>
</div>
<div class="activity">
<?php echo $this->form?>
</div>
<script type="text/javascript">
	$(".activity form").submit(function() {
        var $this = $(this);
		$.post('activity/index/save', $(this).serialize(), function(data){
            $this.parents('.content').html(data);
        });
        return false;
	});
    $('.date').datepicker();
    $('#status').other();
    $('input[type=button], input[type=submit]').button();
</script>