<div>
    <?php if( $this->getPermission( "input" ) ): ?>
        <div class="right"><?=$this->ajax( $this->translate( "new" ) , "rss-rss" , $this->url . "/rss/rss/input/" , 2 );?></div>
    <?php endif; ?>
    <div class="clear"></div>
    <br />

	<?php if( $this->rs->count() ):?>
		<table class="tablesorter">
            <thead>
                <tr>
                    <th class="channel"><?=$this->translate("channels")?></th>
                    <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                        <th></th>
                    <?php endif;?>
                </tr>
            </thead>

            <tbody>
                <?php foreach( $this->rs as $rs ): ?>
                    <?php if( $this->getPermission( "input" ) ): ?>
                        <?php $edit = $this->ajax( $this->translate("edit") , 'rss-rss' , "{$this->url}/rss/rss/input/id/" . $rs->id); ?>
                    <?php endif;?>

                    <?php if( $this->getPermission( "delete" ) ): ?>
                        <?php $delete = $this->ajax( $this->translate("delete") , 'rss-rss' , "{$this->url}/rss/rss/delete/id/" . $rs->id , 1 , $this->translate("want to delete?") );?>
                    <?php endif;?>

                    <tr class="<?=$this->changeClass( $this->rs->key() , array( "even" , "odd" ) )?>">
                        <td width="90%"><?=$this->ajax( $rs->channel , 'rss-rss' , "{$this->url}/rss/rss/view/id/". $rs->id );?></td>
                        <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                            <td nowrap="nowrap"><?=$edit . " " . $delete?></td>
                        <?php endif;?>
                    </tr>
                <?php endforeach;?>
            </tbody>
		</table>
<?php else:?>
    <div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif;?>
</div>
