<?=$this->element()->startForm();?>
<div class="yui-skin-sam" id="div-form-<?=$this->model?>">

    <?php
        echo $this->element()->formHidden( "id" , $this->data->id , array( "printLabel" => false ) )
                  ->formText( "channel" , $this->data->channel , array( "label" => $this->translate("title") ) )
                  ->formText( "url" , $this->data->url )
                  ->formSubmit( "model" , $this->translate("save") , array( "printLabel" => false ) );
    ?>
    
</div>
<?=$this->formRelation( $this->data->id )?>
