<div id="toolbar">
	<div style="float: right">
		<?php if( $this->controller === "content" ): ?>
	       	<a href="javascript:Preceptor.widget.use.setBannerAreas( '<?=Banner::BANNER_AREAS?>' , 'div' , { host: '<?=$this->url?>/' , content: '<?=$this->content?>'} );">Mostrar Banners</a>
	    <?php endif; ?>
		
		<a href="<?=$this->url?>/user/logout/">Sair</a>
	</div>
	<div style="float: left;">	
		<a href="<?=$this->url?>/content/input/id/<?=$this->rs->id?>">Novo</a>
		
		<?php if( $_SESSION['contents'][count($_SESSION['contents'] ) - 1] != $this->id_tool ): ?>
			<a href="<?=$this->url?>/content/delete/id/<?=$this->rs->id?>/contentId/<?=$this->rs->content_id?>" onclick="if( !confirm( 'Deseja realmente excluir?' ) ) return false;">Excluir</a>
		<?php endif; ?>
	</div>
</div>