<div class="exercise">
    <div class="left">
        <?php echo $this->form?>
    </div>
    <?php if ($this->id):?>
        <div style="margin-left: 200px" id="question-list">
            <h3><?php echo $this->translate("Question's list")?></h3>
            <?php if (count($this->questions)) :?>
                <?php foreach($this->questions as $question):?>
                    <div class="question">
                        <input type="button" value="<?php echo $this->translate('remove')?>" />&nbsp;
                        <input type="hidden" value="<?php echo $question->id?>" />
                        <?php echo strip_tags($question->description)?>
                    </div>
                <?php endforeach;?>
            <?php else: ?>
                <p><?php echo $this->translate('there are no records')?></p>
            <?php endif;?>
            <br />
            <input class="add" type="button" value="<?php echo $this->translate('add')?>" />
        </div>
    <?php endif;?>
</div>
<script type="text/javascript">
    (function(){
        var toRemove = [];
        
        $(".exercise form").submit(function() {
            var $this = $(this),
                data = $this.serialize();

            $('.exercise .question input[type=hidden]').each(function(){
                data += '&question_id[]=' + this.value;
            });

            if (toRemove.length) {
                data += '&remove_id[]=' + toRemove.join('&remove_id[]=');
            }

            $.post(this.action, data, function(data) {
                $this.parents('.content').html(data);
            });

            return false;
        });


        $('.exercise .question input[type=button]').live('click', function(){
            var $this = $(this);
            toRemove.push($this.next().val());
            $this.parent().remove();
        });

        $('.exercise .add').click(function() {
            var $this = $(this);

            $.get('exercise/question/index/id/<?php echo $this->id?>/layout/box', function(data){
                $this.parents('.box').before(data);
            });
        });

        $('.date').datepicker();
        $('#status').other();
        $('#question-list').sortable();
        $('.question').css('cursor','move');

        $('input[type=button], input[type=submit]').button();
    })();
</script>