<div class="exercise">
<?php echo $this->form?>
</div>
<script type="text/javascript">
	$(".exercise form").submit(function() {
        var $this = $(this);
		$.post(this.action, $this.serialize(), function(data) {
            $this.parents('.content').html(data);
        });
        return false;
	});
    $('.date').datepicker();
    $('#status').other();
    
    $('input[type=button], input[type=submit]').button();
</script>