<div class="padding left">
    <label for="type"><?=$this->translate("type")?>:</label>&nbsp;
    
    <input id="restriction-bulletin" name="type" type="radio" value="<?=Content_Model_Restriction::EVALUATION ?>" > <?=$this->translate("performance")?>&nbsp;
	<input id="restriction-time" checked='checked' name="type" type="radio" value="<?=Content_Model_Restriction::TIME ?>" > <?=$this->translate("time")?>&nbsp;
    <div class="clear"></div>
</div>	
<div>
	<div class="right">
		<?php if( $this->getPermission( "input" ) ): ?>
			<?=$this->ajax( $this->translate("new") , "content-restriction" , $this->url . "/content/restriction/input/type/" . Content_Model_Restriction::TIME , 2 ) ?>
		<?php endif; ?>
	</div>
	<div class="clear"></div>
	<br />
	<?php if( $this->rs->count() ):?>
			<table class="datatable">
				<tr>
	                <th><?=$this->translate("date init")?></th>
	                <th><?=$this->translate("date expired")?></th>
	                <th><?=$this->translate("content")?></th>
	                <th><?=$this->translate("action")?></th>
				</tr>
				<?php foreach( $this->rs as $rs ): ?>
					<?php $class  = $this->changeClass( $this->rs->key() , array( "light_gray" , "white" ) );?>
					
					<tr class="<?=$class?>">
						<td><?=$this->date( $rs->started ) ?></td>
	                    <td><?=$this->date( $rs->finished )?></td>
	                    <td nowrap="nowrap">
							<?=$rs->findParentRow('Content_Model_Restriction')
								  ->findParentRow('Content_Model_Content')->title?>
						</td>
	                    <td width="100">
	                        <?=$this->ajax( $this->translate("edit") , "content-restriction" , $this->url . "/content/restriction/input/id/" . $rs->id . "/type/" . Content_Model_Restriction::TIME )?> |
	                        <?=$this->ajax( $this->translate("delete") , "content-restriction" , $this->url . "/content/restriction/delete/id/" . $rs->id . "/type/" . Content_Model_Restriction::TIME , 1, $this->translate( "want to delete?" ) )?>
	                    </td>
					</tr>
				<?php endforeach;?>
			</table>  
	<?php else:?>
		<table class="datatable">
			<tr class="<?=$class?>">
				<td><?=$this->translate( "there are no records" );?></td>
			</tr>
		</table> 
	<?php endif;?>
</div>
<script>
	$('#restriction-bulletin').click(function(){
		new Preceptor.util.AjaxUpdate( "content-restriction" , "<?=$this->url?>/content/restriction/index/" );
	});

	$('#restriction-time').click(function(){
		new Preceptor.util.AjaxUpdate( "content-restriction" , "<?=$this->url?>/content/restriction/index/type/" + this.value );
	});
</script>