<?=$this->element()->startForm( array( "action" => "$this->url/person/save-new" ) );?>
<?php
    echo $this->element()->formHidden( "id" , null , array( "printLabel" => false ) )
              ->formHidden( "discipline_id" , $this->discipline_id , array( "printLabel" => false ) );
?>
<div class="right">
    <?=$this->ajax( $this->translate('back') , "default-course" , "$this->url/discipline/register/" , 2 , null )?>
</div>

<div id="message-cpf-email">
    <b><?=$this->translate('please Email CPF and valid')?></b>
</div>

<br />

<div>
    <?php
        echo $this->element()->formText( "cpf" , null , array( "style" => "width: 150px;" , "label" => "CPF" ) )
                  ->formText( "email" , null , array( "class" => "input-medium" ) );
     ?>

    <p>
        <input type="button" id="verify-data" value="<?=$this->translate( "verify" )?>" />
        <input type="button" id="refresh-data" value="<?=$this->translate( "refresh" )?>" />
    </p>
    
    <script type="text/javascript">
        $( "#verify-data" ).click( function(){
            new Preceptor.util.AjaxUpdate( "message-cpf-email" , "<?=$this->url?>/person/verify-data-new/cpf/" + $( '#<?=$this->model?>-cpf' ).val() + "/email/" + $( '#<?=$this->model?>-email' ).val() );
        });

        $( "#refresh-data" ).click( function(){
            $( "#verify-data" ).show();
            $( "#form-fields-complete" ).hide();
            $( "#<?=$this->model?>-model" ).attr( "disabled" , "disabled" );
            $( "#<?=$this->model?>-cpf , #<?=$this->model?>-email" ).removeAttr( "disabled" );
            share_model_person.clearMessages();
            $( this ).hide();
        }).hide();
    </script>
    <br />
    <div id="form-fields-complete" class="none">
        <?php
            echo $this->element()->formText( "name" , null , array( "class" => "input-medium" ) )
                      ->formText( "phone" , null , array( "style" => "width: 150px;" ) );
        ?>

        <div class="clear"></div>

        <?php
            echo $this->element()->formText( "zip_code" , null , array( "label" => $this->translate('zip code') , "style" => "width: 150px;" , "class" => "left" ) );
        ?>
        <script type="text/javascript">
            $( "#Share_Model_Person-zip_code" ).blur( function(){
                if( jQuery.trim( this.value ) && parseInt( this.value ) > 0 ){
                    new Preceptor.util.AjaxUpdate( "address-person" , "<?=$this->url?>/address/find-address/cep/" + this.value );
                }
            });

        </script>

        <div id="address-person" class="clear"></div>

        <?php
            echo $this->element()->formPassword( "password" , null , array( "style" => "width: 150px;" , "model" => "Share_Model_User" ) )
                      ->formPassword( "confirmation" , null , array( "style" => "width: 150px;" , "model" => "Share_Model_User" , "label" => $this->translate( "password confirms" ) ) );
        ?>

        <div class="clear">&nbsp;</div>
        
        <?php echo $this->element()->formSubmit( "model" , $this->translate("save") , array( "printLabel" => false ) ); ?>
    </div>
</div>
<script type="text/javascript">
    $( "#<?=$this->model?>-phone" ).mask( "(99)9999-9999" );
    $( "#<?=$this->model?>-zip_code" ).mask( "99999-999" );

    $( "#<?=$this->model?>-model" ).attr( "disabled" , "disabled" );

	share_model_person.success = function(){
        $( "#<?=$this->model?>-cpf , #<?=$this->model?>-email" ).removeAttr( "disabled" );
        
        new Preceptor.util.AjaxUpdate( 'default-course' , '<?=$this->url?>/person/save-new/' , { formId:"Share_Model_Person" } );
	}

</script>
<div class="clear">&nbsp;</div>
