<div>
	<form action="#" id="formLayout" name="formLayout">
	    <div id="optionsForLayout">
				<?php foreach($this->modules as $key_modulos => $value): ?>
					<?php
                        $checked = "";

                        if( $this->type->layout_organization ){
                            foreach( $this->type->layout_organization as $key => $module ){
                                if($module['div'] == $key_modulos ){
                                    $checked = "checked";
                                }
                            }
                        }else{
                            if($key_modulos == "content" ){
                                $checked = "checked";
                            }
                        }
                    ?>
                    
					<div class="left" style="width: 48%; margin: 3px; background: #EFEFEF; padding: 3px;" >
						<input type="checkbox" id="<?=$key_modulos?>" name="optionsLayout[]" value="<?=$value?>" <?=$checked?>/> <label style="display: inline;" for="<?=$key_modulos?>"><?=$this->translate( $key_modulos )?></label>
					</div>
				<?php endforeach; ?>
				
    	</div>

		<div class="clear"></div>
	
		<br /><br />
		
		<?=$this->formHidden( "relation" )?>
		
		<div class="filter">
			<div class="legend"><?=$this->translate( "apply to" )?>:</div>
			
			<input type="radio" name="option" value="course_id" checked="checked" /> <?=$this->translate( "course" )?> &nbsp; 
			<input type="radio" name="option" value="discipline_id" /> <?=$this->translate( "discipline" )?> &nbsp; 
			<input type="radio" name="option" value="group_id" /> <?=$this->translate( "group" )?>
		</div>
		
		<input type="button" onclick="runLayout();" value="<?=$this->translate("save")?>" />
	</form>
</div>		        