<form id="formMessage_<?=$this->suffix;?>" action="#">
	<div>
		<? $editMessage = $this->idMessage->toArray(); ?>
		<?=$this->formTextarea( "ds" ,  $editMessage[0]["ds"] , array( "id" => "ds_" . $this->suffix, "style" => "width: 100%; height: 80px" ) )?>
		<?=$this->formHidden( "person_receiver_id" , $this->rs->id , array( "id" => "person_receiver_id_" . $this->suffix ) )?>
		<?=$this->formHidden( "id" , $editMessage[0]["id"] , array( "id" => "id_" . $this->suffix ) )?>
		
		<input type="submit" id="message_submit" value="<?=$this->translate( "save" );?>" />
	</div>
</form>

<script>
	clearTimeout( refresh );
	Preceptor.util.Validate.prototype.onsubmit = function(){ 
		YAHOO.util.Event.on( 'formMessage_<?=$this->suffix?>' , 'submit' , function( ev ){
			if( this.verify( $( 'formMessage_<?=$this->suffix?>' ) ) )
			{
				new Preceptor.util.AjaxUpdate( this.div , this.url , { formId: this.formId } );
			}
			
			YAHOO.util.Event.stopEvent( ev );
			
		} , this , true );
	}
</script>

<?=$this->validate( "formMessage_{$this->suffix}" , $this->jsonValidate , $this->suffix , $this->url . "/chat/message/save/" , "message" ); ?>