<div class="list-user" >
    <h3><?php echo $this->translate('User list')?></h3>
    <div class="list">
        <?php if ($this->users) :?>
            <?php foreach($this->users as $user):?>
                <div class="item">
                    <img alt="<?php echo $user->name ?>" src="upload/<?php echo $this->thumbnail($user->image, 'small') ?>" />
                    <?php $text = $user->name . ' (' . $this->translate($user->role).')';?>
                    <?php echo $this->ajax($text, 'chat/message/index/userId/'.$user->id)?>
                </div>
            <?php endforeach;?>
        <?php endif;?>
    </div>
</div>
<?php if ($this->userId != Zend_Auth::getInstance()->getIdentity()->id):?>
    <div class="message">
        <?php echo $this->form?>
    </div>
<?php endif;?>
<?php if(count($this->data)):?>
<table class="datatable" style="width: 75%">
        <?php foreach($this->data as $data): ?>
            <tr>
                <td>
                    <img alt="<?php echo $data->name ?>" src="upload/<?php echo $this->thumbnail($data->image, 'small') ?>" /><br />
                    <?php echo $data->name ?><br />
                    <?php echo $this->date($data->created)?>
                </td>
                <td><?php echo nl2br($data->description)?></td>
                <td nowrap="nowrap">
                    <?php $id = Zend_Auth::getInstance()->getIdentity()->id;?>
                    <?php if ($data->sender == $id || $this->userId == $id) :?>
                        <?php if ($this->userId != Zend_Auth::getInstance()->getIdentity()->id):?>
                            <?php echo $this->ajax("edit", 'chat/message/index/id/'. $data->id.'/userId/'.$this->userId, 2); ?>
                        <?php endif; ?>
                        <?php echo $this->ajax("delete", 'chat/message/delete/id/' . $data->id.'/userId/'.$this->userId, 2 , "want to delete?");?>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach;?>
        </table>
        <div id="notepad-page">
            <?php echo $this->paginationControl($this->data) ?>
        </div>
<?php else:?>
    <p><?=$this->translate( "there are no records" );?></p>
<?php endif;?>
<script type="text/javascript">
    $(".message form").submit(function() {
        var $this = $(this);
		$.post(this.action, $(this).serialize(), function(data){
            $this.parents('.content').html(data);
        });
        return false;
	});
    
    $('input[type=button], input[type=submit]').button();
</script>