<div class="message">
<div style="background: #EFEFEF; border: dashed #6F6F6F 1px; padding: 3px; height: 15px">
	<?=$this->ajax( $this->translate( "my messages" ) , 'chat-message' , "{$this->url}/chat/message/view/id/{$this->person}" );?>
	(<?=$this->rsMessages->count(); ?>)
</div>
<br />
<table class="datatable">
	<tr>
		<th><?=$this->translate( "teacher" )?></th>
	</tr>
</table>

<?php if ( $this->teachers->count() ) :?>
	<?php foreach( $this->teachers as $teacher ): ?>
		<?php $teacherRow = $teacher->findParentRow("Share_Model_Person"); ?>
		<div class="left frame">
			<a href="/message/input" onclick="new Preceptor.util.AjaxUpdate( 'chat-message' , '<?=$this->url;?>/chat/message/view/id/<?=$teacherRow->id;?>' );return false;">
				<div align="center" style="margin: 2px; ">
					<img src="<?=$this->url;?>/file/file/download/read/true/file/<?=base64_encode('thumb_small'.$teacherRow->location)?>" width="63" />
					<div id="messageProfile_<?=$this->suffix;?>" class="messageProfile"><div><?=$teacherRow->name;?></div></div>
				</div>
			</a>
		</div>
	<?php endforeach; ?>
<?php else: ?>
	<table class="datatable">
		<tr class="<?=$class?>">
			<td><?=$this->translate( "there are no records" );?></td>
		</tr>
	</table>
<?php endif; ?>

<div class="clear"></div>
<br />

<table class="datatable">
	<tr>
		<th><?=$this->translate( "friend" )?></th>
	</tr>
</table>

<?php if ( $this->friends->count() ) :?>
	<?php foreach( $this->friends as $friend ): ?>
		<?php $friendRow = $friend->findParentRow("Share_Model_Person"); ?>
		<div class="left frame">
			<a href="/message/index" onclick="new Preceptor.util.AjaxUpdate( 'chat-message' , '<?=$this->url;?>/chat/message/view/id/<?=$friendRow->id;?>' );return false;">
				<div align="center" style="margin: 2px; ">
					<img src="<?=$this->url;?>/file/file/download/read/true/file/<?=base64_encode('thumb_small'.$teacherRow->location)?>" width="63" />
					<div id="messageProfile_<?=$this->suffix;?>" class="messageProfile"><div><?=$friendRow->name;?></div></div>
				</div>
			</a>
		</div>
	<?php endforeach; ?>
<?php else: ?>
	<table class="datatable">
		<tr class="<?=$class?>">
			<td><?=$this->translate( "there are no records" );?></td>
		</tr>
	</table>
<?php endif; ?>

<div class="clear"></div>
</div>