<br/>
<?php echo $this->form?>
<script type="text/javascript" charset="utf-8">
	$('.message-reply-textarea').find('textarea').removeAttr('cols').removeAttr('rows').css({'width':'100%', 'height':'60px'});
	
	$(".message-reply-textarea form").submit(function() {
        var $this = $(this);
		$.post(this.action, $this.serialize(), function(data){
            $this.parents('.content').html(data);
        });
        return false;
	});
	
	$('input[type=button], input[type=submit]').button();
</script>