<div>
	<div style="background: #EFEFEF; border: dashed #6F6F6F 1px; padding: 3px;"> <b>Nome:</b> <?=$this->rs->name; ?> &nbsp;&nbsp;&nbsp;&nbsp; <b>Email:</b> <?=$this->rs->email ?> </div>
	<br />
	<div class="left" id="photoUser">	
		<img width="100" src="<?=$this->url;?>/file/file/download/read/true/file/<?=base64_encode('thumb_medium'.$this->rs->location)?>" />
	</div>
	
    <div class="left" style="margin-left: 10px; width: 85%;">
        <?php
            echo $this->element()->startForm()
                      ->formHidden( "id" , null , array( "printLabel" => false ) )
                      ->formTextarea( "ds" , null , array( "label" => $this->translate("description") , "style" => "width: 100%; height: 80px" ) )
                      ->formHidden( "person_receiver_id" , $this->rs->id , array( "printLabel" => false ) )
                      ->formSubmit( "save" , $this->translate("save") , array( "printLabel" => false ) )
                      ->endForm();
        ?>
    </div>

</div>
<div class="clear"></div>
<br />
<div id="mensageView">

		<?php if( count($this->rsMessages) ):?>
			<table class="datatable" width="99%" cellpadding="5">
				<tr>
					<th><?=$this->translate( "photo" )?></th>
					<th><?=$this->translate( "comments" )?></th>
					<th colspan="2"><?=$this->translate( "date" )?></th>
				</tr>
					<?php foreach( $this->rsMessages as $message ):?>
					<?php $personSender = $message->findParentRow("Share_Model_Person", "Person_Sender"); ?>
					<?php $class = $this->changeClass( $this->rsMessages->key() , array( "light_gray" , "white" ) );?>
					
					<tr class="<?=$class?>">
						<td width="80">
							<img src="<?=$this->url;?>/file/file/download/read/true/file/<?=base64_encode('thumb_small'.$personSender->location)?>" width="63" /><br />
							<div id="messageProfile_<?=$this->suffix;?>" class="messageProfile"><div><?=$personSender->name;?></div></div>
						</td>
						<td><?=nl2br( $this->escape( $message->ds ) )?></td>
						<td width="80" align="right"><?=$this->date( $message->created , "H:i d/m/Y" ); ?></td>
						<td width="84" align="right" >
							<?php if( $message->person_sender_id == $this->person ||  $message->person_receiver_id == $this->person ) : ?>
								<?php if( $message->person_sender_id == $this->person ): ?>
									 &nbsp;&nbsp;<?=$this->ajax( $this->translate( "edit" ) , "chat-message" , "{$this->url}/chat/message/view/id/{$this->rs->id}/idMessage/{$message->id}" )?>
								<?php endif; ?>
								<?=$this->ajax( $this->translate( "delete" ) , "chat-message" , "{$this->url}/chat/message/delete/userId/" . $message->person_receiver_id ."/id/" . $message->id , 1 , $this->translate("want to delete?") )?>
							<?php endif; ?>
						</td>	
					</tr>
				<?php endforeach;?>
			</table>
			
			<br/>
			
		<?=$this->pagination( "chat-message" , "message/message/index" , $this->to , $this->counts ) ?>
		<?php else: ?>
			<table class="datatable">
				<tr class="<?=$class?>">
					<td><?=$this->translate( "there are no records" );?></td>
				</tr>
			</table>
		<?php endif;?>
</div>
<script>
	<?php if ( isset($this->data->id) ): ?>
		setTimeout( function(){ document.getElementById( 'Chat_Model_Message-ds' ).focus(); } , 100 );
	<?php endif; ?>
	
	 chat_model_message.success = function(){
        new Preceptor.util.AjaxUpdate( 'chat-message' , '<?=$this->url?>/chat/message/save' , { formId:"Chat_Model_Message" } );
    }
</script>