<div>
	<div style="background: #EFEFEF; border: dashed #6F6F6F 1px; padding: 3px;"> <b>Nome:</b> <?=$this->rs->name; ?> &nbsp;&nbsp;&nbsp;&nbsp; <b>Email:</b> <?=$this->rs->email ?> </div>
	<br />
	<div class="left" id="photoUser">
    <?=$this->image( "../upload/thumb_medium" . $this->rs->findParentRow( "File" )->location , array( 'width' => '120' ) )?><br />
	</div>
	
	<form  id="formMessage_<?=$this->suffix;?>" action="#">
		<div class="left" style="margin-left: 10px; width: 85%;">
			<?=$this->formHidden( "id" , $this->data->id , array( "id" => "id_" . $this->suffix ) )?>
			<?=$this->formTextarea( "ds" ,  $this->data->ds , array( "id" => "ds_" . $this->suffix, "style" => "width: 100%; height: 80px" ) )?>
			<?=$this->formHidden( "person_receiver_id" , $this->rs->id , array( "id" => "person_receiver_id_" . $this->suffix ) )?>
            <p>Total de caracteres: <span id="number-string_<?=$this->suffix;?>">1400</span></p>
			<input type="submit" id="message_submit" value="<?=$this->translate( "save" );?>" />
		</div>
	</form>
    
</div>
<div class="clear"></div>
<br />
<div id="mensageView">

		<?php if( $this->rsMessages->count() ):?>
			<table class="datatable" width="99%" cellpadding="5">
				<tr>
					<th><?=$this->translate( "photo" )?></th>
					<th><?=$this->translate( "comments" )?></th>
					<th colspan="2"><?=$this->translate( "date" )?></th>
				</tr>
					<?php foreach( $this->rsMessages as $message ):?>
					<?php $personSender = $message->findParentRow("Person", "Person_Sender"); ?>
					<?php $class = $this->changeClass( $this->rsMessages->key() , array( "light_gray" , "white" ) );?>
					
					<tr class="<?=$class?>">
						<td width="80">
							<?=$this->image( "../upload/thumb_small" . $personSender->findParentRow("File")->location , array( 'width' => '70' ) )?><br />
							<div id="messageProfile_<?=$this->suffix;?>" class="messageProfile"><div><?=$personSender->name;?></div></div>
						</td>
						<td><?=nl2br( $this->escape( $message->ds ) )?></td>
						<td width="80" align="right"><?=$this->date( $message->created , "H:i d/m/Y" ); ?></td>
						<td width="84" align="right" >
							<?php if( $message->person_sender_id == $this->person ||  $message->person_receiver_id == $this->person ) : ?>
								<?php if( $message->person_sender_id == $this->person ): ?>
									 &nbsp;&nbsp;<?=$this->ajax( $this->translate( "edit" ) , "message" , "{$this->url}/chat/message/view/id/{$this->rs->id}/idMessage/{$message->id}" )?>
								<?php endif; ?>
								<?=$this->ajax( $this->translate( "delete" ) , "message" , "{$this->url}/chat/message/delete/userId/" . $message->person_receiver_id ."/id/" . $message->id , 1 , $this->translate("want to delete?") )?>
							<?php endif; ?>
						</td>	
					</tr>
				<?php endforeach;?>
			</table>
			
			<br/>
			
		<?=$this->pagination( "message" , "message/message/index" , $this->to , $this->counts ) ?>
		<?php else: ?>
			<table class="datatable">
				<tr class="<?=$class?>">
					<td><?=$this->translate( "there are no records" );?></td>
				</tr>
			</table>
		<?php endif;?>
</div>
<script>
    jQuery('#ds_<?php echo $this->suffix;?>').keyup( function(){
        var text    = jQuery( this ).val(),
        nString = 1400 - text.length;

        if( nString <= 0 ){
            jQuery(this).val( text.substr('0', '1400') );
            jQuery('#number-string_<?php echo $this->suffix;?>').html( '0' );
        }else{
            jQuery('#number-string_<?php echo $this->suffix;?>').html( nString );
        }
    });

    jQuery('#button-registration-<?php echo $this->id?>').click( function(){
        new Preceptor.util.AjaxUpdate( 'dialog-modal-<?=$this->id?>' , '<?php echo $this->url?>/course/save-pre-registration/id/<?php echo $rs->id?>' , {formId:"form-registration-<?php echo $this->id?>"} );
    });
	<?php if ( $this->data->id ): ?>
		setTimeout( function(){ document.getElementById( 'ds_<?=$this->suffix?>' ).focus(); } , 100 );
	<?php endif; ?>
	
	Preceptor.util.Validate.prototype.onsubmit = function(){ 
		YAHOO.util.Event.on( 'formMessage_<?=$this->suffix?>' , 'submit' , function( ev ){
			if( this.verify( $( 'formMessage_<?=$this->suffix?>' ) ) )
			{
				new Preceptor.util.AjaxUpdate( this.div , this.url , { formId: this.formId } );
			}
			
			YAHOO.util.Event.stopEvent( ev );
			
		} , this , true );
	}
</script>
<?=$this->validate( "formMessage_{$this->suffix}" , $this->jsonValidate , $this->suffix , "/chat/message/save/" , "message" ); ?>