<div id="drag" style="cursor: move;display: block;width: 99%">
	<h3 style="float: left;"></h3>
	<a style="float: right;color: black;text-decoration: underline;" href="#focus" onclick="Lightbox.destroy( 'treeviewRelationForm' , '/form/form/input/period/true/id/<?=$this->form_id?>' )">X</a>
	<div style="clear: both;"></div>
</div>
<?=$this->render("input.phtml")?>
<br />
<?php if( $this->rs->count() ):?>
	<table class="datatable">
		<tr>
			<th><?=$this->translate("date init")?></th>
			<th><?=$this->translate("date expired")?></th>
			<?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
				<th width="77px"></th>
			<?php endif;?>	
		</tr>
		<?php foreach( $this->rs as $rs ): ?>
			<?php $class  = $this->changeClass( $this->rs->key() , array( "light_gray" , "white" ) );?>
			
			<?php if( $this->getPermission( "input" ) ): ?>
				<?php $edit = $this->ajax( $this->translate("edit") , 'edit' , '/period/period/input/id/' . $rs->id ); ?>
			<?php endif;?>
			
			<?php if( $this->getPermission( "delete" ) ): ?>
				<?php $delete = $this->ajax( $this->translate("delete") , 'category' , "/period/period/delete/id/{$rs->id}" , 1 , $this->translate("want to delete?") );?>
			<?php endif;?>
			
			<tr class="<?=$class?>">
				<td nowrap="nowrap"><?=$rs->entered?></td>
				<td nowrap="nowrap"><?=$rs->expired?></td>
				<?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
					<td nowrap="nowrap"><?=$edit . " " . $delete?></td>
				<?php endif;?>
			</tr>
		<?php endforeach;?>
	</table>  
<?php else:?>
	<?=$this->translate( "there are no records" );?>
<?php endif;?>