<div>
	<?php if( $this->rs->count() ): ?>
        <p><b><?php echo $this->activity->title?></b></p>
		<table class="datatable">
			<tr>
				<th><?=$this->translate("photo");?></th>
				<th><?=$this->translate("name");?></th>
			</tr>
			<?php $verify = false ?>
			<?php foreach ( $this->rs as $rs ): ?>
				<?php $class = $this->changeClass( $this->rs->key() , array( "light_gray" , "white" ) );?>
				<?php if ( $rs->status == ActivityTextPerson::FINALITY_STUDENT ) : ?>
					<?php $verify = true ?>
					<tr class="<?=$class?>">
						<td width="77">
							<?=$this->image( "../upload/thumb_small" . $rs->findParentRow( "Person" , "SP" )->findParentRow( "File" )->location )?>
						</td>
						<td nowrap="nowrap"><?=$this->ajax( $rs->findParentRow( "Person" , "SP" )->name , 'activity' ,  '/activity/correct/input/person_id/' . $rs->person_id ); ?></td>
					</tr>
				<?php endif; ?>
				
			<?php endforeach;?>
		</table>
		<?php if ( ! $verify ) : ?>
			<p><?=$this->translate("there are no records");?></p>
		<?php endif; ?>
	<?php else: ?>
		<p><?=$this->translate("there are no records");?></p>
	<?php endif; ?>
</div>