<?php if( $this->stage->count() ): ?>
	<ul class="bread">
		<?php foreach( $this->stage as $rs ): ?>
			<?php $arrow = "&raquo;"?>
			<a href="#this" onclick="Toogle.showOneHiddenAll( 'stage<?=$rs->id?>' )"><?=$rs->title?></a> <?=$arrow ?>
			<script>Preceptor.util.elements.push( "stage<?=$rs->id?>" );</script>
			<?php if( ( $this->role == Role::STUDENT ) && ( ($this->rs->key() + 1) == $this->rs->count() ) && ( $this->getPermission( array( "module" => "activity" , "controller" => "text" , "action" => "input"  ) ) ) ): ?>
				<a href="#this" onclick='new Preceptor.util.AjaxUpdate( "text" , "<?=$this->url ?>/activity/text/input/" );' ><?=$this->translate("make")?></a>
			<?php endif; ?>
		<?php endforeach;?>
	</ul>

	<?php $this->stage->rewind(); ?>
	<?php foreach( $this->stage as $rs ): ?>
		<div id="stage<?=$rs->id?>" class="gray padding">
                    <h4><?=$rs->title?></h4>
                    <p><?=$rs->dss?></p>
                    <br /><br />
                    <?php if( $this->rs->key() > 0 ): ?>
                            <input type="button" onclick="Toogle.previous();" value="<?=$this->translate("previous")?>" />
                    <?php endif; ?>

                    <?php if( ($this->rs->key() + 1) < $this->rs->count() ): ?>
                            <input type="button" onclick="Toogle.next();" value="<?=$this->translate("next")?>" />
                    <?php endif; ?>
		</div>

	<?php endforeach;?>
<?php endif; ?>
<br />
<script>
	Toogle = new Preceptor.util.Toggle( Preceptor.util.elements );
</script>

<div id="input_text">
	<div id="text_update" class="left" style="width: 86%">
		<form id="formText_<?=$this->suffix?>">
			
			<label for="ds_<?=$this->suffix?>"><?=$this->translate("description")?>:</label>
			<?=$this->formTextarea( "ds" , $this->rs->current()->ds , array( "id" => "ds_" . $this->suffix ) )?>
			<br /><br />
			<input id="textSubmit" type="submit" value="<?=$this->translate("save")?>" />
			<input id="finalizingSubmit" type="button" value="<?=$this->translate("save and finalizing")?>" />
			
		</form>
	</div>
</div>
<div>&nbsp;</div>
<div class="clear">&nbsp;</div>
<div id="version">
	<h3><?=$this->translate("versions")?></h3>
	<hr />
	
	<?php if( $this->rs->count() ): ?>
		<ul>
			<?php foreach( $this->rs as $rs ): ?>
				<li>
					<?=$this->ajax( $this->date( $rs->created , "d/m/Y H:i:s" ) , "input_text" , "/activity/correct/input/version_id/{$rs->id}" );?> - 
					<?=$rs->findParentRow( "Person" , "SP" )->name?>
				</li>
			<?php endforeach; ?>
		</ul>
	<?php else: ?>
		<p><?=$this->translate("there are no records")?></p>
	<?php endif; ?>
</div>
<script>
	
	var Editor_<?=$this->suffix?> = new Preceptor.widget.Editor( "ds_<?=$this->suffix ?>" , { addButton:["createPaleta", "insertHtml"] } );
	
	Preceptor.util.Validate.prototype.onsubmit = function(){ 
		YAHOO.util.Event.on( 'formText_<?=$this->suffix?>' , 'submit' , function( ev ){
			
			Editor_<?=$this->suffix?>.saveHTML();
			
			if( this.verify( $( 'formText_<?=$this->suffix?>' ) ) )
			{
				new Preceptor.util.AjaxUpdate( this.div , this.url , { formId: this.formId } );
			}
			
			YAHOO.util.Event.stopEvent( ev );
			
		} , this , true );
	}
	
	 
	YAHOO.util.Event.on( 'finalizingSubmit' , 'click' , function( ev ){
		
		Editor_<?=$this->suffix?>.saveHTML();
		
		if( formText_<?=$this->suffix ?>_validate.verify( $( 'formText_<?=$this->suffix?>' ) ) )
		{
			if( confirm( "<?=$this->translate("really finish?")?>" ) )
				new Preceptor.util.AjaxUpdate( "activity" , "<?=$this->url ?>/activity/correct/finalizing" , { formId:"formText_<?=$this->suffix?>" } );
			
		}	
		
		YAHOO.util.Event.stopEvent( ev );
		
	} );
	
	
</script>
<?=$this->validate( "formText_{$this->suffix}" , $this->jsonValidate , $this->suffix , "/activity/correct/save/" , "activity"  ); ?>
