<div>
	<?php if( count( $this->rs ) ): ?>
		<form action="#" id="form_organizer">
			<ul class="organizer" id="organizer">
				<?php foreach( $this->rs as $rs ): ?>
					<li id="organizer_li_<?=$rs['id']?>"><?=$this->ajax( $rs['title'] , "content-organizer" , $this->url . "/content/organizer/index/id/" . $rs['id'] )?></li>
				<?php endforeach; ?>
			</ul>
			<br />
			<input type="hidden" name="json" id="organizer_hidden" />

			<input type="submit" id="organizer_submit" value="<?=$this->translate("save")?>" />

		</form>
		<script>
			$("#organizer").sortable();

			$( '#form_organizer').submit(function(){
				var data = [], value = {},	json;

				$("#organizer li").each( function(i,node){
					value = { id: 0 , position: 0 };
					value.id = node.id.replace( "organizer_li_" , "" );
					value.position = i + 1;

					data.push( value );
				});

				json = YAHOO.lang.JSON.stringify( data );
				$( "#organizer_hidden" ).val( json );
				
				new Preceptor.util.AjaxUpdate( "content-organizer" , "<?=$this->url?>/content/organizer/save/id/<?=$this->content?>" , { formId:"form_organizer" } )

				return false;
			});
		</script>
	<?php else: ?>
		<p><?=$this->translate( "there are no records" );?></p>
	<?php endif; ?>
</div>