<div class="box">

	<div title="Mover janela" id="<?=$this->controller?>Drag" class="drag header">
		<div class="rgt"></div>
		<div class="lft"></div>
		<div class="ctr">
			<h3><?=$this->translate( $this->controller );?></h3>
			<div id="boxToolbar">
				<a style="text-decoration: none;" href="#this" onclick="toggleEdit( true )" title="<?=$this->translate("disable editing mode")?>"><?=$this->image( "icones/lapis_off.gif" )?></a>
				<a href="#ajuda" title="Ajuda" style="cursor: help;" onclick="Preceptor.util.Toggle.showHidden( 'help<?=$this->controller?>' )" >?</a>
			</div>
			<div class="clear"></div>
		</div>
	</div>

	<div id="main<?=$this->controller?>" class="main">

		<?php if( $this->help ): ?>
			<div class="help" id="help<?=$this->controller?>">
				<?=$this->help?>
			</div>
		<?php endif; ?>

		<div id="composer-main">
			<div class="nav">
				<div class="right">
					<?php if( $this->getPermission( "input" ) ): ?>
						<?=$this->ajax( $this->translate("new") , "composer-main-content" , "/composer/composer/input" , 2 ) ?>
					<?php endif; ?>
				</div>

				<a href="#this" id="composer-previous-nav">&lt; <?=$this->translate( "previous" )?></a>
				<?=$this->recursiveSelect( "select_composer_id_nav" , $this->content , null , $this->contents )?>

                 <div style="display: none;">
                    <?=$this->recursiveSelect( "select_composer_id" , $this->content , null , $this->contents )?>
                 </div>
				<a href="#this" id="composer-next-nav"><?=$this->translate( "next" )?> &gt;</a>
			</div>

			<?php if( $this->messages ): ?>
				<div class="message" id="message<?=$id?>">
					<ul>
						<?php foreach( $this->messages as $key => $val ): ?>
							<li><?=$val?></li>
						<?php endforeach; ?>
					</ul>
				</div>
			<?php endif; ?>

			<script>validate = [];</script>
			<?php if( $this->validate ): ?>
				<div id="validate">
					<?php foreach( $this->validate as $key => $val ): ?>
						<ul>
							<li>
								<span id="<?=$key?>_validate"></span>
								<ul>
									<?php foreach( $val as $val2 ): ?>
										<li><?=$val2?></li>
									<?php endforeach; ?>
								</ul>
							</li>
						</ul>
						<script>validate.push( '<?=$key?>' )</script>
					<?php endforeach; ?>
				</div>

				<br style="clear: both" />
			<?php endif; ?>

			<div id="composer-main-content" class="content">
                        </div>
                        <label><?=$this->translate("description")?>:</label>
                        <textarea id="magic-editor"></textarea>

			<br /><br />
			
			
		</div>

		<div class="clear">&nbsp;</div>
	</div>

	<div id="footer<?=$this->controller?>" class="footer">
		<div class="rgt"></div>
		<div class="lft"></div>
		<div class="ctr"></div>
		<div class="clear"></div>
	</div>
</div>

<script>
		var id = $( 'select_composer_id' ).value;

		window.Editor_Composer = new Preceptor.widget.Editor( "magic-editor" , { addButton:["uploadImage", "insertHtml"] , content:true } );

		<?php if( !$this->content ): ?>
			id = 0;
		<?php endif; ?>

		new Preceptor.util.AjaxUpdate( 'composer-main-content' , '<?=$this->url?>/composer/composer/input/id/' + id , { onComplete:
		function(){
			<?php if( $this->validate ): ?>
				if( validate.length )
				{
					for( var i = 0; i < validate.length; i++ )
					{
						var label_for = validate[i];
						$( validate[i] ).className = "erro";
						var label = YAHOO.util.Dom.getElementsBy( function(el){
							forAttribute = el.getAttribute('for') || el.getAttribute('htmlFor');
							return forAttribute == label_for;
						} , "label" );
						$( validate[i] + "_validate" ).innerHTML = label[0].innerHTML;
					}
				}
			<?php endif; ?>
		}});

		YAHOO.util.Event.on( "select_composer_id_nav" , "change" , function(){
			if( verifyChanged() ){
                selectContent( 'select_composer_id' , this.value );
				new Preceptor.util.AjaxUpdate( 'composer-main-content' , '<?=$this->url?>/composer/composer/input/id/' + this.value );
            }
		});

		YAHOO.util.Event.on( "composer-previous-nav" , "click" , function(){
			if( verifyChanged() )
				contentNav( '<?=$this->url?>/composer/composer/input/id/' , false , 'select_composer_id' , 'composer-main-content' );
		});

		YAHOO.util.Event.on( "composer-next-nav" , "click" , function(){
			if( verifyChanged() )
				contentNav( '<?=$this->url?>/composer/composer/input/id/' , true , 'select_composer_id' , 'composer-main-content' );
		});
</script>