<form id="form_composer_<?=$this->suffix?>" action="#">
    <?=$this->formHidden( "id" , $this->data->id )?>

    <div class='right'>
        <input type="button" id="bank-image" value="<?=$this->translate("Banco de Imagens")?>" />
        <?=$this->formSubmit( "submit_composer" , $this->translate("save") );?>
        <input type="button" id="composer-delete" value="<?=$this->translate("delete")?>" />
    </div>

    <label><?=$this->translate("title")?>:</label>
    <?=$this->formText( "title" , $this->data->title , array( "id" => "title_" . $this->suffix , "style" => "width: 400px;" ) )?>

    <label>Pertence a:</label>
    <?=$this->formSelect( "content_id" , $this->data->content_id , array( "id" => "content_id_" . $this->suffix ) , $this->contents )?>
    <br /><br />
    
    <?php if( !$this->parent ): ?>
        <textarea name="ds" id="composer-main-editor" style='display:none'>
                <?=$this->data->ds?>
        </textarea>

    <br /><br/>
    <?php endif; ?>
</form>
<script type="text/javascript">
    /*xed = new xq.Editor("composer-main-editor");
    xed.config.macroIds = [];
    xed.addPlugin('EditorResize');
    xed.addPlugin('CustomStyle');
    xed.addPlugin('FlashMovieMacro');
    xed.addPlugin('LinkToImage');

    xed.setEditMode('wysiwyg');
    xed.setWidth("100%");

    jQuery('#bank-image').click( function(){
        runElementMeio( URL + '/file/folder/' , 'folder' );
    });*/


<?php if( !$this->parent ): ?>
            window.Editor_Composer.setEditorHTML( document.getElementById('composer-main-editor').value );

            Preceptor.util.Validate.prototype.onsubmit = function(){
                YAHOO.util.Event.on( 'form_composer_<?=$this->suffix?>' , 'submit' , function( ev ){

                    window.Editor_Composer.saveHTML();
                    //jQuery('#composer-main-editor').val(xed.getCurrentContent());
                    document.getElementById('composer-main-editor').value = document.getElementById('magic-editor').value;

                    if( this.verify( $( 'form_composer_<?=$this->suffix?>' ) ) ){
                        new Preceptor.util.AjaxUpdate( 'composer-main-content' , this.url , { formId: this.formId } );
                    }

                    YAHOO.util.Event.stopEvent( ev );
                } , this , true );
            }

            hasChanged = false;

<?php endif?>

            YAHOO.util.Event.on( "composer-delete" , "click" , function(){
                if( confirm( "<?=$this->translate("want to delete?")?>" ) )
                {
                    new Preceptor.util.AjaxUpdate( null , '<?=$this->url?>/composer/composer/delete/id/<?=$this->data->id?>' , { onComplete:function(){
                            contentNav( '<?=$this->url?>/composer/composer/index/id/' , false , 'select_composer_id' , 'composer' );
                        } } );
                }
            });
</script>
<?=$this->validate( "form_composer_{$this->suffix}" , $this->jsonValidate , $this->suffix , "/composer/composer/save" , "composer" , true ); ?>