<div class="left">
    <input type="text" name="q" id="qGlossary" style="width: 16em" />
    <input type="submit" value="OK" id="buttonGlossary" />
</div>
<div class="alphabet">
	<?=$this->ajax( '0-9' , 'glossary-glossary' , $this->url . '/glossary/glossary/index/q/%5B0-9%5D' ); ?>
	<? $letters = array( 'a' , 'b' , 'c' , 'd' , 'e' , 'd' , 'f' , 'g' , 'h' , 'i' , 'j' , 'k' , 'l' , 'm' , 'n' , 'o' , 'p' , 'q' , 'r' , 's' , 't' , 'u' , 'v' , 'w' , 'x' , 'y' , 'z' ); ?>
	
	<?php foreach( $letters as $letter ): ?>
		<?=$this->ajax( strtoupper( $letter ) , 'glossary-glossary' , $this->url . '/glossary/glossary/index/q/' . $letter ); ?>
	<?php endforeach; ?>
</div>
<script type="text/javascript">
    $( "#glossaryQWeblibrary" ).submit( function(){
		new Preceptor.util.AjaxUpdate( 'glossary-glossary' , '<?=$this->url?>/glossary/glossary/index/q/' + $( '#qGlossary' ).val() );
        return false;
    })
</script>