<div class="right">
    <?php echo $this->ajax('back', 'activity/index', 2) ?>
</div>
<?php $locale = strtolower(str_replace('_', '-', $this->locale))?>
<h3><?php echo $this->parent->title?></h3>
<p><?php echo $this->parent->description?></p>
<div class="left activityText">
    <?php echo $this->form?>
</div>
<div class="right" style="width: 25%">
    <?php if (count($this->data)):?>
        <h3><?php echo $this->translate('last versions')?></h3>
        <table class="datatable">
                <?php foreach ($this->data as $key => $data): ?>
                    <tr>
                        <td width="50">
                            <img title="<?php echo $data->name ?>" alt="<?php echo $data->name ?>" src="upload/<?php echo $this->thumbnail($data->image, 'small') ?>" /><br />
                        </td>
                        <td nowrap="nowrap"><?php echo $this->ajax($this->date($data->created, true), "activity/text/index/nav/true/id/" . $this->id . "/textId/" . $data->id . "/userId/" . $this->userId)?></td>
                    </tr>
                <?php endforeach;?>
        </table>
    <?php endif;?>
</div>
<script type="text/javascript">
    $('#activity-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $(".activityText form input[type=submit]").click(function(){
        $(".activityText #status").val(this.name);
    });

    $('#note-element').after('<br />');

    $('input[type=button], input[type=submit]').button();
    
    if(!navigator.userAgent.match(/iPhone/i)) {
        var $text = $('#text-description-text'),
            config = {
                toolbar: [
                    ['Source','-','Preview','Templates'],
                    ['Cut','Copy','Paste','PasteText','PasteFromWord'],
                    ['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],
                    '/',
                    ['TextColor','BGColor'],
                    ['Bold','Italic','Underline','Strike'],
                    ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote','CreateDiv'],
                    ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
                    '/',
                    ['Link','Unlink','Anchor'],
                    ['Image','Flash','Table','HorizontalRule','SpecialChar'],
                    ['Styles']
                ],language: '<?php echo $locale?>'
            },
            editor = CKEDITOR.appendTo('description-element', config, $text.val());
        $text.hide();
    }

    $(".activityText form").submit(function() {
        var $this = $(this);
        if(!navigator.userAgent.match(/iPhone/i)) {
            $text.val(editor.getData());
        }
		$.post(this.action, $this.serialize(), function(data){
            $this.parents('.content').html(data);
        });
        return false;
	});
</script>