<h3><?php echo $this->parent->title?></h3>
<p><?php echo $this->parent->description?></p>
<div class="left activityText">
    <?php echo $this->form?>
</div>
<div class="right" style="width: 25%">
    <h3><?php echo $this->translate('last versions')?></h3>
    <table class="datatable">
        <?php if (count($this->data)):?>
            <?php foreach ($this->data as $key => $data): ?>
                <tr>
                    <td width="100">
                        <img alt="<?php echo $data->name ?>" src="upload/<?php echo $this->thumbnail($data->image, 'small') ?>" /><br />
                        <?php echo $data->name?>
                        <?php if ($data->role != 'student'):?>
                            (<?php echo $this->translate($data->role)?>)
                        <?php endif;?>
                    </td>
                    <td><?php echo $this->ajax($this->date($data->created), "activity/text/index/id/" . $this->id . "/textId/" . $data->id)?></td>
                </tr>
            <?php endforeach;?>
        <?php endif;?>
    </table>
</div>
<script type="text/javascript">
    $('#activity-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $(".activityText form").submit(function() {
        var $this = $(this);
		$.post('activity/text/save', $(this).serialize(), function(data){
            $this.parents('.content').html(data);
        });
        return false;
	});
</script>