<?php if ( ( ! $this->rs->count() )
           || ( ( $this->rs->current()->status == Activity_Model_ActivityTextPerson::SAVE_STUDENT )
           || ( $this->rs->current()->status == Activity_Model_ActivityTextPerson::SAVE_TEACHER ) ) ) :?>

	<div id="input_text" class="yui-skin-sam">
		
		<div id="text_update" class="left" style="width: 80%">
			<?php
				if ( $this->activity->group_id ){
					$model = "Activity_Model_ActivityTextGroup";
				}else{
					$model = "Activity_Model_ActivityTextPerson";
				}
				
				
		    	echo $this->element()->startForm( array( 'id' => $model ) )
		                         	 ->formTextarea( "ds" ,  null , array( "label" => $this->translate("description") , 'model' => $model ) )
		                         	 
		    ?>
            <br />
            <label for="name-version" class="inline"><?=$this->translate("version name")?>:</label>
            <?=$this->formText( "data[$model][name]" ,  null , array( "printLabel" => false , "style" => "width: 115px"  ) )?>

            <br /><br />
            <input id="textSubmit" type="submit" value="<?=$this->translate("version save")?>" />
			<input id="finalizingSubmit" type="button" value="<?=$this->translate("save and finalizing")?>" />

			<?=$this->element()->endForm(); ?>
		</div>
	</div>
	<div class="clear">&nbsp;</div>
	<div id="version">
		<h3><?=$this->translate("versions")?></h3>
		<hr />
		
		<?php if( $this->rs->count() ): ?>
			<ul>
				<?php foreach( $this->rs as $rs ): ?>
					<li>
                        <?php
                            $name = isset( $rs->name ) && $rs->name ? $rs->name : $this->date( $rs->created , "d/m/Y H:i:s" );
                        ?>
						<?=$this->ajax( $name , "input_text" , $this->url . "/activity/text/input/id/{$rs->id}" );?> -
						<?=$rs->findParentRow( "Share_Model_Person" , 'SP' )->name?>&nbsp;&nbsp;
                        <?php if( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::INSTITUTION ):?>
                            <?= $this->ajax( $this->translate('edit') , 'input_text' , "{$this->url}/activity/text/input/id/{$rs->id}" ); ?>&nbsp;
                            <?= $this->ajax( $this->translate('delete') , 'activity-text' , "{$this->url}/activity/text/delete/id/{$rs->id}" , 1 , $this->translate('want to delete?') ); ?>
                        <?php endif;?>
					</li>
				<?php endforeach; ?>
			</ul>
		<?php else: ?>
			<div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
		<?php endif; ?>
	</div>

	<script type="text/javascript">
        var el = null;

		var	Editor_<?=$model?> = new Preceptor.widget.Editor( "<?=$model?>-ds" , { addButton:["createPaleta", "insertHtml"], height: '350px' , noAutoHeight: true } );

	    $("#textSubmit").click(function(){
            el = this.id;
	        Editor_<?=$model?>.saveHTML();
	    });
		
		<?=strtolower($model)?>.success = function(){
            if( el == "textSubmit" ){
                new Preceptor.util.AjaxUpdate( 'version' , '<?=$this->url?>/activity/text/save/' , { formId:'<?=$model?>' } );
            }else if( el == "finalizingSubmit" ){
                if( confirm( "<?=$this->translate("really finish?")?>" ) ){
					new Preceptor.util.AjaxUpdate( "activity-activity" , "<?=$this->url ?>/activity/text/finalizing" , { formId:"<?=$model?>" } );
                }
            }
            
            el = null;
	    }
	    
		$( "#finalizingSubmit" ).click( function(){
            el = this.id;
			Editor_<?=$model?>.saveHTML();
        });
	</script>
<?php else : ?>
    <div class="message-table-sorter">
        <?=$this->translate("this activity has been finalized.watch for a correction")?>
    </div>
<?php endif; ?>