<h3><?=$this->translate("versions")?></h3>
<hr />

<?php if( $this->rs->count() ): ?>
	<ul>
		<?php foreach( $this->rs as $rs ): ?>
			<li>
				<?=$this->ajax( $this->date( $rs->created , "d/m/Y H:i:s" ) , "input_text" , "/activity/text/input/id/{$rs->id}" );?> - 
				<?=$rs->findParentRow( "Person" , "SP" )->name?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php else: ?>
	<p><?=$this->translate("there are no records");?></p>
<?php endif; ?>