<h3><?=$this->translate("versions")?></h3>
<hr />

<?php if( $this->rs->count() ): ?>
	<ul>
		<?php foreach( $this->rs as $rs ): ?>
			<li>
                <?php
                    $name = isset( $rs->name ) && $rs->name ? $rs->name : $this->date( $rs->created , "d/m/Y H:i:s" );
                ?>
                <?=$this->ajax( $name , "input_text" , $this->url . "/activity/text/input/id/{$rs->id}" );?> -
                <?=$rs->findParentRow( "Share_Model_Person" , 'SP' )->name?>&nbsp;&nbsp;
                <?php if( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::INSTITUTION ):?>
                    <?= $this->ajax( $this->translate('edit') , 'input_text' , "{$this->url}/activity/text/input/id/{$rs->id}" ); ?>&nbsp;
                    <?= $this->ajax( $this->translate('delete') , 'activity-text' , "{$this->url}/activity/text/delete/id/{$rs->id}" , 1 , $this->translate('want to delete?') ); ?>
                <?php endif;?>
            </li>
		<?php endforeach; ?>
	</ul>
<?php else: ?>
	<p><?=$this->translate("there are no records");?></p>
<?php endif; ?>