<div id="text_update" class="left" style="width: 80%">
	<?php
		if ( $this->activity->group_id ){
			$model = "Activity_Model_ActivityTextGroup";
		}else{
			$model = "Activity_Model_ActivityTextPerson";
		}
		
    	echo $this->element()->startForm( array( 'id' => $model ) )
                         	 ->formTextarea( "ds" , $this->data->ds , array( "label" => $this->translate("description") , 'model' => $model ) );

        if( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::INSTITUTION ){
            echo $this->element()->formHidden( "id" , $this->data->id , array( "printLabel" => false , 'model' => $model ) );
        }
                         	 
    ?>
    <br />
    <label for="name-version" class="inline"><?=$this->translate("version name")?>:</label>
    <?=$this->formText( "data[$model][name]" , isset( $this->data->name ) ? $this->data->name : null , array( "printLabel" => false , "style" => "width: 115px"  ) )?>

    <br /><br />
	<input id="textSubmit" type="submit" value="<?=$this->translate("save")?>" />
	<input id="finalizingSubmit" type="button" value="<?=$this->translate("save and finalizing")?>" />
	
	<?=$this->element()->endForm(); ?>
</div>

<script type="text/javascript">
	
	var	Editor_<?=$model?> = new Preceptor.widget.Editor( "<?=$model?>-ds" , { addButton:["createPaleta", "insertHtml"] , height: '350px' , noAutoHeight: true } );

	$("#textSubmit").click(function(){
            el = this.id;
	        Editor_<?=$model?>.saveHTML();
	    });

    $( "#finalizingSubmit" ).click( function(){
        el = this.id;
        Editor_<?=$model?>.saveHTML();
    });
    
    <?=strtolower($model)?>.success = function(){
        if( el == "textSubmit" ){
            new Preceptor.util.AjaxUpdate( 'version' , '<?=$this->url?>/activity/text/save/' , { formId:'<?=$model?>' } );
        }else if( el == "finalizingSubmit" ){
            if( confirm( "<?=$this->translate("really finish?")?>" ) ){
                new Preceptor.util.AjaxUpdate( "activity-activity" , "<?=$this->url ?>/activity/text/finalizing" , { formId:"<?=$model?>" } );
            }
        }

        el = null;
    }
</script>