<?php if ( $this->rs->current()->status == Activity_Model_ActivityTextPerson::FINALITY_TEACHER ) : ?>
	<h3><?=$this->translate("finished activity")?></h3>
	<hr>
	<br />
	
	<?php if ( !$this->data->ds ) : ?>
		<?=$this->rs->current()->ds ?>
	<?php else : ?>
		<?=$this->data->ds ?>
	<?php endif; ?>
	<br /><br />
	
	<div id="version">
		<h3><?=$this->translate("versions")?></h3>
		<hr />
		<?php if( $this->rs->count() ): ?>
			<ul>
				<?php foreach( $this->rs as $rs ): ?>
					<li>
						<?=$this->ajax( $this->date( $rs->created , "d/m/Y H:i:s" ) , "activity-activity" , $this->url . "/activity/text/view/version_id/{$rs->id}" );?> -
						<?=$rs->findParentRow( "Share_Model_Person" , "SP" )->name?>
					</li>
				<?php endforeach; ?>
			</ul>
		<?php else: ?>
			<p><?=$this->translate("there are no records")?></p>
		<?php endif; ?>
	</div>
<?php else: ?>
	<div class="message">
		<p><?=$this->translate("activity is not yet finalized")?></p>
	</div>
<?php endif; ?>