<?php echo $this->doctype(); ?>
<?php $locale = str_replace('_', '-', $this->locale)?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $this->locale?>" xml:lang="en">
	<head>
		<title>Trilhas - Preceptor Educação a Distância</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <base href="<?php echo $this->serverUrl() . $this->baseUrl() ?>/" />
        <link rel="shortcut icon" href="favicon.ico" />

        <?php echo $this->headLink()->appendStylesheet('css/themes/' . $this->theme . '/jquery-ui.css')
							->appendStylesheet('css/utils.css')
							->appendStylesheet('css/main.css')
							->appendStylesheet('css/admin.css'); ?>

        <?php if(strstr($_SERVER['HTTP_USER_AGENT'],'iPhone') || strstr($_SERVER['HTTP_USER_AGENT'],'iPod')):?>
            <link rel="stylesheet" type="text/css" href="css/iphone.css" />
            <meta name="viewport" content="user-scalable=no, width=device-width" />
            <meta name="apple-mobile-web-app-capable" content="yes" />
            <link rel="apple-touch-icon" href="<?php echo $this->serverUrl() . $this->baseUrl() ?>/img/iphoneIcon.png" />
            <link rel="apple-touch-startup-image" href="<?php echo $this->serverUrl() . $this->baseUrl() ?>/img/iphoneStartup.png" />
        <?php endif; ?>

        <?php $this->headScript()->appendFile('js/jquery/jquery.min.js')
                                 ->appendFile('js/jquery/jquery-ui.min.js')
                                 ->appendFile('js/ckeditor/ckeditor.js');
              if ($locale != 'en') { $this->headScript()->appendFile('js/jquery/ui/i18n/jquery.ui.datepicker-' . $locale . '.js'); }
              if ($locale != 'en') { $this->headScript()->appendFile('js/ckeditor/lang/' . strtolower($locale) . '.js'); }
		      $this->headScript()->appendFile('js/jquery/jquery-ui.min.js')
                                  ->appendFile('js/jquery/jquery.other.js')
                                  ->appendFile('js/yahoo/yahoo-dom-event.js')
                                  ->appendFile('js/yahoo/json-min.js')
                                  ->appendFile('js/chat.js')
                                  ->appendFile('js/navigation.js');
              echo $this->headScript();?>
	</head>
    <body>
        <div id="hd">
            <h1>Trilhas</h1>
            <a href="index"><img src="css/themes/<?php echo $this->theme?>/images/logo.png" alt="Logo Trilhas" /></a>
            <?php if(Zend_Auth::getInstance()->hasIdentity()):?>
                <div style="float: right;">
                    <?php echo Zend_Auth::getInstance()->getIdentity()->name?>
                    (<?php echo $this->translate(Zend_Auth::getInstance()->getIdentity()->role)?>)
                    <?php if(count($this->groups) > 2): ?>
                        <?php echo $this->formSelect('group_id', $this->user->group_id, array('class' => 'select_profile', 'style' => 'margin-left: 6px; margin-right: 6px; height: 18px;') , $this->groups);?> |
                    <?php endif ?>
                    <a href="dashboard"><?php echo $this->translate('dashboard');?></a>&nbsp;
                    <a href="user/logout"><?php echo $this->translate('logout');?></a>
                </div>
            <?php endif; ?>
            <?php if (count($this->pages)) :?>
                <div class="pages">
                    <ul>
                        <?php foreach ($this->pages as $page) :?>
                            <li><a href="page/index/view/id/<?php echo $page->id?>"><?php echo $page->title?></a></li>
                        <?php endforeach;?>
                    </ul>
                </div>
            <?php endif;?>
        </div>
        <div id="bd">
            <?php if ($this->messages):?>
                <div class="ui-state-highlight ui-corner-all message">
                    <span class="ui-icon ui-icon-info"></span>
                    <ul>
                        <?php foreach ($this->messages as $message): ?>
                            <li><?php echo $this->translate($message)?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <br />
            <?php endif;?>
            <div id="menu">
                <div class="button">
                    <?php if ($this->isAllowed(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'))):?>
                        <a href="admin/course/index/" class="ui-state-default ui-corner-all">
                            <span class="ui-icon ui-icon-document"></span><?php echo $this->translate('course')?>
                        </a>
                    <?php endif;?>
                    <?php if ($this->isAllowed(array('module' => 'admin', 'controller' => 'acl', 'action' => 'index'))):?>
                        <a href="admin/acl/index/" class="ui-state-default ui-corner-all">
                            <span class="ui-icon ui-icon-document"></span><?php echo $this->translate('acl')?>
                        </a>
                    <?php endif;?>
                    <?php if ($this->isAllowed(array('module' => 'default', 'controller' => 'classroom', 'action' => 'form'))):?>
                        <a href="admin/classroom" class="ui-state-default ui-corner-all">
                            <span class="ui-icon ui-icon-note"></span><?php echo $this->translate('classroom')?>
                        </a>
                    <?php endif;?>
                    <?php if ($this->isAllowed(array('module' => 'selection-process', 'controller' => 'index', 'action' => 'index'))):?>
                        <a href="selection-process" class="ui-state-default ui-corner-all">
                            <span class="ui-icon ui-icon-folder-open"></span><?php echo $this->translate('selection process')?>
                        </a>
                    <?php endif;?>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role == 'institution'):?>
                        <a href="admin/user" class="ui-state-default ui-corner-all">
                            <span class="ui-icon ui-icon-person"></span><?php echo $this->translate('user')?>
                        </a>
                    <?php endif;?>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role == 'institution'):?>
                        <a href="page" class="ui-state-default ui-corner-all">
                            <span class="ui-icon ui-icon-document-b"></span><?php echo $this->translate('page')?>
                        </a>
                    <?php endif;?>
                </div>
            </div>
            <div class="box">
                <div class="main">
                    <div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
                        <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
                            <h3><?php echo $this->translate($this->title); ?></h3>
                        </div>
                        <div class="ui-dialog-content ui-widget-content content">
                             <?php echo $this->layout()->content?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="ft">
            <a href="http://www.preceptoread.com.br">
                <img border="0" src="img/logo.png" alt="Logo Preceptor" />
            </a>
        </div>
    </body>
</html>
