<div class="box">
    <div class="main index">
        <div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
            <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
                <h3><?php echo $this->translate($this->title); ?></h3>
                <a href="#" class="ui-dialog-titlebar-close ui-corner-all">
                    <span class="ui-icon ui-icon-closethick">close</span>
                </a>
            </div>
            <div class="ui-dialog-content ui-widget-content content">
                 <?php echo $this->layout()->content?>
            </div>
        </div>
    </div>
</div>