<?php echo $this->doctype(); ?>
<?php $locale = str_replace('_', '-', $this->locale)?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $this->locale?>" xml:lang="en">
	<head>
		<title>Trilhas - Preceptor Educação a Distância</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <base href="<?php echo $this->serverUrl() . $this->baseUrl() ?>/" />
        <link rel="shortcut icon" href="favicon.ico" />

        <?=$this->headLink()->appendStylesheet('js/editor/stylesheets/xq_ui.css')
							->appendStylesheet('js/editor/stylesheets/xq_contents.css')
							->appendStylesheet('css/themes/'.$this->theme.'/jquery-ui.css')
							->appendStylesheet('css/themes/'.$this->theme.'/main.css')
							->appendStylesheet('css/navigation.css')
							->appendStylesheet('css/utils.css'); ?>
                            
		<?=$this->headScript()->appendFile('js/jquery/jquery.min.js')
							  ->appendFile('js/jquery/jquery-ui.min.js')
							  ->appendFile('js/jquery/jquery.other.js')
							  ->appendFile('js/jquery/ui/i18n/ui.datepicker-'.$locale.'.js')
                              ->appendFile('js/editor/all.js')
							  ->appendFile('js/editor/plugin/FileGalleryPlugin.js')
							  ->appendFile('js/editor/plugin/CustomStylePlugin.js')
							  ->appendFile('js/editor/plugin/EditorResizePlugin.js')
							  ->appendFile('js/editor/plugin/FlashMovieMacroPlugin.js')
							  ->appendFile('js/editor/plugin/LinkToImagePlugin.js')
							  ->appendFile('js/editor/plugin/ContextoPlugin.js')
							  ->appendFile('js/chat.js')
							  ->appendFile('js/relation.js')
							  ->appendFile('js/action.js')
							  ->appendFile('js/string.js')
							  ->appendFile('js/run.js')
							  ->appendFile('js/navigation.js'); ?>
	</head>
    <body>
        <div id="hd">
            <h1>Trilhas</h1>
            <img src="css/themes/<?=$this->theme?>/images/logo.png" alt="Logo Trilhas" />
            <?php if(Zend_Auth::getInstance()->hasIdentity()):?>
                <span style="margin-right: 5px;">Olá, [username]</span> |
                <?php if(count($this->groups) > 2): ?>
                    <?php echo $this->formSelect("group_id", $this->user->group_id, array( "class" => "select_profile", "style" => "margin-left: 6px; margin-right: 6px; height: 18px;") , $this->groups);?> |
                <?php endif ?>
                <a href="user/logout"><?php echo $this->translate("logout");?></a>&nbsp;
            <?php endif; ?>
        </div>
        <div id="bd">
            <div class="message">
                <?php if ($this->messages):?>
                    <?php foreach($this->messages as $message):?>
                        <p><?php echo $message?></p>
                    <?php endforeach;?>
                <?php endif;?>
            </div>
            <?=$this->layout()->content?>
        </div>
        <div id="ft">
            <a href="http://www.preceptoread.com.br">
                <img src="img/logo.png" alt="Logo Preceptor" />
            </a>
        </div>
        <script type="text/javascript">
            
        </script>
    </body>
</html>