<div>
	<?php
		echo $this->element()->startForm()
							 ->formHidden( "id" , null , array( "printLabel" => false ) )
							 ->formHidden( "folder_id" , $this->data->folder_id , array( "printLabel" => false ) )
	  						 ->formText( "title" );        
	?>  
	
	                     	 
	<input type="checkbox" name="data[File_Model_Folder][visibility]" value="<?=$this->visible?>" id="visibility_<?=$this->suffix?>" <?=($this->data->visibility == 'P' )?("checked='checked'"):"";?> />
	<label for="visibility_<?=$this->suffix?>" class="inline"><?=$this->translate( "visible to all?")?></label>
	
	<?php
	  	echo $this->element()->formSubmit( "save" , $this->translate("save") , array( "printLabel" => false ) )
	                       	 ->endForm();
	?>                                 
</div>
<script>
	file_model_folder.success = function(){
        new Preceptor.util.AjaxUpdate( 'file-file' , '<?=$this->url?>/file/folder/save/' , { formId:"File_Model_File" } );
    }
</script>