<table cellspacing="0" cellpadding="0" width="100%">
	<tr>
		<td height="22" width="22" background="<?=URL;?>/img/layout/bg/bg_tabela_cima_esq.png">&nbsp;</td>
		<td bgcolor="white">&nbsp;</td>
		<td height="22" background="<?=URL;?>/img/layout/bg/bg_tabela_cima_dir.png">
			<a href="remove/<?php echo $this->controller; ?>" onclick="removeElement( '<?php echo $this->controller; ?>' ); return false;" >x</a>
		</td>
	</tr>
	<tr id="mainErro">
		<td bgcolor="white">&nbsp;</td>
		<td bgcolor="white" id="innerErro">
			<p><?php echo $this->exception; ?></p>
		</td>
		<td background="<?=URL;?>/img/layout/bg/bg_tabela_dir.png">&nbsp;</td>
	</tr>
	<tr id="footerErro">
		<td height="22" background="<?=URL;?>/img/layout/bg/bg_tabela_baixo_esq.png">&nbsp;</td>
		<td background="<?=URL;?>/img/layout/bg/bg_tabela_baixo.png">&nbsp;</td>
		<td height="22" width="22" background="<?=URL;?>/img/layout/bg/bg_tabela_baixo_dir.png">&nbsp;</td>
	</tr>
</table>
			