<div class="left menu-index">
    <div id="indetification" class="box">
        <div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
            <div class="ui-dialog-content ui-widget-content">
                <?php if( Zend_Auth::getInstance()->hasIdentity() ): ?>
                <div style="text-align: center; height: 120px; overflow: hidden;">
                        <?php if( $this->user->image ):?>
                    <img src="<?=$this->url?>/file/file/download/read/true/file/<?=base64_encode("thumb_medium{$this->user->image}")?>" />
                        <?php else:?>
                    <img src="<?=$this->url?>/file/file/download/read/true/file/<?=base64_encode("thumb_mediumfoto.jpg")?>" />
                        <?php endif;?>
                </div>
                <?php else: ?>
                <div>
                    <form id="frmLogin" method="post" style="padding: 0; margin: 0;" action="<?=$this->url?>/user/login">

                        <label>E-mail:</label>
                        <input name="username" tabindex="1" id="usuario" type="text" maxlength="255" style="width: 87%" />

                        <label>Senha:</label>
                        <input name="password" id="senha" type="password" tabindex="2" maxlength="255" size="32" style="width: 87%"  />

                        <br /><br />

                        <input type="submit" value="Entrar" tabindex="3" />
                    </form>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="button">
        <?if( Zend_Auth::getInstance()->hasIdentity() ):?>
                    <!--<a href="<?=$this->url?>/person/input" class="ui-state-default ui-corner-all">
        <span class="ui-icon ui-icon-gear"></span>
            <?=$this->translate('manage')?>
    </a>-->
        <a id="my-data" href="<?=$this->url?>/person/input" class="ui-state-default ui-corner-all">
            <span class="ui-icon ui-icon-person"></span>
                <?=$this->translate("data")?>
        </a>
        <a href="#this" id="my-courses" class="ui-state-default ui-corner-all">
            <span class="ui-icon ui-icon-folder-open"></span>
                <?=$this->translate('my courses')?>
        </a>
        <a href="#this" id="all-courses" class="ui-state-default ui-corner-all">
            <span class="ui-icon ui-icon-folder-open"></span>
                <?=$this->translate('all courses')?>
        </a>
        <script type="text/javascript">
            $( "#all-courses" ).click( function(){
                new Preceptor.util.AjaxUpdate( "default-course" , "<?=$this->url?>/course/index/list/true" );
            });

            $( "#my-data" ).click( function(){
                new Preceptor.util.AjaxUpdate( "default-course" , this.href );
                return false;
            });

            $( "#my-courses" ).click( function(){
                new Preceptor.util.AjaxUpdate( "default-course" , "<?=$this->url?>/course/my-course" );
            });
        </script>
        <?endif;?>
    </div>
    <div class="banner">
    </div>
</div>

<div class="main-index">
    <div id="calendar-calendar" class="calendar"></div>
    <div id="default-course"></div>
</div>
<script>
    $(document).ready(function(){
        new Preceptor.util.AjaxUpdate( "default-course" , "course" );

        <?if( Zend_Auth::getInstance()->hasIdentity() ):?>
            $('#default-course').addClass('course');
            new Preceptor.util.AjaxUpdate( "calendar-calendar" 	, "calendar/calendar/index" );
        <?endif;?>
    });
</script>