<?php if( isset( $this->data ) ): ?>
    <?=$this->formHidden( "data[Station_Model_Address][cep_log_logradouro_log_nu]" , $this->data->log_nu , array( "id" => "Station_Model_Address-cep_log_logradouro_log_nu" ) )?>

    <label for="Station_Model_Address-address_end"><?=$this->translate( 'address' )?>:</label>
    <?=$this->formText( "data[Station_Model_Address][address_end]" , $this->data->log_no , array( "id" => "Station_Model_Address-address_end" , "class" => "input-medium" , "disabled" => "disabled" ) )?>

    <label for="Station_Model_Address-complement"><?=$this->translate( 'complement' )?>:</label>
    <?=$this->formText( "data[Station_Model_Address][complement]" , $this->data->log_complemento , array( "id" => "Station_Model_Address-complement" , "class" => "input-medium" ) )?>

    <label for="Station_Model_Address-address_city"><?=$this->translate( 'city' )?>:</label>
    <?=$this->formText( "data[Station_Model_Address][address_city]" , $this->data->loc_no , array( "id" => "Station_Model_Address-address_city" , "class" => "input-medium" , "disabled" => "disabled" ) )?>

    <label for="Station_Model_Address-address_neighborhood"><?=$this->translate( 'city' )?>:</label>
    <?=$this->formText( "data[Station_Model_Address][address_neighborhood]" , $this->data->bai_no , array( "id" => "Station_Model_Address-address_neighborhood" , "class" => "input-medium" , "disabled" => "disabled" ) )?>
    
     <script type="text/javascript">
        share_model_person.add('Station_Model_Address-complement' , Validate.notEmpty , 'Preenchimento obrigatório');
     </script>
<?php else:?>
    <span style='color: red;'><?=$this->translate( "zip not found" )?></span><br /><br />
<?php endif?>

