<div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
    <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
        <h3><?php echo $this->translate('Course');?></h3>
    </div>
    <div class="ui-dialog-content ui-widget-content">
        <?php echo $this->form?>
    </div>
</div>
<script type="text/javascript">
    $('#category, #status').other();
</script>