<?php $locale = strtolower(str_replace('_', '-', $this->locale))?>
<div class="right">
    <?=$this->ajax("back", 'course', 2); ?>
</div>
<?php echo $this->form ?>
<script type="text/javascript">
    var $page = $('#course-description-text'),
        config = {
            toolbar: [
                ['Source','-','Preview','Templates'],
                ['Cut','Copy','Paste','PasteText','PasteFromWord'],
                ['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],
                '/',
                ['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
                ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote','CreateDiv'],
                ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
                ['Link','Unlink','Anchor'],
                ['Image','Flash','Table','HorizontalRule','SpecialChar'],
                '/',
                ['Styles','Format','Font','FontSize'],
                ['TextColor','BGColor'],
                ['Maximize', 'ShowBlocks','-','About']
            ],language: '<?php echo $locale?>'
        }, editor = CKEDITOR.appendTo('description-element', config, $page.val());
    $page.hide();

    $("form").submit(function() {
        var $this = $(this);
        $page.val(editor.getData());
	});

    $('#category').other();

    $('input[type=button], input[type=submit]').button();
</script>