<div class="right">
	<input type="button" id="manager_discipline" value="<?=$this->translate("managing disciplines")?>" />	
</div>

<form action="#" id="formCourse">
	<?=$this->formHidden( "id" , $this->data->id , array( "id" => "id_{$this->suffix}" ) );?>

	<label for="title_<?$this->suffix?>"><?=$this->translate( "title" )?>:</label>
	<?=$this->formText( "title" , $this->data->title , array( "id" => "title_{$this->suffix}" , "class" => "input-medium" ) );?>
	
	<br /><br />
	<div id="groupList">
		<?=$this->groupedList( "discipline_all" , $this->all , "discipline_id" , $this->selected );?>
	</div>
	
	<label for="title_<?$this->suffix?>"><?=$this->translate( "minimum average for approval" )?>:</label>
	<?=$this->formText( "average" , number_format( $this->data->average , 2 , "," , ".") , array( "id" => "average_{$this->suffix}" , "class" => "input-medium" ) );?>
	
	<br /><br />
	
    <label for="status_<?=$this->suffix?>"><?=$this->translate( "status" )?>:</label>
    <?=$this->formSelect( "status" , $this->data->status , array( "id" => "status_{$this->suffix}" ) , $this->status );?>

	<br /><br />
	
	<?=$this->formSubmit( "submitGroup" , $this->translate( "save" ) );?>
</form>
		
<script>
	YAHOO.util.Event.on( 'formCourse' , 'submit' , function( ev ){
		GroupedList_course_discipline_all.selectAll( 'discipline_id' );
		
		var response = new Preceptor.util.AjaxUpdate( 'course' , '<?=$this->url?>/course/save' , {formId:"formCourse"} );
			
		YAHOO.util.Event.stopEvent( ev );	
	});
	
	YAHOO.util.Event.on( "manager_discipline" , "click" , function(ev){
		var div = Lightbox.create();
		div.style.border = 'solid 1px black';
			
		new Preceptor.util.AjaxUpdate( 'category' , "<?=$this->url?>/discipline/list/courseId/<?=$this->data->id?>" );
		window.location = '#category';
	});
</script>