    <?php if( isset( $this->user->courseIntention ) ):?>
        <script type="text/javascript">
            new Preceptor.util.AjaxUpdate( "default-course" , "<?=$this->url?>/discipline/register-confirm/discipline_id/<?=$this->user->courseIntention?>" )
        </script>
        <?php unset( $this->user->courseIntention )?>
    <?php endif?>
    <?php if( $this->rs->count() ): ?>
		<?php foreach( $this->rs as $rs ):?>

            <h3><?=$this->escape( $rs->name )?></h3>
			<?php $disciplines = $rs->findManyToManyRowset( "Station_Model_Discipline" ,
															"Station_Model_CourseDiscipline" ,
															null ,
															null ,
															$rs->getTable()->select()
																		   ->where( "id IN( {$this->discipline_id} )" )
																		   ->order( 'name' ) ) ?>
			<?php if( $disciplines->count() ): ?>
				<table id="course-list" width="100%">
					<?php foreach( $disciplines as $discipline ): ?>
						<tr class="<?=$this->changeClass( $disciplines->key() , array( 'one' , 'two' ) )?>">
							<td width="50%"><span style="font-size: 1.1em"><?=$this->escape( $discipline->name )?></span></td>
                            <?if( Zend_Auth::getInstance()->hasIdentity() ):?>
                                <?php
                                    if( 
                                        ( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::INSTITUTION ) ||
                                        ( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::SPECIALIST ) ||
                                        ( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::TEACHER ) )
                                    {
                                        $groups = $discipline->findDependentRowSet( "Station_Model_ClassModel");
                                    }else{
                                        $select = $discipline->getTable()->select()->where( 'id IN('.$this->user->group->all.')' );
                                        $groups = $discipline->findDependentRowSet( "Station_Model_ClassModel" , null , $select );
                                    }
								?>
                                <td width="38%">
                                    <?php if( $groups->count() > 1 ): ?>
                                        <select onchange="window.location = '<?=$this->url?>/discipline/index/id/<?=$rs->id?>/discipline_id/<?=$discipline->id?>/group_id/' + this.value">
                                            <option value=""><?=$this->translate("select")?> ...</option>
                                            <?php foreach( $groups as $group ): ?>
                                                <option value="<?=$group->id?>">
                                                    <?=$this->escape( $group->name )?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    <?php else: ?>
                                        <?php
                                            if(
                                                ( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::INSTITUTION ) ||
                                                ( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::SPECIALIST ) ||
                                                ( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::TEACHER ) )
                                            {
                                                $group  = $groups->current();
                                            }else{
                                                $group  = $groups->current();
                                                $select =  $group->getTable()->select()->where( 'person_id IN('.$this->user->person_id.')' );
                                                $status = $group->findStation_Model_ClassModelViaStation_Model_ClassPerson( $select )->current()->status;
                                            }
                                        ?>

                                        <?php if( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::STUDENT ):?>
                                            <?php if( $status == Station_Model_Status::WAITING ):?>
                                                <?=$this->ajax( $this->translate( "payment waiting" ) , "default-course" , "$this->url/discipline/payment/class_id/$group->id" , 2 , null )?>
                                                <?=$this->ajax( $this->translate( "cancel" ) , "default-course" , "$this->url/person/register-class-cancel/id/$group->id" , 2 , null )?>
                                            <?php else:?>
                                                <?php if( $status == Station_Model_Status::STUDYING ):?>
                                                    <?php if( ( date( "Y-m-d" ) >= $group->initially ) &&
                                                        ( ( isset( $group->finish )  && date( "Y-m-d" ) <= $group->finish ) || !$group->finish ) ):?>
                                                        <a href="<?=$this->url?>/discipline/index/id/<?=$rs->id?>/discipline_id/<?=$discipline->id?>/group_id/<?=$group->id?>" title="<?=$this->translate( "access" )?>">
                                                            <img src="<?=$this->url?>/img/icons/application_go.png" /> <?=$this->translate( "course access" )?>
                                                        </a>
                                                    <?php else: ?>
                                                        <?php if( date( "Y-m-d" ) <= $group->initially ):?>
                                                            <div class="message-table-sorter"><?=$this->translate( "date for start of the course" ) ?> - <?=$this->date( $group->initially )?></div>
                                                        <?php else: ?>
                                                            <div class="message-table-sorter"><?=$this->translate( "course completed" ) ?> - <?=$this->date( $group->finish )?></div>
                                                        <?php endif;?>

                                                    <?php endif;?>
                                                <?php endif;?>
                                            <?php endif;?>
                                        <?php else: ?>
                                            <?php if( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::INSTITUTION || $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::SPECIALIST ):?>
                                                <a href="<?=$this->url?>/discipline/index/id/<?=$rs->id?>/discipline_id/<?=$discipline->id?>/group_id/<?=$group->id?>">
                                                    <img src="<?=$this->url?>/img/icons/application_go.png" />
                                                </a>
                                            <?php else: ?>
                                                <?php if( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::TEACHER ):?>
                                                    <a href="<?=$this->url?>/discipline/index/id/<?=$rs->id?>/discipline_id/<?=$discipline->id?>/group_id/<?=$group->id?>">
                                                        <img src="<?=$this->url?>/img/icons/application_go.png" />
                                                    </a>
                                                <?php endif?>
                                            <?php endif?>
                                        <?php endif?>
                                    <?php endif; ?>
                                </td>
                            <?php endif; ?>
							<?php
//								$print = null;
//								foreach ( $groups as $group_certificate ){
//									$certificate = $group_certificate->findDependentRowset( "Certificate" )->current();
//									if ( ( $certificate ) && ( $this->role_id == Role::STUDENT ) ){
//										$person_certificate = $certificate->findDependentRowset( "CertificatePerson" , null , $certificate->getTable()->select()->where( "person_id =?" , $this->person_id ) );
//                                        if( $person_certificate->count() )
//											$print = "<a href='{$this->url}/certificate/certificate/print/group_id/{$group_certificate->id}' name='".$this->translate("print certificate")."' target='_blank'>".$this->image('icones/certificate.gif')."</a>";
//									}
//								}
							?>
							<td><?//=$print?></td>
                            <?php if( ( $this->user->roles[SYSTEM_ID]['current'] == Share_Model_Role::STUDENT ) && ( date( "d-m-Y" ) >= $this->date( $group->initially ) ) &&
                                    ( ( isset( $group->finish )  && date( "d-m-Y" ) <= $this->date( $group->finish ) ) || !$group->finish ) ):?>
							<td width="12%">
								<?php
									$content	   = new Content_Model_Content();
									$contentAccess = new Content_Model_ContentAccess();

									$count = $contentAccess->countByPerson( $discipline->id );
									$countDiscipline = $content->count( array( "discipline_id = ?" => $discipline->id ,
																			   "NOT ds IS NULL" => "" ) );

									@$total = ceil( ( 100 * $count ) /  $countDiscipline );
									if( $total > 100 ) $total = 100;
								?>

								<?php if( $total ): ?>
									<div style='width:100px; border: 1px solid #407DA9; overflow:hidden'><p style='padding:0; margin: 0; text-align: center; width: <?=$total?>px; background: #1B4D6F; color: white;'><?=$total?>%</p></div>
								<?php endif;?>
							</td>
                            <?php else:?>
                            <td>
                            </td>
                            <?php endif;?>
						</tr>
					<?php endforeach; ?>
				</table>
			<?php endif; ?>
            <br />
	<?php endforeach; ?>
<?php else: ?>
	<div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif; ?>