<div class="right">
	<?php if( $this->getPermission( "input" ) ): ?>
		<?=$this->ajax( $this->translate("new") , "category-category" , $this->url . "/category/category/input" , 2 ) ?>
	<?php endif; ?>
</div>
<div class="clear"></div>
<br />

<?php if( $this->rs->count() ):?>
	<table class="tablesorter">
        <thead>
            <tr>
                <th><?=$this->translate("name")?></th>

                <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                    <th width="77px"></th>
                <?php endif;?>
            </tr>
        </thead>

        <tbody>
            <?php foreach( $this->rs as $rs ): ?>
                <?php if( $this->getPermission( "input" ) ): ?>
                    <?php $edit = $this->ajax( $this->translate("edit") , 'category-category' , $this->url . '/category/category/input/id/' . $rs->id ); ?>
                <?php endif;?>

                <?php if( $this->getPermission( "delete" ) ): ?>
                    <?php $delete = $this->ajax( $this->translate("delete") , 'category-category' , $this->url . "/category/category/delete/id/$rs->id/type/$this->type" , 1 , $this->translate("want to delete?") );?>
                <?php endif;?>

                <tr class="<?=$this->changeClass( $this->rs->key() , array( "even" , "odd" ) )?>">
                    <td nowrap="nowrap"><?=$rs->name?></td>
                    <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                        <td nowrap="nowrap"><?=$edit . " " . $delete?></td>
                    <?php endif;?>
                </tr>
            <?php endforeach;?>
        </tbody>
	</table>
<?php else:?>
	<div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif;?>