<?=$this->element()->startForm();?>
<div id="edit">
    <div class="yui-skin-sam" id="div-form-<?=$this->model?>">

        <?php
            echo $this->element()->formHidden( "id" , $this->data->id , array( "printLabel" => false , "model" => "Category_Model_Category" ) )
                      ->formHidden( "type" , $this->type , array( "printLabel" => false , "model" => "Category_Model_Category" ) )
                      ->formText( "name" , $this->data->name , array( "model" => "Category_Model_Category" ) );
        ?>
    <br />
        <?php
            echo $this->element()->formSubmit( "model" , $this->translate("save") , array( "printLabel" => false ) );
        ?>
    </div>
    <div class="clear"></div>
    <?=$this->formRelation( $this->data->id , array( 'url' => "category/category/save" ) )?>
</div>
