<div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
	<div id="calendar-render"></div>
    
	<div class="calendar-list">
		<?php if( count( $this->rs ) ): ?>
			<table cellpadding="10" width="100%">
                
				<?php foreach ( $this->rs as $rs ): ?>
					<?php $class   = $this->changeClass( $this->rs->key() , array( "light_gray" , "gray" ) );?>
					<?php $edit = $delete = "" ?>
					<?php $rowspan = 2;?>
					
					<?php if ( $rs->person_id == $this->user->person_id || $this->user->roles[SYSTEM_ID]['current'] == 6 ): ?>
						<?php $edit   = $this->ajax( $this->translate( "edit" ) , "calendar-calendar" , "calendar/calendar/input/id/" . $rs->id .  "/date/" . $this->date )?>
						<?php $delete = $this->ajax( $this->translate( "delete" ) , "calendar-calendar" , "calendar/calendar/delete/id/" . $rs->id , 1 , $this->translate("want to delete?") )?>
					<?php endif; ?>

					<?php $person = $rs->findParentRow( "Share_Model_Person" ) ?>
					<tr class="<?=$class?>">
						<td align="center">
							<?=$this->date( $rs->started , 'd' )?><br />
							<?=$this->translate( $this->date( $rs->started , 'M' ) );?>
						</td>
						<td>
							<?=nl2br( $this->escape( $rs->ds ) )?>
							<p class="calendar-by"><strong><?=$this->shortName( $person->name )?></strong></p>
						</td>
						<td><?=$edit?><p><?=$delete?></p></td>
					</tr>
				<?php endforeach;?>
			</table>
		<?php else: ?>
			<p><?=$this->translate("there are no records")?></p>
			<div class="clear">&nbsp;</div>
		<?php endif; ?>
		<div>
            <?if( $this->getPermission( "input" ) ):?>
                <?=$this->ajax( $this->translate( "new" ) , "calendar-calendar" , "calendar/calendar/input/date/" . $this->date , 2 )?>
            <?endif?>
		</div>
	</div>

	<div class="clear"></div>

	<form id="findCalendar" action="#">
		<input type="hidden" name="date" id="dateCalendar" />
	</form>
</div>
<script type="text/javascript">
	$("#calendar-render").datepicker({
		onSelect: function(dateText) {
			new Preceptor.util.AjaxUpdate( "calendar-calendar" , "calendar/calendar/find/date/" + dateText );
		},
		dateFormat: 'yy-mm-dd'
	});
</script>
