<div class="yui-skin-sam">
	<?=$this->element()->startForm();?>
	<div id="notepad_text">
        <?php
            echo $this->element()->formHidden( "id" , null , array( "printLabel" => false ) )
                      ->formTextarea( "ds" , null )
                      ->formSubmit( "model" , $this->translate("save") , array( "printLabel" => false ) );
        ?>
        <div class="clear">&nbsp;</div>
	</div>
    <?=$this->element()->endForm();?>
</div>
<div>
	<?php if( $this->rs->count() ):?>
		<table class="tablesorter">
            <thead>
                <tr>
                    <th><?=$this->translate("type")?></th>
                    <th><?=$this->translate("discipline")?></th>
                    <th><?=$this->translate("description")?></th>
                    <th><?=$this->translate("date")?></th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
			<?php foreach( $this->rs as $key => $rs ): ?>
				<?php $class  = $this->changeClass( $key , array( "even" , "odd" ) );?>
				<?php if ( $this->person_id == $rs->person_id ) : ?>
					<?php $edit   = $this->ajax( $this->translate("edit") , 'notepad-notepad' , $this->url . '/notepad/notepad/index/id/'. $rs->id ); ?>
					<?php $delete = $this->ajax( $this->translate("delete") , 'notepad-notepad' , $this->url . '/notepad/notepad/delete/id/' . $rs->id , 1 , $this->translate("want to delete?") );?>
				<?php endif; ?>
				<tr class="<?=$class?>">
					<td><?=$this->status( $rs->type , array( "A" => $this->translate("annotation") , "R" => $this->translate("abstract") ) )?></td>
					<td><?=$rs->findParentRow('Station_Model_Discipline')->name?></td>
					<td>
						<?php if( $rs->content_id ): ?>
							<strong><?=$rs->findParentRow( "Content_Model_Content" )->title ?></strong> -
						<?php endif; ?>
						<?=$rs->ds?>
					</td>
                    <td><?=$this->date( $rs->created )?></td>
					<td nowrap="nowrap"><?=$edit ." &nbsp; ". $delete?></td>
				</tr>
				<?php if( $key == 5 ) break; ?>
			<?php endforeach; ?>
            </tbody>
		</table>
	<?php else : ?>
		<div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
	<?php endif;?>
</div>
<br />
<script type="text/javascript">

	$("#notepad-render").datepicker({
		onSelect: function(dateText) {
			new Preceptor.util.AjaxUpdate( 'notepad' , '<?=$this->url?>/notepad/notepad/find/date/' + dateText );
		},
		dateFormat: 'yy-mm-dd'
	});
    
	var Editor_Notepad = new Preceptor.widget.Editor( "<?=$this->model?>-ds" , { addButton:['uploadImage' , 'insertHtml'] , height:'100px' , noAutoHeight: true } );

    $("#<?=$this->model?>-model").click(function(){
        Editor_Notepad.saveHTML();
    });

    notepad_model_notepad.success = function(){
		new Preceptor.util.AjaxUpdate( 'notepad-notepad' , '<?=$this->url?>/notepad/notepad/save' , { formId:"Notepad_Model_Notepad" } );
	}

</script>
