<div id="menu" class="ui-accordion ui-widget ui-helper-reset">
        <?php $menu = Zend_Registry::get('menu');?>
        <?php $i = 0; $previousParentName = null;?>
		<?php foreach ($menu as $parentName => $childs): ?>
                <?php foreach($childs as $name => $data): ?>
                    <?php if ($this->isAllowed($data)): ?>
                        <?php if ($parentName != $previousParentName):?>
                            <?php if($i > 0): ?>
                                    </div>
                                </ul>
                            <?php endif;?>
                                 <h3 class="ui-accordion-header ui-helper-reset ui-state-active ui-corner-top"><?=$this->translate($parentName)?></h3>
                                 <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom ui-accordion-content-active">
                                <ul>
                        <?php endif;?>
                        <li>
                            <a href="#this" onclick="addElement('main', '<?=$data['controller']?>' , '<?=$this->url?>/<?=$data['module']?>/<?=$data['controller']?>/<?=$data['action']?>' )"  >
                                <?=$this->translate($name)?>
                            </a>
                        </li>
                    <?php endif; ?>
                    <?php $previousParentName = $parentName; $i++;?>
                <?php endforeach; ?>
		<?php endforeach; ?>
            </div>
        </ul>
</div>