<div class="ui-state-highlight ui-corner-all message">
    <span class="ui-icon ui-icon-info"></span>
    <ul>
        <?php foreach ($this->messages as $message): ?>
            <li><?php echo $this->translate($message)?></li>
        <?php endforeach; ?>
    </ul>
</div>
<script type="text/javascript">
    clearTimeout(mTime);
    var mTime = setTimeout(function(){
        $('.message').animate({"height": "toggle", "opacity": "toggle"}, 'slow');
    }, 5000);
</script>
