<div id="content-content" class="ui-dialog ui-widget ui-widget-content ui-corner-all">
	<div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
		<span class="ui-dialog-title" id="ui-dialog-title-dialog">
			<h3><?=$this->translate( $this->controller );?></h3>
		</span>

		<?php if( $this->narration ): ?>
			<a href="#" class="content-icon content-volume">
				<span class="ui-icon ui-icon-volume-on">volume</span>
			</a>
		<?php endif; ?>

		<?php if( $this->getPermission( array( "module" => "content" , "controller" => "composer", "action" => "input" ) ) ): ?>
			<a href="#" class="content-icon content-edit">
				<span class="ui-icon ui-icon-pencil">edit</span>
			</a>
		<?php endif ?>

		<a href="#" class="content-icon content-print">
			<span class="ui-icon ui-icon-print">print</span>
		</a>
	</div>
	<div class="ui-dialog-content ui-widget-content">
		<div>
			<?php if( $this->narration ): ?>
				<div id="mp3player" class="pos-absolute mp3player" style="display: none;">
					<object width="220" height="30" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0 ">
						<param name="movie" value="<?=$this->url?>/swf/player_custom/mp3player.swf?src=<?=$this->url?>/upload/narration/<?=$this->narration;?>" />
						<embed src="<?=$this->url?>/swf/player_custom/mp3player.swf?src=<?=$this->url?>/upload/narration/<?=$this->narration;?>" type="application/x-shockwave-flash" width="220" height="30" />
					</object>
				</div>
			<?php endif; ?>

			<div id="content-main">
				<div class="nav">
					<div class="bread">
						<img src="<?=$this->url?>/img/icons/treeview.gif" />
						<div class="treeview"></div>
						<span></span>
					</div>
					<div class="buttons">
						<a href="#this"><?=$this->translate('previous')?></a> | 
						<a href="#this"><?=$this->translate('next content')?></a>
					</div>
					<div class="clear zero"></div>
				</div>
				<div id="content-main-content" class="content">
					
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$('#content-main').navigation('<?=$this->contents?>',
                                  {baseUrl:'<?=$this->url?>',
                                   url:'/content/content/view/id/'});
	
	$(".content-edit").click(function(){
		$('.cache').empty();
		layout.addPanel( 'content-composer' , '<?=$this->url?>/content/composer/index/id/' + $(window).data('current_id') );
        return false;
	});

	$(".content-print").click(function(){
		printModule('content-content');
        return false;
	});

	$(".content-volume").click(function(){
		$('#mp3player').toggle();
        return false;
	});
	
	window.words = YAHOO.lang.JSON.parse( '<?=$this->words?>' );
</script>
