<h4><?//=$this->rs->title;?></h4>
<p><?=$this->rs->ds;?></p>
<p><?=$this->restriction?></p>
<?php if( count( $this->narration ) ): ?>
	<!-- 
		division into three columns
		
		1. the first column comment on the narration
		2. the second column player
		3. the third column download		
	-->
	<div class="filter back-transparent border-black">
		
		<div class="left" style="padding-right: 7px;">
		
		</div>

		<div class="left" style="padding-right: 7px;">
			<object width="220" height="30" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0 ">
		    	<param name="movie" value="<?=$this->url?>/swf/player_custom/mp3player.swf?src=<?=$this->url?>/upload/narration/<?=$location = $this->narration->findParentRow( "File" )->location;?>" />
		    	<embed src="<?=$this->url?>/swf/player_custom/mp3player.swf?src=<?=$this->url?>/upload/narration/<?=$location?>" type="application/x-shockwave-flash" width="220" height="30" />
			</object>
		</div>
		
		<?php if( $this->getPermission( array( "module" => "file" , "controller" => "file" , "action" => "download" ) ) ): ?>
			<div>
				<a target="_blank" href="<?=$this->url?>/file/file/download/file/<?=base64_encode( "upload/narration/" . $this->narration->findParentRow( "File" )->location ); ?>"><strong><?=$this->translate( "download" ); ?></strong></a>
			</div>
		<?php endif; ?>
		
		<div class="clear"></div>
	</div>
<?php endif; ?>
<!--
<?php if( count($this->childs) ): ?>
    <div>
        <ul>
        <?php foreach( $this->childs as $child ): ?>
            <li><a href="#this" onclick="new Preceptor.util.AjaxUpdate( 'content-main-content' , '<?=$this->url?>/content/view/id/<?=$child->id?>', { evalScripts:true } ); document.getElementById( 'content-main-content' ).focus(); return false;"><?=$child->title?></a></li>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

-->
<script>
	YAHOO.util.Event.onDOMReady( function(){
		var content = $('content-main-content').innerHTML, i, lower;
		
		for ( i = 0 ; i < words.length; i++ ){
			if( content.indexOf( words[i]['word'] + " " ) > -1 ){
                content = content.replace( " " + words[i]['word'] + " " , ' <a href="#this" style="border-bottom: 1px dotted; text-decoration: none;" onclick="addElement(\'main\' , \'glossary\' , \'<?=$this->url?>/glossary/glossary/index/q/'+ words[i]['encode'] + ' \' )">' + words[i]['word'] + '</a> ' );
			}else if( content.indexOf( " " + words[i]['word'].toLowerCase() + " " ) > -1 ){
				lower = words[i]['word'].toLowerCase();
                content = content.replace( " " + lower + " "  , ' <a href="#this" style="border-bottom: 1px dotted; text-decoration: none;" onclick="addElement(\'main\' , \'glossary\' , \'<?=$this->url?>/glossary/glossary/index/q/'+ words[i]['encode'] + ' \' )">' + lower + '</a> ' );
			}
		}

        content = content.replace( /\/www17dsv\//gi , '/<?php echo $_SERVER['HTTP_HOST']?>/' );
        content = content.replace( /\/www17\//gi , '/<?php echo $_SERVER['HTTP_HOST']?>/' );

		$('content-main-content').innerHTML = content;
	});
</script>