<div>
	<?php if( $this->sessionUser == $this->user->usuario_id ) : ?>
		<div style="text-align: right;">
			<?php echo $this->ajax( $this->translate( "edit" ) , "page" , "page/page/input/id/" . $this->user->usuario_id , 2 ); ?>
		</div>
	<?php endif; ?>
	<div id="contentPage">
	
		<img src="<?=URL?>upload/thumb_medium<?php echo $this->user->findParentRow('File')->arquivo_caminho; ?>" />
		
		<div>
			<h3><?php echo $this->user->usuario_nome; ?></h3>
				
			<p><b><?=$this->translate( "email" )?>:</b>&nbsp;<a href="mailto:<?php echo $this->user->usuario_email; ?>" title="<?php echo $this->user->usuario_email; ?>"><?php echo $this->user->usuario_email; ?></a></p>
			
			<div id="mensageUser">
				<a href="#message" onclick="addElement( 'meio' , 'message/message/index/id/<?php echo $this->user->usuario_id ?>' );"><?php echo LANG_SYSTEM_MESSAGE; ?></a>
				<?php  echo "(" . $this->countMessage . ")" ?>
			</div>
			<br />
			
		</div>
		
		<div style="clear: left;">&nbsp;</div>		
	</div>

	<div>

		<h3><?=$this->translate( "teacher" );?></h3>
		<hr />
		
		<?php if ( $this->teacher ) :?>
			<?php foreach( $this->teacher as $val1 ): ?>
				<div class="users">
					<a href="/page/index" onclick="new Preceptor.util.AjaxUpdate( 'page' , 'page/page/index/id/<?=$val1['usuario_id']?>' ); return false;">
						<div class="usersImg"><img src="<?=URL?>upload/thumb_small<?php echo $val1['arquivo_caminho']?>" /></div>
						<?=$val1['usuario_nome'];?>
					</a>
				</div>
			<?php endforeach; ?>
		<?php else: ?>
			<p><?=$this->translate( "don't have registers" )?></p>
		<?php endif; ?>

		<div style="clear: left;"></div>

		<h3><?=$this->translate( "friend" )?></h3>
		<hr />
		
		<?php if ( $this->friend ) :?>
			<?php foreach( $this->friend as $val2 ): ?>
				<div class="users">
					<a href="/page/index" onclick="new Preceptor.util.AjaxUpdate( 'page' , 'page/page/index/id/<?=$val2['usuario_id']?>' );return false;">
						<div class="usersImg"><img src="<?=URL?>upload/thumb_small<?=$val2['arquivo_caminho']?>" /></div>
						<?=$val2['usuario_nome'];?>
					</a>
				</div>
			<?php endforeach; ?>
		<?php else: ?>
			<p><?=$this->translate( "don't have registers" )?></p>
		<?php endif; ?>
		
		<div style="clear: left;">&nbsp;</div>
	</div>

</div>
