<?php if( $this->rs->count() ):?>
	<table class="tablesorter">
        <thead>
            <tr>
                <th><?=$this->translate("title")?></th>
                <th><?=$this->translate("url")?></th>
                <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                    <th width="77px"></th>
                <?php endif;?>
            </tr>
        </thead>

        <tbody>
            <?php foreach( $this->rs as $rs ):?>
                <?php if( $this->getPermission( "input" ) ): ?>
                    <?php $edit = $this->ajax( $this->translate("edit") , 'link-link' , $this->url . '/link/link/input/id/' . $rs->id );?>
                <?php endif;?>

                <?php if( $this->getPermission( "delete" ) ): ?>
                    <?php $delete = $this->ajax( $this->translate("delete") , 'link-link' , $this->url . '/link/link/delete/id/' . $rs->id . '/category_id/' . $this->category_id , 1 , $this->translate("want to delete?") );?>
                <?php endif;?>

                <tr class="<?=$this->changeClass( $this->rs->key() , array( "even" , "odd" ) )?>">
                    <td nowrap="nowrap"><?=$this->escape( $rs->title )?></td>
                    <td><a target="_blank" href="<?=$this->verifyProtocol( $rs->url )?>" ><?=$this->verifyProtocol( $rs->url )?></a></td>
                    <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                        <td nowrap="nowrap"><?=$edit . " " . $delete?></td>
                    <?php endif;?>
                </tr>
            <?php endforeach;?>
        </tbody>
	</table>
<?php else:?>
	<div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif;?>

<br />

<div class="right">
	<?php if( $this->limit < 999999 && count( $this->counts ) > 1 ): ?>
		<?=$this->ajax( $this->translate("all reply") , "forum" , $this->url . "/forum/forum/view/id/" . $this->forum_id . "/to/0/limit/999999" , 2 )?>
	<?php endif;?>
</div>	