<div class="right">
    <?php 
        if ($this->isAllowed('form')) {
           echo $this->ajax('new', 'exercise/question/form', 2);
        }
    ?>
</div>
<br /><br />
<?php if(count($this->data)):?>
	<table class="datatable">
		<tr>
			<th width="250"><?php echo $this->translate("Description")?></th>
            <th><?php echo $this->translate("Note")?></th>
            <th><?php echo $this->translate("Exercise")?></th>
			<?php if($this->isAllowed("form")): ?>
				<th></th>
			<?php endif;?>
		</tr>
		<?php foreach($this->data as $data):?>
			<tr>
                <td><?php echo $data->description?></td>
                <td><?php echo $data->note?></td>
                <td><?php echo $data->name ? $data->name : '---'?></td>
                <td>
                    <input class="add-question" type="button" value="<?php echo $this->translate('add')?>">&nbsp;
                    <input type="hidden" value="<?php echo $data->id?>">
                    <?php if($this->isAllowed("form")): ?>
                        <?php echo $this->ajax("edit", 'exercise/question/form/id/' . $data->id, 2);?>
                    <?php endif;?>
                </td>
			</tr>
		<?php endforeach;?>
	</table>
    <div id="question-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
<?php else:?>
	<?=$this->translate( "there are no records" );?>
<?php endif;?>
<script type="text/javascript">
    $('#question-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $('.add-question').click(function(){
        var $this = $(this),
            html = '<div class="question">'
                 + '<input type="button" value="<?php echo $this->translate('remove')?>" />&nbsp;\n'
                 + '<input type="hidden" value="' + $this.next().val() + '" />'
                 + $this.parent().prev().prev().prev().text();
                 + '</div>';
        $('#question-list h3').after(html);
        $('input[type=button], input[type=submit]').button();
    });

    $(".close").live("click", function(){
        $(this).parents('.box').remove();
        return false;
    });

    $('input[type=button], input[type=submit]').button();
</script>