<div class="right">
    <?php echo $this->ajax('back', 'glossary/index', 2) ?>
</div>
<div class="glossary">
<?php echo $this->form?>
</div>
<script type="text/javascript">
	$(".glossary form").submit(function() {
        var $this = $(this);
		$.post('glossary/index/save', $(this).serialize(), function(data){
            $this.parents('.content').html(data);
        });
        return false;
	});
    $('input[type=button], input[type=submit]').button();
</script>