<?php if( $this->getPermission( "input" ) ): ?>	
	<div class="right"><?=$this->ajax( $this->translate( "new" ) , 'activity' , '/activity/stage/input/' , 2 ); ?></div>
<?php endif; ?>
<?php if( $this->rs->count() ): ?>
	<ul class="bread">
		<?php foreach( $this->rs as $rs ): ?>
			<?php $arrow = "&raquo;"?>
			<a href="#this" onclick="Toogle.showOneHiddenAll( 'stage<?=$rs->id?>' )"><?=$rs->title?></a> <?=$arrow ?> 
			<script>Preceptor.util.elements.push( "stage<?=$rs->id?>" );</script>
			<?php if( ( $this->role == Role::STUDENT ) && ( ($this->rs->key() + 1) == $this->rs->count() ) && ( $this->getPermission( array( "module" => "activity" , "controller" => "text" , "action" => "input"  ) ) ) ): ?>
				<a href="#this" onclick='new Preceptor.util.AjaxUpdate( "text" , "<?=$this->url ?>/activity/text/input/" );' ><?=$this->translate("make")?></a>
			<?php endif; ?>
		<?php endforeach;?>
	</ul>
	
	<?php $this->rs->rewind(); ?>
	<?php foreach( $this->rs as $rs ): ?>
		<div id="stage<?=$rs->id?>" class="gray padding">
		
			<?php if( $this->user->type <= 5 ): ?>
				<div class="boxAdmin_button">
					<?php if( $this->getPermission( "input" ) ): ?>		
						<?=$this->ajax( $this->translate("edit") , "activity" , "/activity/stage/input/id/" . $rs->id )?>
					<?php endif;?>
					
					<?php if( $this->getPermission( "delete" ) ): ?>
						<?=$this->ajax( $this->translate("delete") , "activity" , "/activity/stage/delete/id/" . $rs->id , 1 , $this->translate("want to delete?") )?>
					<?php endif;?>
				</div>
			<?php endif; ?>
			
			<h4><?=$rs->title?></h4>
			<p><?=$rs->dss?></p>
			<br /><br />
			<?php if( $this->rs->key() > 0 ): ?>
				<input type="button" onclick="Toogle.previous();" value="<?=$this->translate("previous")?>" />
			<?php endif; ?>
			
			<?php if( ($this->rs->key() + 1) < $this->rs->count() ): ?>
				<input type="button" onclick="Toogle.next();" value="<?=$this->translate("next")?>" />
			<?php endif; ?>
			
			<?//php if( ( $this->role == Role::STUDENT ) && ( ($this->rs->key() + 1) == $this->rs->count() ) && ( $this->getPermission( array( "module" => "activity" , "controller" => "text" , "action" => "input"  ) ) ) ): ?>
				<input type="button" onclick='new Preceptor.util.AjaxUpdate( "text" , "<?=$this->url ?>/activity/text/input/" );' value="<?=$this->translate("make")?>" />
			<?//php endif; ?>
		</div>
		
	<?php endforeach;?>
<?php endif; ?>
<br />
<div id="text"></div>
<script>
	Toogle = new Preceptor.util.Toggle( Preceptor.util.elements );
</script>