<?php if( $this->getPermission( "input" ) || $this->rs->count() ): ?>
	<div class="right">
        <?=$this->ajax( $this->translate( "make" ) , 'activity-text' , $this->url . '/activity/text/input/' , 2 ); ?>

        <?php if( $this->getPermission( "input" ) ):?>
            <?=$this->ajax( $this->translate( "new" ) , 'activity-activity' , $this->url . '/activity/stage/input/' , 2 ); ?>
        <?php endif?>
    </div>

<?php endif; ?>
<?php if( $this->rs->count() ): ?>
	<div>
		<?php foreach($this->rs as $key => $rs): ?>
			<?php
                $arrow = "&raquo;";
                if( $key+1 == count($this->rs)){
                    $arrow = null;
                }
            ?>
			<a href="#this" onclick="Toogle.showOneHiddenAll( 'stage<?=$rs->id?>' )"><?=$rs->title?></a> <?=$arrow ?>
			<script>Preceptor.util.elements.push( "stage<?=$rs->id?>" );</script>
		<?php endforeach;?>
	</div>

    <br /><br />
    
	<?php $this->rs->rewind(); ?>
	<?php foreach( $this->rs as $rs ): ?>
		<div id="stage<?=$rs->id?>" class="padding" style="border: 1px #DDD solid;">
			<?php if( isset( $this->role ) && $this->role > 2 ): ?>
				<div class="right">
					<?php if( $this->getPermission( "input" ) ): ?>
						<?=$this->ajax( $this->translate("edit") , "activity-activity" , $this->url . "/activity/stage/input/id/" . $rs->id )?>
					<?php endif;?>

					<?php if( $this->getPermission( "delete" ) ): ?>
						<?=$this->ajax( $this->translate("delete") , "activity-activity" , $this->url . "/activity/stage/delete/id/" . $rs->id , 1 , $this->translate("want to delete?") )?>
					<?php endif;?>
				</div>
			<?php endif; ?>

			<h4><?=$rs->title?></h4>
			<p><?=$rs->ds?></p>
			<br /><br />
			<?php if( $this->rs->key() > 0 ): ?>
				<input type="button" onclick="Toogle.previous();" value="<?=$this->translate("previous")?>" />
            <?php else: ?>
                <input type="button" disabled="disabled" value="<?=$this->translate("previous")?>" />
			<?php endif; ?>

			<?php if( ($this->rs->key() + 1) < $this->rs->count() ): ?>
				<input type="button" onclick="Toogle.next();" value="<?=$this->translate("next")?>" />
            <?php else: ?>
                <input type="button" disabled="disabled" value="<?=$this->translate("next")?>" />
			<?php endif; ?>

			<input type="button" onclick='new Preceptor.util.AjaxUpdate( "activity-text" , "<?=$this->url ?>/activity/text/input/" );' value="<?=$this->translate("make")?>" />
		</div>
	<?php endforeach;?>
<?php endif; ?>
<br />
<div id="activity-text"></div>
<script>
	Toogle = new Preceptor.util.Toggle(Preceptor.util.elements);
</script>