<div>
	<form id="formStage_<?=$this->suffix?>">
		
		<?=$this->formHidden( "id" , $this->data->id )?>
		
		<label for="title_<?=$this->suffix?>"><?=$this->translate("title")?>:</label>
		<?=$this->formText( "title" , $this->data->title , array( "id" => "title_" . $this->suffix ) )?>
			
		<label for="ds_<?=$this->suffix?>"><?=$this->translate("description")?>:</label>
		<?=$this->formTextarea( "dss" , $this->data->dss , array( "id" => "ds_" . $this->suffix ) )?>
	
		<br /><br />
		
		<input id="activitySubmit" type="submit" value="<?=$this->translate("save")?>" />
	</form>
</div>
<script>

	var Editor_<?=$this->suffix?> = new Preceptor.widget.Editor( "ds_<?=$this->suffix ?>" , { addButton:["insertHtml"] } );
	
	Preceptor.util.Validate.prototype.onsubmit = function(){ 
		YAHOO.util.Event.on( 'formStage_<?=$this->suffix?>' , 'submit' , function( ev ){
			
			Editor_<?=$this->suffix?>.saveHTML();
			
			if( this.verify( $( 'formStage_<?=$this->suffix?>' ) ) )
			{
				new Preceptor.util.AjaxUpdate( this.div , this.url , { formId: this.formId } );
			}
			
			YAHOO.util.Event.stopEvent( ev );
			
		} , this , true );
	}
	
</script>
<?=$this->validate( "formStage_{$this->suffix}" , $this->jsonValidate , $this->suffix , "/activity/stage/save/" , "activity"  ); ?>