<div class="panel">
    <div class="right">
        <?php
            if($this->isAllowed( "form" ) ) {
               echo $this->ajax('Itens', 'panel/index/form', 2);
            }
        ?>
    </div>
    <div id="user-status">
        <?php echo $this->formRadio('status',$this->status, null, $this->statusOptions, '&nbsp;&nbsp;')?>
    </div>
    <br /><br /><br />
    <div class="list">
        <?php if (count($this->data)): ?>
            <table class="datatable">
                <tr>
                    <th></th>
                    <th><?php echo $this->translate('Note')?></th>
                    <th><?php echo $this->translate('Average')?></th>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role != 'student'):?>
                        <th><?php echo $this->translate('Status')?></th>
                    <?php endif; ?>
                </tr>
            <?php foreach($this->data as $user):?>
                <?php $total = 0?>
                <tr>
                    <td width="250">
                        <img alt="<?php echo $user->name ?>" src="upload/<?php echo $this->thumbnail($user->image, 'small') ?>" />
                        <?php echo $user->name;?>
                    </td>
                    <td>
                        <?php if (count($this->panel)):?>
                            <?php 
                                $i = 0;
                                $panelNote = new Tri_Db_Table('panel_note');
                                $panelNote = new Tri_Db_Table('panel_note');
                                $forumReply = new Tri_Db_Table('forum_reply');
                                $certificate = new Tri_Db_Table('certificate');
                                $activityText = new Tri_Db_Table('activity_text');
                            ?>
                            <?php foreach($this->panel as $panel):?>
                                <?php
                                    $note = $panelNote->fetchRow(array('panel_id = ?' => $panel->id, 'user_id = ?' => $user->id));
                                    $background = null;
                                    if ($panel->type == 'activity') {
                                        $row = $activityText->fetchRow(array('activity_id = ?' => $panel->item_id,
                                                                             'user_id = ?' => $user->id), 'id DESC');
                                        if ($row) {
                                            if ($row->status == 'close') {
                                                $background = 'background: #F3F781';
                                            } elseif ($row->status == 'final') {
                                                $background = 'background: #D0F5A9';
                                            }
                                        }
                                    }

                                    if ($panel->type == 'forum') {
                                        $row = $forumReply->fetchRow(array('forum_id = ?' => $panel->item_id,
                                                                           'user_id = ?' => $user->id));
                                        if ($row) {
                                            $background = 'background: #D0F5A9';
                                        }
                                    }

                                    if ($panel->type == 'exercise') {
                                        if ($note->note && $note->note > 0) {
                                            $background = 'background: #D0F5A9';
                                        }
                                    }
                                ?>
                                <form action="panel/index/save-note">
                                    <div class="item">
                                        <a href="<?php echo $panel->type?>/index/view/layout/box/id/<?php echo $panel->item_id?>/userId/<?php echo $user->id?>">
                                            <?php echo $this->translate($panel->type)?>
                                        </a>
                                        <div class="note">
                                            <?php $total += $note ? $note->note : '0';?>
                                            <?php if (Zend_Auth::getInstance()->getIdentity()->role == 'student'):?>
                                                <?php echo $note ? $note->note : '0';?>
                                            <?php else: ?>
                                                <input style="<?php echo $background?>" type="text" name="note" value="<?php echo $note ? $note->note : '0';?>" />
                                                <input type="hidden" name="user_id" value="<?php echo $user->id?>" />
                                                <input type="hidden" name="panel_id" value="<?php echo $panel->id?>" />
                                            <?php endif?>
                                        </div>
                                    </div>
                                    <?php $i++;?>
                                </form>
                            <?php endforeach;?>
                        <?php endif;?>
                    </td>
                    <td width="50">
                        <?php echo round($total/$i)?>
                    </td>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role != 'student'):?>
                        <td width="80">
                            <button class="status-button"><?php echo $this->translate('Change')?></button>
                            <div style="display: none;">
                                <?php
                                    if ($this->status == 'registered') {
                                        echo $this->ajax('Approve', 'panel/certificate/save/userId/'.$user->id, 2);
                                    } else {
                                        echo $this->ajax('Register', 'panel/index/change/status/registered/userId/'.$user->id, 2);
                                    }

                                    echo $this->ajax('Disapprove', 'panel/index/change/status/disapproved/userId/'.$user->id, 2);
                                    echo $this->ajax('Quitter justified', 'panel/index/change/status/justified/userId/'.$user->id, 2);
                                    echo $this->ajax('Quitter not justified', 'panel/index/change/status/not-justified/userId/'.$user->id, 2);
                                ?>
                            </div>
                        </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach;?>
            </table>
        <?php else:?>
            <p><?php echo $this->translate("there are no records");?></p>
        <?php endif;?>
    </div>
</div>
<script type="text/javascript">
    var opened = false;
    $(".close").live("click", function(){
        $(this).parents('.box').remove();
        opened = false;
        return false;
    });

    $('.panel form').submit(function(){
        return false;
    });
    
    $('.panel .item a').click(function(){
        var $this = $(this);
        $.get(this.href, function(data){
            if (opened) {
                $this.parents('.box').prev().html(data);
            } else {
                $this.parents('.box').before(data);
                opened = true;
            }
        });
        return false;
    });

    $('.panel .note input[type=text]').blur(function(){
        var $this = $(this),
            $form = $this.parents('form');

        $.post($form[0].action, $form.serialize(), function(){
            alert('<?php echo $this->translate('Success')?>.');

            var sum = 0, i = 0, average = 0;
            $this.parents('tr').find('input[type=text]').each(function(){
                sum += parseInt(this.value, 10);
                i++;
            });
            
            average = Math.round(sum/i);
            $this.parents('td').next().text(average);
        });
    });

    $('.status-button').button().click(function(){
        $(this).hide().next().show();
    });

    $('#user-status label').click(function(){
        var $this = $(this);
        $this.parents('.content').load('panel/index/index/status/'+$this.children('input').val());
    });

    $('input[type=button], input[type=submit]').button();
</script>