<?php if($this->isAllowed('form')): ?>	
	<div class="right"><?=$this->ajax("new", 'chat/room/form/', 2); ?></div>
<?php endif; ?>	
<div class="left">
    <form id="formFindRoom" action="#">
        <span class="ui-icon ui-icon-search magnifier"></span>
        <input type="text" name="q" id="qRoom" style="width: 16em" />
        <input type="submit" value="ok" /> &nbsp;&nbsp;&nbsp;
    </form>
</div>
<div class="clear">&nbsp;</div>

<?php if (count($this->data)):?>
    <table class="datatable">
        <?php foreach ($this->data as $data): ?>
            <tr>
                <td>
                    <?php echo $this->ajax($data->title, 'chat/room/live/id/'.$data->id)?>
                    (<?php echo $data->total?>)
                </td>
                <td>
                    <?php echo $this->translate($data->status)?>
                </td>
                <td nowrap="nowrap">
                    <?php if ($this->isAllowed('form')): ?>
                        <?php echo $this->ajax("edit", 'chat/room/form/id/'. $data->id, 2); ?>
                    <?php endif;?>

                    <?php if($this->isAllowed("delete")): ?>
                        <?php echo $this->ajax("delete", 'chat/room/delete/id/' . $data->id, 2 , "want to delete?");?>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <div id="room-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
<?php else:?>
    <p><?=$this->translate( "there are no records" );?></p>
<?php endif;?>
<script type="text/javascript">
    $('.room-show').click(function(){
        $(this.target).toggle();
        return false;
    });

    $('#room-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $("#formFindRoom").submit(function(ev) {
		$(this).parents('.content').load('chat/room/index/q/' + $('#qRoom').val());
        return false;
	});

    $('input[type=button], input[type=submit]').button();
</script>