<div class="chat-room">
    <div>
        <h3><?php echo $this->data->title?></h3>
        <?php echo $this->data->description?>
    </div>
    <br />
    <div class="stream">
        <?php echo $this->render('room/stream.phtml')?>
    </div>
    <br />
    <div class="form">
        <form action="chat/room/live-save">
            <input type="hidden" value="<?php echo $this->id?>" name="id" />
            <textarea rows="5" name="description"></textarea><br />
            <input type="submit" value="<?php echo $this->translate('Send')?>" />
        </form>
    </div>
</div>
<script type="text/javascript">
    $('.chat-room form').submit(function(){
        var $this = $(this);
        $.post(this.action, $this.serialize(), function(data){
            $this.prev('.stream').html(data);
            $this.find('textarea').val('');
        });
        return false;
    });

    $('.chat-room form textarea').keypress(function(e){
        if (e.keyCode == 13) {
            $(this).parents('form').submit();
            return false;
        }
    });

    <?php if(!$this->interval):?>
        var intervalVar = setInterval(function(){
            var $liveRoom = $('.chat-room');

            if ($liveRoom.length) {
                $liveRoom.children('.stream')
                         .load('chat/room/live/interval/true/id/<?php echo $this->id?>');
            } else {
                clearInterval(intervalVar);
            }
        }, 30000);
    <?php endif?>
</script>
