<div class="right">
    <a href="classroom/form"><?php echo $this->translate('New')?></a>
</div>
<div class="search">
    <form action="classroom/index" method="get">
        <input type="text" name="query" value="<?php echo $this->params['query']?>" />
        <input type="submit" value="<?php echo $this->translate('Search')?>" />
    </form>
</div>
<br />
<div class="courses">
    <?php if (count($this->data)): ?>
        <?php foreach($this->data as $data): ?>
            <div class="item">
                <a href="classroom/form/id/<?php echo $data->id?>"><?php echo $data->name?></a>
            </div>
        <?php endforeach; ?>
        <?php echo $this->paginationControl($this->data, null, null, $this->params); ?>
    <?php else:?>
        <p><?php echo $this->translate('No register')?></p>
    <?php endif;?>
</div>
<script type="text/javascript">
    $('form').submit(function(){
        this.action = this.action + '/query/' + $('input[type=text]').val();
    });
</script>