<?php echo $this->render('menu.phtml') ?>
<div id="main">

</div>
<div id="fixed">
    <div class="box">
        <div class="main index">
            <div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
                <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
                    <h3><?php echo $this->translate('content'); ?></h3>
                </div>
                <div class="courses ui-dialog-content ui-widget-content">
                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(".close").live("click", function(){
        $(this).parents('.box').remove();
        return false;
    });

    $(".fix").live("click", function(){
        $('#fixed').prepend($(this).parents('.box'));
        $(this).remove();
        return false;
    });
</script>