<?php echo $this->render('menu.phtml') ?>
<a name="start0"></a>
<div id="main">

</div>
<div id="fixed">
    <?php if (in_array('content', Tri_Config::get('tri_plugins', true))) :?>
    <div class="box">
        <div class="main index">
            <div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
                <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
                    <h3><?php echo $this->translate('base-text'); ?></h3>
                </div>
                <div id="content" class="ui-dialog-content ui-widget-content">
                    <div class="nav">
                        <div class="bread">
                            <img src="img/treeview.gif" />
                            <div class="treeview"></div>
                            <span></span>
                        </div>
                        <div class="buttons">
                            <a class="previous" href="content/previous"><?php echo $this->translate('previous content') ?></a>&nbsp;&nbsp;
                            <a class="next" href="content/next"><?php echo $this->translate('next content') ?></a>
                        </div>
                    </div>
                    <div id="content-main-content" class="text">

                    </div>
                    <div class="nav">
                        <div class="buttons">
                            <a class="previous" href="content/previous"><?php echo $this->translate('previous content') ?></a>&nbsp;&nbsp;
                            <a class="next" href="content/next"><?php echo $this->translate('next content') ?></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $('#content').navigation('<?=str_replace("\'", "'", $this->data)?>', {current: <?php echo $this->current?>});
    </script>
    <?php endif;?>
</div>
<script type="text/javascript">
    $(".close").live("click", function(){
        $(this).parents('.box').remove();
        return false;
    });

    $(".fix").live("click", function(){
        $('#fixed').prepend($(this).parents('.box'));
        $(this).remove();
        return false;
    });
</script>