<div class="right">
	<?php if( $this->getPermission( "input" ) ): ?>
		<?=$this->ajax( $this->translate("new") , "faq-faq" , $this->url . "/faq/faq/input" , 2 ) ?>
	<?php endif; ?>
</div>
<div class="clear"></div>
<br />
<?php if( $this->rs->count() ):?>
		<table class="tablesorter">
            <thead>
                <tr>
                    <th><?=$this->translate("category")?></th>
                    <th></th>
                </tr>
            </thead>
            
            <tbody>
                <?php foreach( $this->rs as $key => $rs ): ?>
                    <?php if( $this->getPermission( "input" ) ): ?>
                        <?php $edit = $this->ajax( $this->translate("edit") , "faq-faq" , $this->url . "/category/category/input/id/" . $rs->id ); ?>
                    <?php endif; ?>

                    <?php if( $this->getPermission( "delete" ) ): ?>
                        <?php $delete = $this->ajax( $this->translate("delete") , "faq-faq" , $this->url . "/category/category/delete/id/" . $rs->id , 1 , $this->translate( "want to delete?" ) ); ?>
                    <?php endif; ?>
                    
                    <tr class="<?=$this->changeClass( $key , array( 'even' , 'odd' ) )?>">
                        <td nowrap="nowrap"><?=$this->ajax( $rs->name , 'faq-faq' , $this->url . '/faq/faq/view/id/' . $rs->id );?></td>
                    <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                        <td nowrap="nowrap" width="77"><?=$edit . " " . $delete?></td>
                    <?php endif; ?>
                    </tr>
                <?php endforeach;?>
            </tbody>
		</table>
<?php else:?>
   <div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif;?>