<?=$this->element()->startForm();?>
<div class="yui-skin-sam" id="div-form-<?=$this->model?>">
     <?php
        echo $this->element()->formHidden( "id" , $this->data->id , array( "printLabel" => false ) )
                  ->formText( "question" , $this->data->question )
                  ->formTextarea( "answer" , $this->data->answer );
     ?>

    <?php //if( ( $this->getPermission( "input" ) ) && ( ! $this->data->id ) ): ?>
        <br />
        <div class="right" style="margin-right: 95px;">
            <input type="button" id="manager_category_faq" value="<?=$this->translate("category")?>" >
        </div>
    <?php //endif; ?>

    <a name="focus_faq"></a>
    <div id="categories">
        <label for="category_<?=$this->suffix?>"><?=$this->translate("categories")?>:</label>
        <?=$this->groupedList( "faqall" , $this->all , "faqchecked" , $this->checked , null , array( 'height' => '180px' , 'width' => '292px' , 'width_text' => '288px' ) );?>
    </div>

    <?php echo $this->element()->formSubmit( "model" , $this->translate("save") , array( "printLabel" => false ) ) ?>
    <div class="clear"></div>
</div>
<script>
    $( "#manager_category_faq").click(function(){
        layout.addPanel( "category-category" , "<?=$this->url?>/category/category/index/type/F/id/<?=$this->data->id?>" );
	});
</script>
<?=$this->formRelation( $this->data->id , array( "groupedList" => true ) )?>