<?php if( $this->rs->count() ):?>
	<table width="100%" class="tablesorter">
        <thead>
            <tr>
                <th><?=$this->category->name ?></th>

                <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                    <th width="77px"></th>
                <?php endif;?>
            </tr>
        </thead>

        <tbody>
            <?php foreach( $this->rs as $rs ):?>
                <?php $class  = $this->changeClass( $this->rs->key() , array( "even" , "odd" ) );?>
                <?php if( $this->getPermission( "input" ) ): ?>
                    <?php $edit = $this->ajax( $this->translate("edit") , 'faq-faq' , $this->url . '/faq/faq/input/id/' . $rs->id );?>
                <?php endif;?>

                <?php if( $this->getPermission( "delete" ) ): ?>
                    <?php $delete = $this->ajax( $this->translate("delete") , 'faq-faq' , $this->url . "/faq/faq/delete/id/{$rs->id}/category_id/{$this->category->id}" , 1 , $this->translate("want to delete?") );?>
                <?php endif;?>

                <tr class="<?=$class?>">
                    <td nowrap="nowrap"><?=($this->rs->key()+1)?>. <a href="#this" onclick="showHidden( '<?=$rs->id ?>' )"><?=$this->escape( $rs->question )?></a></td>
                    <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                        <td nowrap="nowrap"><?=$edit . " " . $delete?></td>
                    <?php endif;?>
                </tr>
                <tr class="<?=$class?>">
                    <td id="<?=$rs->id ?>" style="display: none;" colspan="2"><?=$rs->answer?></td>
                </tr>
            <?php endforeach;?>
        </tbody>
	</table>
<?php else:?>
	<div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif;?>

<br />

<div class="right">
	<?php if( $this->limit < 999999 && count( $this->counts ) > 1 ): ?>
		<?=$this->ajax( $this->translate("all reply") , "forum" , $this->url . "/forum/forum/view/id/" . $this->forum_id . "/to/0/limit/999999" , 2 )?>
	<?php endif;?>
</div>	