<div id="reportComunication">
	
	<input type="radio" value="chat" id="chatReport" name="comunication" onclick="new Preceptor.util.AjaxUpdate( 'reportResponse' , 'log/comunication/view/comunication/' + this.value );" />
	<label for="chatReport">Chat</label>
	
	<input type="radio" value="forum" id="forumReport" name="comunication" onclick="new Preceptor.util.AjaxUpdate( 'reportResponse' , 'log/comunication/view/comunication/' + this.value );" />
	<label for="forumReport">F&oacute;rum</label>
	
	<input type="radio" value="message" id="messageReport" name="comunication" onclick="new Preceptor.util.AjaxUpdate( 'reportResponse' , 'log/comunication/view/comunication/' + this.value );" />
	<label for="messageReport">Mensagem</label>

	<div id="reportResponse">

	</div>

</div>
