<?php if($this->isAllowed('form')): ?>	
	<div class="right"><?=$this->ajax("new", 'forum/index/form/', 2); ?></div>
<?php endif; ?>	
<div class="left">
    <form id="formFindForum" action="#">
        <span class="ui-icon ui-icon-search magnifier"></span>
        <input type="text" name="q" id="qForum" style="width: 16em" />
        <input type="submit" value="ok" /> &nbsp;&nbsp;&nbsp;
    </form>
</div>
<div class="clear">&nbsp;</div>

<?php if (count($this->data)):?>
    <table class="datatable">
        <?php foreach ($this->data as $data): ?>
            <tr>
                <td><?php echo $this->ajax($data->title, 'forum/reply/index/id/' . $data->id);?></td>
                <td nowrap="nowrap">
                    <?php if ($this->isAllowed('form')): ?>
                        <?php echo $this->ajax("edit", 'forum/index/form/id/'. $data->id, 2); ?>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <div id="forum-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
<?php else:?>
    <p><?=$this->translate( "there are no records" );?></p>
<?php endif;?>
<script type="text/javascript">
    $('#forum-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $("#formFindForum").submit(function(ev) {
		$(this).parents('.content').load('forum/index/index/q/' + $('#qForum').val());
        return false;
	});

    $('input[type=button], input[type=submit]').button();
</script>