<?php $locale = strtolower(str_replace('_', '-', $this->locale))?>
<div class="composer">
	<?php echo $this->form?>
</div>
<script type="text/javascript">
    var $composer = $('#composer-description-text'),
        config = {
            toolbar: [
                ['Source','-','Preview','Templates'],
                ['Cut','Copy','Paste','PasteText','PasteFromWord'],
                ['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],
                '/',
                ['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
                ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote','CreateDiv'],
                ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
                ['Link','Unlink','Anchor'],
                ['Image','Flash','Table','HorizontalRule','SpecialChar'],
                '/',
                ['Styles','Format','Font','FontSize'],
                ['TextColor','BGColor'],
                ['Maximize', 'ShowBlocks','-','About']
            ],language: '<?php echo $locale?>'
        }, editor = CKEDITOR.appendTo('description-element', config, $composer.val());
    $composer.hide();

    $(".composer form").submit(function() {
        var $this = $(this);
        $composer.val(editor.getData());
		$.post(this.action, $(this).serialize(), function(data){
            $('#content-main-composer').html(data);
        });
        return false;
	});
    $('input[type=button], input[type=submit]').button();
</script>