<script type="text/javascript">
    $( "#content-content" ).hide();
</script>
<div class="yui-skin-sam ui-dialog ui-widget ui-widget-content ui-corner-all">
	<div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
		<span class="ui-dialog-title" id="ui-dialog-title-dialog">
			<h3><?=$this->translate( $this->controller );?></h3>
		</span>
		<a href="#" id="content-composer-close" class="ui-dialog-titlebar-close ui-corner-all">
			<span class="ui-icon ui-icon-closethick">close</span>
		</a>
	</div>
	<div class="ui-dialog-content ui-widget-content">
		<?php if( $this->messages ): ?>
			<div class="ui-state-highlight ui-corner-all message">
				<span class="ui-icon ui-icon-info"></span>
				<?php foreach( $this->messages as $key => $val ): ?>
					<p><?=$val?></p>
				<?php endforeach; ?>
			</div>
		<?php endif; ?>

		<div id="composer-content-main">
            <div class="nav">
                <div class="bread">
                    <img src="<?=$this->url?>/img/icons/treeview.gif" />
                    <div class="treeview"></div>
                    <span></span>
                </div>
                <div class="buttons">
                    <a href="#this"><?=$this->translate('previous')?></a> |
                    <a href="#this"><?=$this->translate('next')?></a>
                </div>
                <div class="clear zero"></div>
            </div>
            <div style="text-align: right">
                <?=$this->ajax( $this->translate("new") , "composer-content-content" , $this->url . "/content/composer/input" , 2 ) ?>
            </div>
            <div class="content" id="composer-content-content"></div><br />

            <textarea id="magic-editor"></textarea>
        </div>

        <script type="text/javascript">
            $( "#content-content" ).hide();

            var initCurrent = 0;

            window.Editor_Composer = new Preceptor.widget.Editor( 'magic-editor' , { addButton:['uploadImage', "insertHtml"] } );

            <?php if( $this->go ): ?>
                initCurrent = $(window).data('current_index')-1;
            <?php else:?>
                initCurrent = $(window).data('current_index');
            <?php endif?>

            <?php if( $this->current ): ?>
                initCurrent = <?=$this->current?>;
            <?php endif?>

            $('#composer-content-main').navigation(
                '<?=$this->contents?>' ,
                { baseUrl:'<?=$this->url?>',
                  url:'/content/composer/input/id/',
                  current: initCurrent,
                  cache: false }
            );

            $( "#content-composer-close" ).click(function(){
                $( "#content-composer" ).remove();
                $( "#content-content" ).show();
            });
        </script>
	</div>
</div>