<div id="view-person-bulletin">
    <div id="view-person-bulletin-close" class="right" style="display:none;">
        <a href="#this" class="ui-state-default ui-corner-all left" title="<?=$this->translate( 'delete' )?>" style="width: 17px; display: block;">
            <span class="ui-icon ui-icon-close"></span>
        </a>
    </div>
    <div id="view-person-bulletin-content"></div>
</div>

<div id="select-person-bulletin">
    <div class="right">
        <?php if( $this->getPermission( "input" ) ): ?>
            <?=$this->ajax( $this->translate("new") , "bulletin" , "/bulletin/bulletin/input" , 2 ) ?>
        <?php endif; ?>
    </div>
    <br /><br />

    <?php if( $this->rs->count() ): ?>
        <?php if($this->role != Role::STUDENT ):?>
    <form id="form-search-bulletin" action="#">
        <input type="text" id="search" name="search" style="width:300px;" />
        <input type="submit" value=" <?php echo $this->translate('search')?> "/>
    </form>
    <script type="text/javascript">
        jQuery('#form-search-bulletin > #search')
        .val('Digite o nome do aluno')
        .focus( function(){
            jQuery(this).val( '' );
        })
        .blur( function(){
            if(!jQuery.trim(jQuery(this).val())){
                jQuery(this).val('Digite o nome do aluno');
            }
        });

        jQuery('#form-search-bulletin').submit( function(){
            if(jQuery("#form-search-bulletin > #search").val() == "Digite o nome do aluno"){
                jQuery("#form-search-bulletin > #search").val('all');
            }
            new Preceptor.util.AjaxUpdate('mainbulletin', "<?php echo $this->url?>/bulletin/bulletin/index", {formId: this.id})
            return false;
        })
    </script>
    
    <br/>
            <?php echo $this->translate('number of students')?>: <?php echo count($this->persons)?>
    <br/><br/>
        <?php endif;?>
        <?php echo $this->translate('Legenda')?>:
    <span class="evaluations"><?php echo $this->translate('Nada salvo')?></span>
    <span class="evaluations bulletin_gray"><?php echo $this->translate('Aguardando finalização do aluno')?></span>
    <span class="evaluations bulletin_yellow"><?php echo $this->translate('Aguardando correção')?></span>
    <span class="evaluations bulletin_orange"><?php echo $this->translate('Aguardando nota')?></span>
    <span class="evaluations bulletin_green"><?php echo $this->translate('Lançada a nota')?></span>
    <br/><br/>
    <div id="dialog-email"></div>
    <div class="right">
        <a href="#this" class="left" id="checkAll" style="margin-right:10px;">Marcar todos</a>
        <a href="#this" class="left" id="uncheckAll">Desmarcar todos</a>
    </div>
    <br><br>
    <form id="form" action="#this">
        <?php if($this->role != Role::STUDENT ):?>
        <div id="layout-email">
            <div>
                <label for="subject"><?php echo $this->translate('subject')?>: </label>
                    <?php echo $this->formText('subject') ?>
            </div>
            <br>
            <div>
                <textarea id="ds" name="ds" style="height: 150px;width: 100%"></textarea>
            </div>
            <div class="right">
                <br>
                <input type="button" id="view-email" value=" <?=$this->translate('view email')?> " style="margin-left:10px;" />
                <input type="submit" value=" <?=$this->translate('send email')?> " style="margin-left:10px;" />
            </div>
            <div class="clear">&nbsp;</div>
            <br/>
        </div>
        <?php endif;?>
        <table class="datatable">
            <tr>
                <?php if($this->role != Role::STUDENT ):?>
                    <th rowspan="2"><?php echo $this->image('icones/email.png')?></th>
                <?php endif;?>
                <th rowspan="2"><?=$this->translate("student")?></th>
                    <?php foreach( $this->rs as $key => $rs ):?>
                <th colspan="2">
                            <?php if( $this->getPermission( "input" ) ): ?>
                                <?="<a href='#this' style='color: #FFFFFF;' onclick=\"new Preceptor.util.AjaxUpdate( 'bulletin' , '{$this->url}/bulletin/bulletin/input/id/{$rs->id}' )\" >{$rs->title}"?>
                            <?php else : ?>
                                <?=$rs->title?>
                            <?php endif; ?>
                </th>
                        <?php $evaluations[$key] = $this->itemEvaluatios( $rs ) ?>
                    <?php endforeach;?>
                <th rowspan="2"><?=$this->translate("overall average")?></th>
                <th rowspan="2"></th>
            </tr>
            <tr>
                    <?php foreach( $this->rs as $key => $rs ):?>
                <th><?=$this->translate("note")?></th>
                <th><?=$this->translate("average")?></th>
                    <?php endforeach;?>
            </tr>
                <?=$this->printItemEvaluatios( $this->persons , $evaluations , $this->person_id , $this->role ) ?>
        </table>
    </form>

    <?php else: ?>
    <table class="datatable">
        <tr class="<?=$class?>">
            <td><?=$this->translate( "there are no records" );?></td>
        </tr>
    </table>
    <?php endif; ?>
</div>
<div id="nulo"></div>
<script type="text/javascript">
    jQuery('#view-person-bulletin').hide();
    jQuery('#layout-email').hide();

    jQuery('.link-bulletin > a').click( function(){
        jQuery('#view-person-bulletin').show();
        jQuery('#view-person-bulletin-close').show();
        jQuery('#select-person-bulletin').hide();
    });

    jQuery('#view-person-bulletin-close').click( function(){
        jQuery('#view-person-bulletin').hide();
        jQuery('#select-person-bulletin').show();
        jQuery('#view-person-bulletin-content').html('');
    });

    jQuery( '#form' ).submit( function(){
        Editor_email.saveHTML();
        if(jQuery("#form .email > input[type='checkbox']:checked").length){
            if(jQuery('#ds').val()){
                if(confirm("<?php echo $this->translate('really want to send this email?')?>")){
                    new Preceptor.util.AjaxUpdate( 'mainbulletin' , '<?=$this->url?>/email/email/send' , { formId: "form" });
                }
            }else{
                alert('Digite um texto para enviar o email');
            }
        }else{
            alert('Selecione alguem pra enviar o email');
        }
        return false;
    });

    jQuery('#view-email').click( function(){
        Editor_email.saveHTML();
        new Preceptor.util.AjaxUpdate( 'dialog-email' , '<?=$this->url?>/email/email/view' , { formId: "form" });
        jQuery('#dialog-email').dialog('open').show();
    });

    jQuery("#dialog-email")
    .dialog({
        autoOpen: false,
        height: 350,
        width: 610,
        modal: false
    })
    .hide()
    .bind('dialogclose', function(){
        jQuery(this).html('');
    });

    jQuery('#checkAll').click(function() {
        jQuery("#form .email > input[type=checkbox]").each(function(j , val) {
            this.checked = true;
        });
        jQuery('#layout-email').show();
    });

    jQuery('#uncheckAll').click(function() {
        jQuery("#form .email > input[type=checkbox]").each(function() {
            this.checked = false;
        });
        jQuery('#layout-email').hide();
    });

    jQuery("#form .email > input[type='checkbox']").click(function() {
        if(jQuery("#form .email > input[type='checkbox']:checked").length){
            jQuery('#layout-email').show();
        }else{
            jQuery('#layout-email').hide();
        }
    });

    var Editor_email = new Preceptor.widget.Editor("ds");
</script>