<div class="filter">
    <div class="legend pos-relative"><?=$this->translate("filter")?></div>
    
    <label for="type"><?=$this->translate("type")?>:</label><br /><br />
    
    <input id="evaluation_<?=$this->suffix?>" checked='checked' name="type" type="radio" value="<?=Restriction::EVALUATION ?>" > <?=$this->translate("performance")?>&nbsp;
	<input id="time_<?=$this->suffix?>" <?=$check_time ?> name="type" type="radio" value="<?=Restriction::TIME ?>" > <?=$this->translate("time")?>&nbsp;
    <div class="clear"></div>
</div>	

<div id="evaluation_time">
	<div class="right">
		<?php if( $this->getPermission( "input" ) ): ?>
			<?=$this->ajax( $this->translate("new") , "restriction" , "/restriction/restriction/input/type/" . Restriction::EVALUATION , 2 ) ?>
		<?php endif; ?>
	</div>
	<div class="clear"></div>
	<br />
	<?php if( $this->rs->count() ):?>
		<table class="datatable">
			<tr>
				<th><?=$this->translate("group")?></th>
				<th><?=$this->translate("performance")?></th>
                <th><?=$this->translate("note")?></th>
                <th><?=$this->translate("content")?></th>
                <th><?=$this->translate("action")?></th>
			</tr>
			<?php foreach( $this->rs as $rs ): ?>
				<?php $class  = $this->changeClass( $this->rs->key() , array( "light_gray" , "white" ) );?>
				
				<tr class="<?=$class?>">
					<?php 
						try{
							$title = $rs->findParentRow('Restriction')->findParentRow('Group')->title;
						}catch ( Exception $e ){}
						if ( $title )
							$title = $title;
						else
							$title = $this->translate('all');
							
					?>
					<td><?=$title ?></td>
					<td><?=$rs->findParentRow('BulletinGroup')->title?></td>
                    <td><?=$rs->note?></td>
                    <td nowrap="nowrap"><?=$rs->findParentRow('Restriction')->findParentRow('Content')->title?></td>
                    <td width="100">
                        <?=$this->ajax( $this->translate("edit") , "restriction" , "/restriction/restriction/input/id/" . $rs->id . "/type/" . Restriction::EVALUATION )?> | 
                        <?=$this->ajax( $this->translate("delete") , "restriction" , "/restriction/restriction/delete/id/" . $rs->id . "/type/" . Restriction::EVALUATION , 1, $this->translate( "want to delete?" ) )?>
                    </td>
				</tr>
			<?php endforeach;?>
		</table>  
	<?php else:?>
		<table class="datatable">
			<tr class="<?=$class?>">
				<td><?=$this->translate( "there are no records" );?></td>
			</tr>
		</table> 
	<?php endif;?>
</div>
		
<script>
	YAHOO.util.Event.on( "evaluation_<?=$this->suffix?>" , "click" , function(){
		new Preceptor.util.AjaxUpdate( "evaluation_time" , "<?=$this->url?>/restriction/restriction/index/type/" + this.value );
	});
	
	YAHOO.util.Event.on( "time_<?=$this->suffix?>" , "click" , function(){
		new Preceptor.util.AjaxUpdate( "evaluation_time" , "<?=$this->url?>/restriction/restriction/index/type/" + this.value );
	});
</script>