<?php $this->suffix = $this->controller ?>
<form id="formRestrictionTime_<?=$this->suffix?>">

	<?=$this->formHidden( "id" , $this->data->rid )?>
	<?=$this->formHidden( "bulletin_id" , $this->data->bulletin_id )?>
	
	<label for="group"><?=$this->translate("group")?>:</label>
	<?=$this->formSelect( "group_id" , $this->data->group_id , null , $this->groups )?>
	
	<label for="started_<?=$this->suffix?>"><?=$this->translate("date init")?>:</label>
	<?=$this->formText( "started" , $this->date( $this->data->started ) , array( "id" => "started_" . $this->suffix ) )?>
	
	<label for="finished_<?=$this->suffix?>"><?=$this->translate("date expired")?>:</label>
	<?=$this->formText( "finished" , $this->date( $this->data->finished ) , array( "id" => "finished_" . $this->suffix ) )?>
	
	<label for="content_id"><?=$this->translate("content")?>:</label>
	<?=$this->formSelect( "content_id" , $this->data->content_id , null , $this->contents )?>
	
	<br /><br />
	        
	<input type="submit" value="<?=$this->translate("save")?>" />
	
	<div class="clear"></div>

</form>	
<script>
	new Preceptor.util.Mask( "started_<?=$this->suffix ?>" , {mask:'00/00/0000'} )
	new Preceptor.util.Mask( "finished_<?=$this->suffix ?>" , {mask:'00/00/0000'} )
	
	Preceptor.util.Validate.prototype.onsubmit = function(){ 
		YAHOO.util.Event.on( 'formRestrictionTime_<?=$this->suffix?>' , 'submit' , function( ev ){
			
			if( this.verify( $( 'formRestrictionTime_<?=$this->suffix?>' ) ) )
			{
				new Preceptor.util.AjaxUpdate( this.div , this.url , { formId: this.formId } );
			}
			
			YAHOO.util.Event.stopEvent( ev );
			
		} , this , true );
	}
</script>

<?=$this->validate( "formRestrictionTime_{$this->suffix}" , $this->jsonValidate , $this->suffix , "/restriction/restriction/save/type/CT" , "restriction" ); ?>