<form id="formRestrictionEvaluation_<?=$this->suffix?>">
	
	<?=$this->formHidden( "id" , $this->data->rid )?>
	<?=$this->formHidden( "bulletin_id" , $this->data->bulletin_id )?>
	
	<label for="group"><?=$this->translate("group")?>:</label>
	<?=$this->formSelect( "group_id" , $this->data->group_id , array( "id" => "group_id" . $this->suffix ) , $this->groups )?>
	
	<br /><br />
	<label for="evaluation"><?=$this->translate("performance")?>:</label>
	<?=$this->formSelect( "bulletin_group_id" , $this->data->bulletin_group_id , array( "id" => "bulletin_group_id" . $this->suffix ) , $this->evaluations )?>
	
	<br /><br />
	
	<label for="note_<?=$this->suffix?>"><?=$this->translate("minimum note")?>:</label>
	<?=$this->formText( "note" , $this->data->note , array( "id" => "note_" . $this->suffix ) )?>
	
	<br /><br />
	
	<label for="note_restriction_<?=$this->suffix?>"><?=$this->translate("obtaining the following note eliminates the restriction of time")?>:</label>
	<?=$this->formText( "note_restriction" , $this->data->note_restriction , array( "id" => "note_restriction_" . $this->suffix ) )?>
	
	<br /><br />
	
	<label for="content_id"><?=$this->translate("restricting from")?>:</label>
	<?=$this->formSelect( "content_id" , $this->data->content_id , null , $this->contents )?>
	
	<br /><br />
	        
	<input type="submit" value="<?=$this->translate("save")?>" />
	
	<div class="clear"></div>
	
</form>

<script>
	
	Preceptor.util.Validate.prototype.onsubmit = function(){ 
		YAHOO.util.Event.on( 'formRestrictionEvaluation_<?=$this->suffix?>' , 'submit' , function( ev ){
			
			if( this.verify( $( 'formRestrictionEvaluation_<?=$this->suffix?>' ) ) )
			{
				new Preceptor.util.AjaxUpdate( this.div , this.url , { formId: this.formId } );
			}
			
			YAHOO.util.Event.stopEvent( ev );
			
		} , this , true );
	}
    
</script>
<?=$this->validate( "formRestrictionEvaluation_{$this->suffix}" , $this->jsonValidate , $this->suffix , "/restriction/restriction/save/type/AV" , "restriction" ); ?>