<div class="right">
    <?php echo $this->ajax('back', 'faq/index', 2) ?>
</div>
<div class="faq">
<?php echo $this->form?>
</div>
<script type="text/javascript">
	$(".faq form").submit(function() {
        var $this = $(this);
		$.post('faq/index/save', $(this).serialize(), function(data){
            $this.parents('.content').html(data);
        });
        return false;
	});
    $('input[type=button], input[type=submit]').button();
</script>