<?php if($this->isAllowed('form')): ?>	
	<div class="right"><?=$this->ajax("new", 'faq/index/form/', 2); ?></div>
<?php endif; ?>	
<div class="left">
    <form id="formFindFaq" action="#">
        <input type="text" name="q" id="qFaq" style="width: 16em" />
        <input type="submit" value="OK" /> &nbsp;&nbsp;&nbsp;
    </form>
</div>
<div class="clear">&nbsp;</div>

<?php if (count($this->data)):?>
    <table class="datatable">
        <?php foreach ($this->data as $data): ?>
            <tr>
                <td>
                    <a class="faq-show" href="#" target="#f<?php echo $data->id?>"><?php echo $data->question?></a>
                    <div style="display: none; margin-top: 10px;" id="f<?=$data->id?>"><?php echo nl2br($data->answer)?></div>
                </td>
                <td nowrap="nowrap">
                    <?php if ($this->isAllowed('form')): ?>
                        <?php echo $this->ajax("edit", 'faq/index/form/id/'. $data->id, 2); ?>
                    <?php endif;?>

                    <?php if($this->isAllowed("delete")): ?>
                        <?php echo $this->ajax("delete", 'faq/index/delete/id/' . $data->id, 2 , "want to delete?");?>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <div id="faq-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
<?php else:?>
    <p><?=$this->translate( "there are no records" );?></p>
<?php endif;?>
<script type="text/javascript">
    $('.faq-show').click(function(){
        $(this.target).toggle();
        return false;
    });

    $('#faq-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $("#formFindFaq").submit(function(ev) {
		$(this).parents('.content').load('faq/index/index/q/' + $('#qFaq').val());
        return false;
	});
</script>