<?=$this->render("search/menu.phtml")?>
<?php if( $this->searchContent->count() ): ?>
	<table class="datatable">
		<th><?=$this->translate("result")?></th>
	
		<?php foreach( $this->searchContent as $key => $val ): ?>
			<?php $class  = $this->changeClass( $this->searchContent->key() , array( "light_gray" , "white" ) );?>
			<tr class="<?=$class?>">
				<td nowrap="nowrap">
					<a href="#this" onclick="selectedNavigatorCourse( <?=$val->id?> ); new Preceptor.util.AjaxUpdate( 'content-main-content' , '<?=$this->url?>/content/view/id/<?=$val->id;?>');" ><?=$val->title;?></a>
				</td>
			</tr>  
		<?php endforeach;?>
	
	</table>
<?php else:?>
	<table class="datatable">
		<tr class="<?=$class?>">
			<td><?=$this->translate( "there are no records" );?></td>
		</tr>
	</table>
<?php endif;?>

<div class="clear"></div>

<script>
	selectedNavigatorCourse = function( valueEl )
	{
		var options = $( 'select_content_id' ).options;
		
		for( var i = 0 , len = options.length; i < len; i++ )
		{
			if( options[i].value == valueEl )
			{
				$( 'select_content_id').selectedIndex = i;
				break;
			}
		}
	}
</script>