<?=$this->render("search/menu.phtml")?>

<?php if( $this->paginator->count() ): ?>
	<table class="tablesorter">
        <thead>
            <tr>
                <th><?=$this->translate("result")?></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach( $this->paginator as $key => $val ): ?>
                <tr class="<?=$this->changeClass( $key , array( "even" , "odd" ) )?>">
                    <td nowrap="nowrap">
                        <a href="#this" onclick="layout.addPanel( 'glossary-glossary' , '<?=$this->url?>/glossary/glossary/index/q/<?=$val->word;?>'); $('#search').remove();" ><?=$val->word;?></a>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
	</table>
    <?=$this->paginationControl($this->paginator, 'Sliding', 'search/pagination.phtml'); ?>
    <div class="clear">&nbsp;</div>
<?php else:?>
	<div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif;?>

<div class="clear"></div>
<script type="text/javascript">
    action = "<?=$this->type?>";
</script>