<?=$this->render("search/menu.phtml")?>

<?php if( $this->searchGlossary->count() ): ?>
	<table class="datatable">
		<th><?=$this->translate("result")?></th>
	
		<?php foreach( $this->searchGlossary as $key => $val ): ?>
			<?php $class  = $this->changeClass( $this->searchGlossary->key() , array( "light_gray" , "white" ) );?>
			<tr class="<?=$class?>">
				<td nowrap="nowrap">
					<a href="#this" onclick="addElement('main' , 'glossary' , '<?=$this->url?>/glossary/glossary/index/q/<?=$val->word;?>')" ><?=$val->word;?></a>
				</td>
			</tr>  
		<?php endforeach;?>
	
	</table>
<?php else:?>
	<table class="datatable">
		<tr class="<?=$class?>">
			<td><?=$this->translate( "there are no records" );?></td>
		</tr>
	</table>
<?php endif;?>

<div class="clear"></div>