<?=$this->render("search/menu.phtml")?>
	
<?php if( $this->searchMultimedia->count() ): ?>
	<table class="datatable">
		<th><?=$this->translate("result")?></th>
	
		<?php foreach( $this->searchMultimedia as $key => $val ): ?>
			<?php $class  = $this->changeClass( $this->searchMultimedia->key() , array( "light_gray" , "white" ) );?>
			<tr class="<?=$class?>">
				<td nowrap="nowrap">
					<a href="#multimedia" onclick="runSearchView( 'multimedia' , 'multimedia/multimedia/list/id/<?php echo $val['galeria_id']; ?>/busca/<?php echo $this->string; ?>' );"><?php echo $val['galeria_titulo']; ?></a>
				</td>
			</tr>
		<?php endforeach;?>
	
	</table>
<?php else:?>
	<table class="datatable">
		<tr class="<?=$class?>">
			<td><?=$this->translate( "there are no records" );?></td>
		</tr>
	</table>
<?php endif;?>

<div class="clear"></div>