<?=$this->render("search/menu.phtml")?>
	
<?php if( $this->searchRss->count() ): ?>
	<table class="datatable">
		<th><?=$this->translate("result")?></th>
		
		<?php foreach( $this->searchRss as $val ): ?>
			<?php $class  = $this->changeClass( $this->searchRss->key() , array( "light_gray" , "white" ) );?>
			<tr class="<?=$class?>">
				<td nowrap="nowrap">	
					<a href="#this" onclick="addElement('main' , 'rss' , '<?=$this->url?>/rss/rss/view/id/<?=$val->id;?>')" ><?=$val->channel?></a>
				</td> 
			</tr>	 
		<?php endforeach;?>
	
	</table>
<?php else:?>
	<table class="datatable">
		<tr class="<?=$class?>">
			<td><?=$this->translate( "there are no records" );?></td>
		</tr>
	</table>
<?php endif;?>

<div class="clear"></div>
