<?=$this->render("search/menu.phtml")?>

<?php if( $this->paginator->count() ): ?>
	<table class="tablesorter">
        <thead>
            <tr>
                <th colspan="3"><?=$this->translate("result")?></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach( $this->paginator as $val ): ?>
                <tr class="<?=$this->changeClass( $key , array( "even" , "odd" ) )?>">
                    <td nowrap="nowrap">
                        <a href="#this" onclick="layout.addPanel( 'weblibrary-weblibrary' , '<?=$this->url?>/weblibrary/weblibrary/find/word/<?=$val->title;?>'); $('#search').remove();" ><?=$val->title?></a><br />
                    </td>
                    <td nowrap="nowrap">
                        <?=$val->author; ?>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
	</table>
    <?=$this->paginationControl($this->paginator, 'Sliding', 'search/pagination.phtml'); ?>
<?php else:?>
	<div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif;?>

<div class="clear"></div>
<script type="text/javascript">
    action = "<?=$this->type?>";
</script>