<div id="chat">
    <div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
        <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
            <span class="ui-dialog-title" id="ui-dialog-title-dialog">
                <h3><?=$this->translate('chat');?></h3>
            </span>
        </div>
        <div class="ui-dialog-content ui-widget-content">
            <ul>
                <?php foreach($this->chatRs as $rs): ?>
                    <li>
                        <?php echo $rs->name;?>
                        <input type="hidden" name="id" value="<?php echo $rs->id;?>" />
                    </li>
                <?php endforeach?>
            </ul>
        </div>
    </div>
    <div class="dialogs">
        
    </div>
</div>
<script>
    Chat.init('chatloader/index.php?id=<?php echo $this->user->person_id?>','chat');
</script>