<script>
    var layout = new Preceptor.widget.Layout();
</script>
<div class="menu">
    <?php echo $this->action('menu', 'discipline')?>
</div>
<div class="column">
    <div class="search ui-dialog ui-widget ui-widget-content ui-corner-all">
        <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
            <form name="formSearch" id="formSearch" action="#">
                <input id="sbusca" accesskey="b" tabindex="1" title="Busca" name="q" class="select" type="text" />
            </form>

            <a class="content-icon content-search" href="#">
                <span class="ui-icon ui-icon-search">search</span>
            </a>
        </div>
    </div>

    <?php echo $this->action('chat', 'discipline')?>
</div>
<div id="main">
    <div id="box-main"></div>
    <?=$this->action( 'index' , 'content' , 'content' ); ?>
</div>
<script type="text/javascript">
    $("#formSearch").submit( function( ev ){
        runElementMeio( '<?=$this->url;?>/search/search/glossary/string/' + $('#sbusca').val() , 'search'  );
        $('#sbusca').empty();
        return false;
    });

    $( ".content-search" ).click( function(){
        $( "#formSearch" ).trigger( "submit" );
    });
</script>
