<div id="drag" style="cursor: move;display: block;width: 99%">
	<h3 style="float: left;"></h3>
	<a style="float: right;color: black;text-decoration: underline;" href="#focus" onclick="Lightbox.destroy( 'groupList' , '/course/input/id/<?=$this->course_id?>/discipline/true' )">X</a>
	<div style="clear: both;"></div>
</div>

<div id="update_div">
	<?php if( $this->getPermission( "input" ) ): ?>
	<div class="light_gray padding">
		<form action="#" id="formDiscipline">
			<?=$this->formHidden( "id" , $this->data->id )?>
			<?=$this->formHidden( "course_id" , $this->course_id )?>
			
			<label><?=$this->translate("title")?></label>
			<?=$this->formText( "title" , $this->data->title )?>
			
			<br /><br />
			
			<?=$this->formSubmit( "SAVE" , $this->translate("save") )?>
		</form>
	</div>
	
	<br /><br />
	<?php endif?>
	
	<div>
		<?php if( $this->rs->count() ):?>
			<table class="datatable">
				<tr>
					<th><?=$this->translate("title")?></th>
					<th><?=$this->translate("created")?></th>
					<th></th>
				</tr>
				<?php foreach( $this->rs as $rs ): ?>
					<?php $class  = $this->changeClass( $this->rs->key() , array( "light_gray" , "white" ) );?>
					<?php if( $this->getPermission( "input" ) ): ?>
						<?php $edit   = $this->ajax( $this->translate("edit") , 'category' , $this->url . '/discipline/list/id/'. $rs->id . '/courseId/' . $this->course_id ); ?>
					<?php endif?>
					
					<?php if( $this->getPermission( "delete" ) ): ?>
						<?php $delete = $this->ajax( $this->translate("delete") , 'category' , $this->url . '/discipline/delete/id/' . $rs->id , 1 , $this->translate("want to delete?") );?>
					<?php endif?>
					
					<tr class="<?=$class?>">
						<td><?=$rs->title?></td>
						<td width="70" nowrap="nowrap"><?=$this->date( $rs->created )?></td>
						<td width="95" nowrap="nowrap"><?=$edit ." &nbsp; ". $delete?></td>
					</tr>
				<?php endforeach; ?>
			</table>
		<?php else : ?>
			<?=$this->translate( "there are no records" );?>
		<?php endif;?>
	</div>
</div>
<script type="text/javascript">
	var DisciplineValidate = new Preceptor.util.Validate();

	DisciplineValidate.addValidate( 'title' , DisciplineValidate.stringLength	, <?=Zend_Json::encode( array ( 'stringLength' => $this->translate("maxlength") ) )?>  ,<?=Zend_Json::encode( array ( 'stringLength' , 0 , 255 ) )?> , 'stringLength' );
	DisciplineValidate.addValidate( 'title' , DisciplineValidate.notEmpty 		, <?=Zend_Json::encode( array ( 'notEmpty' => $this->translate("required field") ) )?> , null , 'notEmpty' );

	YAHOO.util.Event.on( 'formDiscipline' , 'submit' , function( ev ){
		if( DisciplineValidate.verify( this ) )
		{
			new Preceptor.util.AjaxUpdate( 'category' , '<?=$this->url?>/discipline/save' , { formId: "formDiscipline" });
		}
		YAHOO.util.Event.stopEvent( ev );
	});
</script>

