<?php if( $this->verifyRegister ):?>
    <div class="right">
        <?=$this->ajax( $this->translate('back') , "default-course" , "$this->url/course/index/" , 2 , null )?>
    </div>
    <h2 class="left"><?=$this->translate("course")?>: <?=$this->discipline->name; ?></h2>
    <div class="clear">&nbsp;</div>
    <?php if( $this->groups->count() ):?>
        <?=$this->translate("choose a class")?>:
        <form id="class-register" method="post" action="#">
            <table class="tablesorter">
                <thead>
                    <tr>
                        <th style="width: 22px"></th>
                        <th><?=$this->translate( "group" )?></th>
                        <th><?=$this->translate( "students" )?></th>
                        <th><?=$this->translate( "initiation" )?></th>
                        <th><?=$this->translate( "finish" )?></th>
                    </tr>

                </thead>

                <tbody>

                    <?php foreach( $this->groups as $key => $group ): ?>

                    <tr class="<?=$this->changeClass( $key , array( "even" , "odd" ) )?>">
                        <td><input type="radio" name="class_id" value="<?=$group->id?>" id="class-<?=$group->id?>" /></td>
                        <td><label for="class-<?=$group->id?>"><?=$group->name?></label></td>
                        <td><?=$group->findDependentRowset( "Station_Model_ClassPerson" )->count()?></td>
                        <td><?=$this->date( $group->initially )?></td>
                        <td><?=$this->date( $group->finish )?></td>
                    </tr>

                    <?php endforeach?>

                </tbody>
            </table>

            <div>
                <label for="promotion" class="inline"><?=$this->translate('enter the code if the PPS')?></label>
                <?=$this->formText( "promotion" , null , array( "style" => "width: 90px; text-transform: uppercase;" ) )?>
                <script type="text/javascript">
                    $( "#promotion" ).mask( "******" );
                </script>
            </div>

            <br />
            <br />
            
            <input type="submit" value="<?=$this->translate('save')?>" />
        </form>
    <?php else:?>
        <div class="message-table-sorter"><?=$this->translate( "there is no class available" ) ?></div>
    <?php endif?>
<?php else:?>
    <div class="right">
        <a href="<?=$this->url?>/index"><?=$this->translate( "back" )?></a>
    </div>
    <div class="clear"></div>
    <div class="message-table-sorter"><?=$this->translate( "you are already registered in this course!" ) ?></div>
<?php endif?>
<div class="clear">&nbsp;</div>

<script type="text/javascript">
    $( "#class-register" ).submit( function(){
        var validate = false;

        $( "#class-register input:radio" ).each( function(){
            if( this.checked ){
                validate = true;
            }
        });

        if( validate ){
            new Preceptor.util.AjaxUpdate( "default-course" , "<?=$this->url?>/person/register-class" , {formId: this.id} );
        }else{
            alert( "<?=$this->translate("choose a class")?>" );
        }

        return false;
    });
</script>