<div class="forum">
    <h3><?php echo $this->parent->title?></h3>
    <table class="datatable">
        <?php if ($this->page == 1):?>
            <?php $table = new Tri_Db_Table('user');?>
            <?php $user = $table->fetchRow(array('id = ?' => $this->parent->user_id));?>
            <tr>
                <td width="60" valign="top" align="center">
                    <img alt="<?php echo $user->name ?>" src="upload/<?php echo $this->thumbnail($user->image, 'small') ?>" /><br />
                </td>
                <td>
                    <span class="name"><?php echo $user->name;?></span><br />
                    <?php echo $this->parent->description?>
                </td>
            </tr>
            <tr>
                <td colspan="3" class="message-reply">
                    <?php echo $this->date($this->parent->created, true)?>
                </td>
            </tr>
        <?php endif;?>
        <?php $identity = Zend_Auth::getInstance()->getIdentity()?>
        <?php if (count($this->data)):?>
            <?php foreach ($this->data as $key => $data): ?>
                <tr>
                    <td width="60" valign="top" align="center">
                        <img alt="<?php echo $data->name ?>" src="upload/<?php echo $this->thumbnail($data->image, 'small') ?>" /><br />
                        <?php
                            if ($this->parent->status == 'active') {
                                if ($this->isAllowed('form') && $identity->id == $data->user_id) {
                                    echo $this->ajax("edit", 'forum/reply/form/id/'. $data->id, 2);
                                }

                                if (($this->isAllowed('delete') && $identity->id == $data->user_id) || $identity->role != 'student') {
                                    echo $this->ajax("delete", 'forum/reply/delete/id/' . $data->id . '/forumId/' . $data->forum_id, 2 , "want to delete?");
                                }
                            }
                        ?>
                    </td>
                    <td>
                        <span class="name">
                            <?php echo $data->name;?>
                            <?php if ($data->role != 'student'):?>
                                (<?php echo $this->translate($data->role)?>)
                            <?php endif;?>
                        </span><br />
                        <?php echo nl2br($data->description);?>
                    </td>
                </tr>
                <tr>
                    <td colspan="3" class="message-reply">
                        <?php echo $this->date($data->created, true)?>
                    </td>
                </tr>
            <?php endforeach;?>
        <?php endif;?>
        <?php if ($this->parent->status == 'active'):?>
            <tr>
                <td width="60" valign="top" align="center">
                    <img alt="<?php echo $identity->name ?>" src="upload/<?php echo $this->thumbnail($identity->image, 'small') ?>" /><br />
                    <?php echo $identity->name?><br />
                </td>
                <td><div class="forumReply"><?php echo $this->form?></div></td>
            </tr>
        <?php endif;?>
    </table>
    <div id="forum-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
</div>
<script type="text/javascript">
    $('#forum-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $(".forumReply form").submit(function() {
        var $this = $(this);
		$.post('forum/reply/save', $(this).serialize(), function(data){
            $this.parents('.content').html(data);
        });
        return false;
	});

    $('input[type=button]').button();
</script>