<?php if( $this->getPermission( "input" ) ): ?>
    <div class="right"><?=$this->ajax( $this->translate( "new") , "dictionary-dictionary" , $this->url . "/dictionary/dictionary/input" , 2 ); ?></div>
<?php endif ?>
<div class="clear"></div>
<br />
<?php if( $this->rs->count() ): ?>
	<table class="tablesorter">
        <thead>
            <tr>
                <th><?=$this->translate("links")?></th>
                <th><?=$this->translate("description")?></th>
                <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                    <th></th>
                <?php endif;?>
            </tr>
        </thead>
        <tbody>
	<?php foreach( $this->rs as $rs ):?>
		<?php $edit	   = "" ?>
		<?php $delete  = "" ?>

		<?php $content = "<a href='http://{$rs->url}' target='_blank'>{$rs->title}</a>"?>
		<?php $class   = $this->changeClass( $this->rs->key() , array( "even" , "odd" ) );?>

		<?php if( $this->getPermission( "input" ) ): ?>
			<?php $edit = $this->ajax( $this->translate("edit") , "dictionary-dictionary" , $this->url . "/dictionary/dictionary/input/id/" . $rs->id ); ?>
		<?php endif; ?>

		<?php if( $this->getPermission( "delete" ) ): ?>
			<?php $delete = $this->ajax( $this->translate("delete") , "dictionary-dictionary" , $this->url . "/dictionary/dictionary/delete/id/" . $rs->id , 1 , $this->translate( "want to delete?" ) ); ?>
		<?php endif; ?>

		<tr class="<?=$class?>">
			<td nowrap="nowrap"><?=$content;?></td>
			<td><?=$rs->ds?></td>
			<?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
				<td nowrap="nowrap" width="77"><?=$edit . " " . $delete?></td>
			<?php endif;?>
		</tr>
	<?php endforeach;?>
        </tbody>
	</table>
<?php else: ?>
	<div class="clear">&nbsp;</div>
   <div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif; ?>
