<form action="#" id="formGroup_<?=$this->suffix?>">

	<?=$this->formHidden( "discipline_id" , $this->data->discipline_id , array( "id" => "discipline_id_{$this->suffix}" ) );?>
	<?=$this->formHidden( "course_id" , $this->course_id );?>
	<?=$this->formHidden( "id" , $this->data->id , array( "id" => "id_{$this->suffix}" ) );?>
	
	<label for="title_<?=$this->suffix?>"><?=$this->translate( "title" )?></label>
	<?=$this->formText( "title" , $this->data->title , array( "id" => "title_{$this->suffix}" , "class" => "input-medium" ) );?>
	
	<br /><br />
	
	<div id="groupList">
		<table width="100%" style="margin: 0;">
			<tr>
				<td width="378"><?=$this->translate( "not registered" );?>:</td>
				<td><?=$this->translate( "registered" );?>:</td>
			</tr>
		</table>
		<?=$this->groupedListGroup( "groupall" , $this->all , "groupchecked" , $this->checked );?>
	</div>
	
	<label for="turma_status"><?=$this->translate( "status" )?>:</label>
	<?=$this->formSelect( "status" , $this->data->status , array( "id" => "status_{$this->suffix}" ) , $this->status );?>
	
	<br /><br />
	
	<?=$this->formSubmit( "submitGroup" , $this->translate( "save" ) );?>
</form>

<script>
	Preceptor.util.Validate.prototype.onsubmit = function(){ 
		YAHOO.util.Event.on( 'formGroup_<?=$this->suffix?>' , 'submit' , function( ev ){
			
			GroupedList_group_groupall.selectAll( 'groupchecked' );
			
			if( this.verify( $( 'formGroup_<?=$this->suffix?>' ) ) )
			{
				new Preceptor.util.AjaxUpdate( this.div , this.url , { formId: this.formId } );
			}
			
			YAHOO.util.Event.stopEvent( ev );
			
		} , this , true );
	}
</script>
<?=$this->validate( "formGroup_{$this->suffix}" , $this->jsonValidate , $this->suffix , $this->url . "/group/save/" , "group"  ); ?>