<div>
	<?php if( $this->rs->count() ):?>
		<table class="datatable">
			<tr>
				<th>&nbsp;</th>
			</tr>
            
			<?php foreach( $this->rs as $rs ): ?>
				<?php //$class  = $this->changeClass( $this->rs->key() , array( "light_gray" , "white" ) );?>
				
				<tr class="group-list">
					<td>
                        <h2><?=$rs->title?></h2>
                        <?php $disciplines = $rs->findDisciplineViaCourseDiscipline();?>
                        <ul>
                            <?php foreach( $disciplines as $discipline ):?>
                                <li>
                                    <?php if( $this->getPermission( "input" ) ): ?>
                                        <div class="right"><?php echo $this->ajax( $this->translate("group new") , "group" , $this->url . "/group/input/discipline_id/".$discipline->id , 2 ); ?></div>
                                    <?php endif; ?>
                                    
                                    <h3><?=$discipline->title?></h3>
                                    <?php $groups = $discipline->findGroup( $discipline->getTable()->select()->order( 'title' ) );?>
                                    <ul>
                                        <?php foreach( $groups as $group ):?>
                                            <?php if( $this->getPermission( "input" ) ): ?>
                                                <?php $edit = $this->ajax( $this->translate("edit") , 'group' , $this->url . '/group/input/course_id/'.$rs->id.'/discipline_id/'.$discipline->id.'/id/'. $group->id ); ?>
                                            <?php endif; ?>

                                            <?php if( $this->getPermission( "delete" ) ): ?>
                                                <?php $delete = $this->ajax( $this->translate("delete") , 'group' , $this->url . '/group/delete/discipline_id/'.$discipline->id.'/id/' . $group->id , 1 , $this->translate("want to delete?") );?>
                                            <?php endif; ?>
                                            <li>
                                                <label><?=$group->title?></label>
                                                <?=$edit?> <?=$delete?>
                                            </li>
                                        <?php endforeach;?>
                                    </ul>
                                </li>
                            <?php endforeach;?>
                        </ul>
                    </td>
				</tr>
			<?php endforeach; ?>
		</table>
	<?php else : ?>
		<?=$this->translate( "there are no records" );?>
	<?php endif;?>
</div>