<?php if( $this->getPermission( "input" ) ): ?>
	<div class="right"><?=$this->ajax( $this->translate( "new" ) , 'weblibrary' , $this->url . '/weblibrary/weblibrary/input/' , 2 ); ?></div>
<?php endif; ?>

<form action="#" id="weblibrary">
    <?=$this->render( "weblibrary/menu.phtml" ); ?>
    <div class="clear"></div>
</form>

<br/>
<h3><?=$this->translate( "result" )?>:</h3>
	<?php if( $this->rs->count() ): ?>
		<table class="tablesorter">
            <thead>
                <tr>
                    <th class="title"><?=$this->translate("title")?></th>
                    <th class="author"><?=$this->translate("author")?></th>
                    <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                            <th></th>
                    <?php endif;?>
                </tr>
            </thead>

				<?php foreach( $this->rs as $key => $file ): ?>
					<?php if( $this->getPermission( "input" ) ): ?>
						<?php $edit = $this->ajax( $this->translate("edit") , 'weblibrary-weblibrary' , "{$this->url}/weblibrary/weblibrary/input/id/" . $file->id); ?>
					<?php endif;?>

					<?php if( $this->getPermission( "delete" ) ): ?>
						<?php $delete = $this->ajax( $this->translate("delete") , 'weblibrary-weblibrary' , "{$this->url}/weblibrary/weblibrary/delete/id/" . $file->id , 1 , $this->translate("want to delete?") );?>
					<?php endif;?>

					<tr class="<?=$this->changeClass( $key , array( "even" , "odd" ) )?>">
						<td nowrap="nowrap" width="30%">
							<a target="_blank" href="<?=$this->url?>/file/file/download/file/<?=base64_encode( $file->location ); ?>"><strong><?=$file->title; ?></strong></a>
						</td>

						<td>
							<?=$file->author; ?>
						</td>

						<?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
							<td nowrap="nowrap" width="77"><?=$edit . " " . $delete?></td>
						<?php endif;?>
					</tr>
				<?php endforeach;?>
				</table>
	<?php else:?>
		<table class="datatable">
			<tr class="<?=$class?>">
				<td><?=$this->translate( "there are no records" );?></td>
			</tr>
		</table>
	<?php endif;?>

<div class="clear"></div>
<?php //if( $this->user->profileId != 1 ):?>
	<?//=$this->render( "input.tpl" )?>
<?php // endif; ?>