<?php if( $this->getPermission( "input" ) ): ?>
	<div class="right"><?=$this->ajax( $this->translate( "new" ) , 'weblibrary-weblibrary' , $this->url . '/weblibrary/weblibrary/input/' , 2 ); ?></div>
<?php endif; ?>

<div >
	<form action="#" id="weblibraryQWeblibrary">
		<?=$this->render( "weblibrary/menu.phtml" ); ?>
		<div class="clear"></div>
	</form>
</div>

<?php if( $this->rs->count() ): ?>
	<table class="tablesorter">
        <thead>
            <tr>
                <th class="title"><?=$this->translate("title")?></th>
                <th class="author"><?=$this->translate("author")?></th>
                <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                        <th></th>
                <?php endif;?>
            </tr>
        </thead>

        <tbody>
			<?php foreach( $this->rs as $key => $file ): ?>
				<?php $class  = $this->changeClass( $this->rs->key() , array( "even" , "odd" ) );?>

				<?php if( $this->getPermission( "input" ) ): ?>
					<?php $edit = $this->ajax( $this->translate("edit") , 'weblibrary-weblibrary' , "{$this->url}/weblibrary/weblibrary/input/id/" . $file->id); ?>
				<?php endif;?>

				<?php if( $this->getPermission( "delete" ) ): ?>
					<?php $delete = $this->ajax( $this->translate("delete") , 'weblibrary-weblibrary' , "{$this->url}/weblibrary/weblibrary/delete/id/" . $file->id , 1 , $this->translate("want to delete?") );?>
				<?php endif;?>

				<tr class="<?=$class?>">
					<td nowrap="nowrap" width="30%">
						<a target="_blank" href="<?=$this->url?>/file/file/download/file/<?=base64_encode( $file->location ); ?>"><strong><?=$file->title; ?></strong></a>
					</td>

					<td>
						<?=$file->author; ?>
					</td>

					<?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
						<td nowrap="nowrap" width="77"><?=$edit . " " . $delete?></td>
					<?php endif;?>
				</tr>
			<?php endforeach;?>
        </tbody>
    </table>
		<?php else:?>
           <div class="clear">&nbsp;</div>
           <div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
		<?php endif;?>
	
<div class="clear"></div>
