<?=$this->element()->startForm();?>
<div id="div-form-<?=$this->model?>">
    <?php
        echo $this->element()
				  ->formHidden( "id" , null , array( "printLabel" => false ) )
                  ->formHidden( "file_id" , null , array( "printLabel" => false ) );

   ?>
   <input type="radio" id="WB-type" name="type" value="WB"/> <label for="WB-type" class="inline"><?=$this->translate("file")?></label>
   <input type="radio" id="WL-type" name="type" value="WL"/> <label for="WL-type" class="inline"><?=$this->translate("links")?></label>
   <br />
   <div id="input-file">
        <?php
             if( !isset($this->data->id) ){
                echo $this->element()->formFile( "file" );
            }
        ?>
   </div>

   <div id="input-link" style="display: none;">
        <?php
            echo $this->element()->formText( "link" , null , array( 'label' => $this->translate("URL") ) );
        ?>
   </div>

   <?php
        echo $this->element()
				  ->formText( "title" )
                  ->formText( "author" , null , array( 'style' => "width: 300px;" ) )
				  ->formSubmit( "model" , $this->translate("save") , array( "printLabel" => false ) );
    ?>
    <div class="clear"></div>
</div>
<?=$this->formRelation( $this->data->id , array( "isUpload" => true ) )?>
<script type="text/javascript">
    $( "#WB-type" ).click( function(){
       $( "#input-file" ).show();
       $( "#input-link" ).hide();
    });
    
    $( "#WL-type" ).click( function(){
       $( "#input-link" ).show();
       $( "#input-file" ).hide();
    });
</script>