<ul>
	<?php foreach( $this->rs as $rs ):?>
		<li>
			<?=$this->image( "icones/chat_status_" . $rs['status'] . ".gif" )?>
			
			<a href="#open" onclick="Chat.open( '<?=$rs['status']?>' , <?=$rs['personid']?> );"><?=$this->translate( $rs['acname'] )?> - <?=$this->shortName( $rs['name'] )?></a>
			
			<div id="chat-users-list-<?=$rs['personid']?>" style="display: none;">
				<img src="<?=$this->url?>/upload/thumb_small<?=$rs['location']?>" />
				<span><?=$this->translate( $rs['acname'] )?> - <?=$this->shortName( $rs['name'] )?></span>
			</div>
		</li>
	<?php endforeach ?>
</ul>
<script>
	Chat.load( '<?=$this->messages?>' );
</script>