<div id="chat-list" class="ui-accordion ui-widget ui-helper-reset">
	<h3 class="ui-accordion-header ui-helper-reset ui-state-active ui-corner-top">
		<a href="#"><?=$this->translate("chat")?></a>
	</h3>
	<div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom ui-accordion-content-active" >
		<ul>
			<?php foreach( $this->rs as $rs ):?>
				<li>
					<?=$this->image( "icones/chat_status_" . $rs['status'] . ".gif" )?>

					<a href="#open" onclick="Chat.open( '<?=$rs['status']?>' , <?=$rs['personid']?> );"><?=$this->shortName( $rs['name'] )?></a>

					<div id="chat-users-list-<?=$rs['personid']?>" style="display: none;">
						<img src="<?=$this->url?>/upload/thumb_small<?=$rs['location']?>" />
						<span><?=$this->shortName( $rs['name'] )?></span>
					</div>
				</li>
			<?php endforeach ?>
		</ul>
	</div>
</div>
<script>
	Chat.load( '<?=$this->messages?>' );
</script>