<div class="chat-footer">
	<form action="#" id="chat-message-form-<?=$this->rs->id?>">
		<input type="hidden" value="<?=$this->rs->id?>" name="person_id" />
		<textarea id="chat-message-text-<?=$this->rs->id?>" name="ds"></textarea>
		<input type="submit" value="<?=$this->translate( "send" )?>">
	</form>
</div>
<div class="clear"></div>
<script>
YAHOO.util.Event.onDOMReady( function(){
	YAHOO.util.Event.on( "chat-message-text-<?=$this->rs->id?>" , "keypress" , function( ev ){
		var key = YAHOO.util.Event.getCharCode( ev );
		
		if( key == 13 )
		{
			YAHOO.util.Event.stopEvent( ev );
			Chat.submit( <?=$this->rs->id?> , "<?=$this->translate("write a message")?>" );
		}
	});
	
	YAHOO.util.Event.on( "chat-message-form-<?=$this->rs->id?>" , "submit" , function( ev ){
		YAHOO.util.Event.stopEvent( ev );
		Chat.submit( <?=$this->rs->id?> , "<?=$this->translate("write a message")?>" );
	});
});
</script>