<?php if( $this->getPermission( "input" ) ): ?>
	<div style="text-align: right;">
		<?php echo $this->ajax( $this->translate("new") , "activity" , "/activity/group/input/" , 2 ); ?>
	</div>
	<br />
<?php endif;?>

<div>
	<?php if( $this->rs->count() ):?>
		<table class="datatable">
			<tr>
				<th><?=$this->translate("name")?></th>
				<?php if( $this->getPermission( "input" ) ): ?>
					<th></th>
				<?php endif; ?>
			</tr>
			<?php foreach( $this->rs as $rs ): ?>
				<?php $class  = $this->changeClass( $this->rs->key() , array( "light_gray" , "white" ) );?>
				
				<?php if( $this->getPermission( "input" ) ): ?>
					<?php $edit = $this->ajax( $this->translate("edit") , 'activity' , '/activity/group/input/id/'. $rs->id ); ?>
				<?php endif; ?>
				
				<?php if( $this->getPermission( "delete" ) ): ?>
					<?php $delete = $this->ajax( $this->translate("delete") , 'activity' , '/activity/group/delete/id/' . $rs->id , 1 , $this->translate("want to delete?") );?>
				<?php endif; ?>
				
				<tr class="<?=$class?>">
					<td><?=$rs->title?></td>
					<?php if( $this->getPermission( "input" ) ): ?>
						<td width="95" nowrap="nowrap"><?=$edit?></td>
					<?php endif; ?>
				</tr>
			<?php endforeach; ?>
		</table>
	<?php else : ?>
		<?=$this->translate( "there are no records" );?>
	<?php endif;?>
</div>