<?php if( $this->getPermission( "input" ) ): ?>
	<div style="text-align: right;">
		<?php echo $this->ajax( $this->translate("new") , "activity-activity" , $this->url . "/activity/group/input/" , 2 ); ?>
	</div>
	<br />
<?php endif;?>

<div>
	<?php if( $this->rs->count() ):?>
		<table class="tablesorter">
            <thead>
                <tr>
                    <th><?=$this->translate("name")?></th>
                    <?php if( $this->getPermission( "input" ) ): ?>
                        <th></th>
                    <?php endif; ?>
                </tr>
            </thead>

            <tbody>
                <?php foreach( $this->rs as $key => $rs ): ?>
                    <?php if( $this->getPermission( "input" ) ): ?>
                        <?php $edit = $this->ajax( $this->translate("edit") , 'activity-activity' , $this->url . '/activity/group/input/id/'. $rs->id ); ?>
                    <?php endif; ?>

                    <?php if( $this->getPermission( "delete" ) ): ?>
                        <?php $delete = $this->ajax( $this->translate("delete") , 'activity-activity' , $this->url . '/activity/group/delete/id/' . $rs->id , 1 , $this->translate("want to delete?") );?>
                    <?php endif; ?>

                    <tr class="<?=$this->changeClass( $key , array( "even" , "odd" ) )?>">
                        <td><?=$rs->title?></td>
                        <?php if( $this->getPermission( "input" ) ): ?>
                            <td width="95" nowrap="nowrap"><?=$edit?></td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
		</table>
	<?php else : ?>
		<div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
	<?php endif;?>
</div>