<?=$this->render("filter.tpl")?>

<form action="#" id="formActivityGroup_<?=$this->suffix?>">

	<?=$this->formHidden( "id" , $this->data->id , array( "id" => "id_{$this->suffix}" ) );?>

	<label for="title_<?=$this->suffix?>"><?=$this->translate( "title" )?></label>
	<?=$this->formText( "title" , $this->data->title , array( "id" => "title_{$this->suffix}" , "class" => "input-medium" ) );?>
	
	<br /><br />
	
	<div id="list_person_activity">
		<table width="100%" style="margin: 0;">
			<tr>
				<td width="378"><?=$this->translate( "students" )?>:</td>
				<td></td>
			</tr>
		</table>
		<?=$this->groupedList( "activitygroup_all" , $this->all , "activitygroupchecked" , $this->checked , array( 'height' => '150px' , 'width' => '239px' , 'width_text' => '235px' ) );?>
	</div>
	
	<br />
	
	<?=$this->formSubmit( "submitGroup" , $this->translate( "save" ) );?>
</form>
	
<script>	
	
	Preceptor.util.Validate.prototype.onsubmit = function(){ 
		YAHOO.util.Event.on( 'formActivityGroup_<?=$this->suffix?>' , 'submit' , function( ev ){
			
			GroupedList_group_activitygroup_all.selectAll( 'activitygroupchecked' );
			
			if( this.verify( $( 'formActivityGroup_<?=$this->suffix?>' ) ) )
			{
				new Preceptor.util.AjaxUpdate( this.div , this.url , { formId: this.formId } );
			}
			
			YAHOO.util.Event.stopEvent( ev );
			
		} , this , true );
	}
	
</script>
<?=$this->validate( "formActivityGroup_{$this->suffix}" , $this->jsonValidate , $this->suffix , "/activity/group/save/" , "activity"  ); ?>
