<?php $this->suffix = $this->controller ?>
<div id="edit">
	<form id="formPeriod_<?=$this->suffix?>">
		<?=$this->formHidden( "id" , $this->data->id )?>

		<label for="entered_<?=$this->suffix?>"><?=$this->translate("date init")?>:</label>
		<?=$this->formText( "entered" , $this->data->entered , array( "id" => "entered_" . $this->suffix ) )?>
		
		<label for="expired_<?=$this->suffix?>"><?=$this->translate("date expired")?>:</label>
		<?=$this->formText( "expired" , $this->data->expired , array( "id" => "expired_" . $this->suffix ) )?>

		<br /><br />
		
		<input type="submit" value="<?=$this->translate("save")?>" />
		<div class="clear"></div>
	</form>	
</div>
<script>
	
	new Preceptor.util.Mask( "entered_<?=$this->suffix ?>" , {mask:'00/00/0000'} )
	new Preceptor.util.Mask( "expired_<?=$this->suffix ?>" , {mask:'00/00/0000'} )
	
	Preceptor.util.Validate.prototype.onsubmit = function(){ 
		YAHOO.util.Event.on( 'formPeriod_<?=$this->suffix?>' , 'submit' , function( ev ){
			
			if( this.verify( $( 'formPeriod_<?=$this->suffix?>' ) ) )
			{
				new Preceptor.util.AjaxUpdate( this.div , this.url , { formId: this.formId } );
			}
			
			YAHOO.util.Event.stopEvent( ev );
			
		} , this , true );
	}
</script>
<?=$this->validate( "formPeriod_{$this->suffix}" , $this->jsonValidate , $this->suffix , "/period/period/save/" , "category"  ); ?>