<p>
    <?=$this->formSelect( "content-public" , null , array( 'style' => 'margin-right: 10px;' ) , $this->contents )?>
    <input type="button" id="add-public" value="<?=$this->translate( 'add' )?>" />
</p>

<div class="clear">&nbsp;</div>

<?php if( isset( $this->rs ) && $this->rs->count() ):?>
    <table class="tablesorter">
        <thead>
            <tr>
                <th><?=$this->translate( "content" )?></th>
                <?php if( $this->getPermission( array( "module" => "public" , "controller" => "public" , "action" => "delete"  ) ) ):?>
                    <th style="width: 42px;"></th>
                <?php endif;?>
            </tr>
        </thead>
            
        <tbody>
            <?php foreach( $this->rs as $key => $rs ):?>
            <tr class="<?=$this->changeClass( $key , array( "even" , "odd" ) )?>">

                <?php if( isset( $rs->content_id ) && $rs->content_id ):?>
                    <td><?=$rs->findParentRow( "Content_Model_Content" )->title." ---- ".$rs->title?></td>
                <?php else:?>
                    <td><?=$rs->title?></td>
                <?php endif;?>
                
               <?php if( $this->getPermission( array( "module" => "public" , "controller" => "public" , "action" => "delete"  ) ) ):?>
                <td>
                    <a href="#this" id="<?=$rs->id?>-delete" title="<?=$this->translate( 'delete' )?>" style="width: 17px; display: block;">
                        <?=$this->translate( 'retire' )?>
                    </a>
                    <script type="text/javascript">
                        $( "#<?=$rs->id?>-delete" ).click( function(){
                            if( confirm( '<?=$this->translate( "want to delete?" )?>' ) ){
                                new Preceptor.util.AjaxUpdate( "public-public" , "<?=$this->url?>/public/public/delete/content_id/<?=$rs->id?>" );
                            }
                        });
                    </script>
                </td>
                <?php endif;?>
                
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
<?php else:?>
    <div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif;?>

<script type="text/javascript">
    /**
     * verify if the item selected has value,
     * if have, the button of save is enabled
     */
    $( "#content-public" ).change( function(){
        if( this.value > 0 ){
            $( "#add-public" ).removeAttr( "disabled" ).removeAttr( "style" );
        }else{
            $( "#add-public" )
            .attr( "disabled" , "disabled" )
            .css( { "background" : "#CCC" , "color" : "#AAA" , "border" : "none" } );
        }
    });

    /**
     * disables the button and change color
     */
    $( "#add-public" )
            .attr( "disabled" , "disabled" )
            .css( { "background" : "#CCC" , "color" : "#AAA" , "border" : "none" } );


    /**
     * update of the content for access public
     */
    $( "#add-public" ).click( function(){
        new Preceptor.util.AjaxUpdate( "public-public" , "<?=$this->url?>/public/public/save/content_id/" + $( "#content-public" ).val() )
    });
</script>