<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="en">
	<head>
		<title>Trilhas - Preceptor Educação a Distância</title>
		<meta http-equiv="Content-Type" content="text/html; charset=<?=APP_CHARSET?>"/>

        <?=$this->headLink()->appendStylesheet( URL_JAVASCRIPT_LIBRARY . "yahoo/fonts/fonts-min.css" )
							->appendStylesheet( URL_JAVASCRIPT_LIBRARY . "yahoo/calendar/assets/calendar.css" )
							->appendStylesheet( URL_JAVASCRIPT_LIBRARY . "yahoo/button/assets/skins/sam/button.css" )
							->appendStylesheet( URL_JAVASCRIPT_LIBRARY . "yahoo/container/assets/skins/sam/container.css" )
							->appendStylesheet( URL_JAVASCRIPT_LIBRARY . "yahoo/editor/assets/skins/sam/editor.css" )
                            ->appendStylesheet( URL_JAVASCRIPT_LIBRARY . "preceptor/treeview/assets/tree.css" )
                            ->appendStylesheet( URL_JAVASCRIPT_LIBRARY . "preceptor/organizer/assets/organizer.css" )
                            ->appendStylesheet( URL_JAVASCRIPT_LIBRARY . "jquery/tooltip/jquery.tooltip.css" )
							->appendStylesheet( URL_JAVASCRIPT_LIBRARY . "jquery/themes/".$this->theme."/jquery-ui.css" )
                            ->appendStylesheet( URL_JAVASCRIPT_LIBRARY . "jquery/tablesorter/themes/blue/style.css" )
							->appendStylesheet( $this->url . "/css/themes/".$this->theme."/main.css" )
							->appendStylesheet( $this->url . "/css/themes/".$this->theme."/modules.css" )
							->appendStylesheet( $this->url . "/css/navigation.css" )
							->appendStylesheet( $this->url . "/css/editor.css" )
							->appendStylesheet( $this->url . "/css/utils.css" ); ?>

		<?=$this->headScript()->appendFile( URL_JAVASCRIPT_LIBRARY . "yahoo/yahoo-dom-event/yahoo-dom-event.js" )
                              ->appendFile( URL_JAVASCRIPT_LIBRARY . "yahoo/dragdrop/dragdrop-min.js" )
			                  ->appendFile( URL_JAVASCRIPT_LIBRARY . "yahoo/element/element-beta.js" )
				              ->appendFile( URL_JAVASCRIPT_LIBRARY . "yahoo/container/container_core-min.js" )
				              ->appendFile( URL_JAVASCRIPT_LIBRARY . "yahoo/animation/animation-min.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "yahoo/calendar/calendar-min.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "yahoo/connection/connection-min.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "yahoo/json/json-min.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "yahoo/treeview/treeview-min.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "yahoo/menu/menu-min.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "yahoo/editor/editor-min.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/preceptor.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/layout/layout.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/ajax/ajax.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/treeview/tasknode.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/rules/mask.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/rules/validate.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/validate/validate.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/validate/mask.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/validate/brazilian_patterns.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/validate/date.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/validate/number.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/validate/string.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/toggle/toggle.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "preceptor/dom/dom.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "jquery/jquery.js" )
							  ->appendFile( URL_JAVASCRIPT_LIBRARY . "jquery/jquery-ui-all.js" )
							  ->appendFile( $this->url . "/js/chat.js" )
							  ->appendFile( $this->url . "/js/relation.js" )
							  ->appendFile( $this->url . "/js/action.js" )
							  ->appendFile( $this->url . "/js/run.js" )
							  ->appendFile( $this->url . "/js/string.js" )
							  ->appendFile( $this->url . "/js/navigation.js" )
							  ->appendFile( $this->url . "/js/editor.js" ); ?>

		<script type="text/javascript">var URL = "<?=$this->url?>";</script>
	</head>

	<body class="yui-skin-sam">
		<div class="bar">
            &nbsp;
        </div>
        <br /><br />
        <div class="ui-dialog ui-widget ui-widget-content ui-corner-all" style="width: 80%; margin: auto;" >
            <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
                <h3><?=$this->translate( $this->controller );?></h3>
            </div>
            <div class="ui-dialog-content ui-widget-content" style="padding: 10px;">
                <div id="content-main">
                    <div class="nav">
                        <div class="bread">
                            <img src="<?=$this->url?>/img/icons/treeview.gif" />
                            <div class="treeview"></div>
                            <span></span>
                        </div>
                        <div class="buttons">
                            <a href="#this"><?=$this->translate('previous')?></a> |
                            <a href="#this"><?=$this->translate('next')?></a>
                        </div>
                        <div class="clear zero"></div>
                    </div>
                    <div id="content-main-content" class="content">

                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $('#content-main').navigation( '<?=$this->contents?>' , {baseUrl:'<?=$this->url?>',url:'/public/public/view/id/'} );
        </script>
    </body>
</html>
