<div id="login">

	<!-- TOPO -->
	<div id="hd" >
		<div class="lft">&nbsp;</div>
		<div class="rgt">&nbsp;</div>
		<div class="ctr"></div>
	</div>
	
	<div id="msg">
		<div id="alerta"></div>
	</div>

	<!-- MEIO -->
	
	<div class="box">
		<div class="header">
			<div class="rgt"></div>
			<div class="lft"></div>
			<div class="ctr"></div>
		</div>
		
		<div class="main">
			<form id="formSelect" action="<?=$this->url?>/user/select" method="post">
				<?=$this->translate("select a role")?>: 
				<?=$this->formSelect( "role_id" , null , array( "onchange" => "document.getElementById( 'formSelect' ).submit();" ) , $this->roles )?>&nbsp;
			</form>
		</div>

		<div class="footer">
			<div class="rgt"></div>
			<div class="lft"></div>
			<div class="ctr"></div>
			<div class="clear"></div>
		</div>
	</div>

</div>