<?php $this->suffix = $this->controller ?>
<b><?=$this->translate("name")?>:</b> <?=$this->person->name ?><br />
<b><?=$this->translate("login")?>:</b> <?=$this->person->email ?>
<br /><br />
<form action="<?=$this->url?>/user/save/" id="formUser_<?=$this->suffix?>" method="post">
	
	<label for="password_<?=$this->suffix?>"><span class="notEmpty">*</span> <?=$this->translate("password")?>:</label>
	<?=$this->formPassword( "password" , null , array( "id" => "password_" . $this->suffix ) )?>
	
	<label for="cpassword_<?=$this->suffix?>"><span class="notEmpty">*</span> <?=$this->translate("reply password")?>:</label>
	<?=$this->formPassword( "cpassword" , null , array( "id" => "cpassword_" . $this->suffix ) )?>
	<br /><br />
	
	<input type="submit" value="<?=$this->translate("save")?>" />
</form>
	
<script>
	var validateUser = new Preceptor.util.Validate();
	
	validateUser.addValidate( "password_<?=$this->suffix ?>"  , validateUser.notEmpty , <?=Zend_Json::encode( array ( 'notEmpty' => $this->translate("required field") ) ) ?> , null , 'notEmpty' );
	validateUser.addValidate( "cpassword_<?=$this->suffix ?>" , validateUser.notEmpty , <?=Zend_Json::encode( array ( 'notEmpty' => $this->translate("required field") ) ) ?> , null , 'notEmpty' );
	
	validateUser.addValidate( "username_<?=$this->suffix ?>"  , validateUser.stringLength , <?=Zend_Json::encode( array ( 'stringLength' => $this->translate("maxlength") ) ) ?> , <?=Zend_Json::encode( array ( 'stringLength' , 0 , 255 ) ) ?> , 'stringLength' );
	validateUser.addValidate( "password_<?=$this->suffix ?>"  , validateUser.stringLength , <?=Zend_Json::encode( array ( 'stringLength' => $this->translate("maxlength") ) ) ?> , <?=Zend_Json::encode( array ( 'stringLength' , 4 , 32 ) )  ?> , 'stringLength' );
	validateUser.addValidate( "cpassword_<?=$this->suffix ?>" , validateUser.stringLength , <?=Zend_Json::encode( array ( 'stringLength' => $this->translate("maxlength") ) ) ?> , <?=Zend_Json::encode( array ( 'stringLength' , 4 , 32 ) )  ?> , 'stringLength' );
	
	validateUser.addValidate( "password_<?=$this->suffix ?>"  , validateUser.stringEquals , <?=Zend_Json::encode( array ( 'stringEquals' => $this->translate("match not password") ) ) ?> , <?=Zend_Json::encode( array( "stringEquals" , "cpassword_" . $this->suffix ) ) ?> , 'stringEquals' );
	
	YAHOO.util.Event.on( 'formUser_<?=$this->suffix?>' , 'submit' , function( ev ){
		if( ! validateUser.verify( $( 'formUser_<?=$this->suffix?>' ) ) )
		{
			YAHOO.util.Event.stopEvent( ev );
		}
		
	});
</script>