<?php echo $this->translate("discipline")?>:
<?php echo $this->formSelect( "discipline" , $this->discipline , null , $this->disciplines ) ?>
<script type="text/javascript">
    jQuery('#findPerson-discipline > select').change( function(){
        if(jQuery(this).val()){
            new Preceptor.util.AjaxUpdate( 'findPerson-group' , '<?=$this->url?>/form/formfielddata/selected-find/discipline_id/' + jQuery(this).val() );
        }else{
           jQuery('#findPerson-group').html('')
        }

    });
</script>