<?php foreach ( $this->form->findManyToManyRowset( 'FormGroup' , 'FormGroupField' , null , null , $this->form->getTable()->select()->group('form_group_id') ) as $formGroup ) : ?>
	<fieldset>
		<legend><?=$formGroup->name ?></legend>
		<ul>
		<?php foreach ( $formGroup->findManyToManyRowset( 'FormField' , 'FormGroupField' , null , null , $formGroup->getTable()->select()->where( 'form_id =?' , $this->form->id )->order('form_field_id') ) as $formField ) : ?>
			<?php foreach ( $formField->findDependentRowset( 'FormFieldData' ) as $formData ) : ?>
				<?php if ( $formData->findParentRow( 'FormDataCreated' )->id == $this->createdId ) : ?>
					<li><b><?=$formField->label ?></b>&nbsp;<?=$formData->value?></li>
				<?php endif; ?>
			<?php endforeach; ?>
		<?php endforeach; ?>
		</ul>
		<br /><br />
	</fieldset>
	<br />
<?php endforeach; ?>
Código de Inscrição: 000<?=$this->createdId ?>