<div style="text-align: right">
    <?=$this->ajax( $this->translate('new') , 'user' , '/form/formfielddata/input/' , 2 )?>
</div>

<div class="filter">
	<div class="legend pos-relative"><?=$this->translate("filter")?></div>
	<form id="findPerson">
		
		<label id="findPerson-course">
            <?=$this->translate("course")?>:
            <?=$this->formSelect( "course" , $this->course , null , $this->courses ) ?>
		</label>

		<label id="findPerson-discipline">
        </label>

        <label id="findPerson-group">
        </label>
		<br /><br />
		
		<label>
            <?=$this->translate("search")?>:
            <?=$this->formText( "search" , null , array( 'style' => 'width: 200px;' ) ) ?>
        </label>
        
        <label><?=$this->translate("country")?>:</label>
		<?=$this->formSelect( "country" , null , null , $this->country ) ?>

        <label><?=$this->translate("state")?>:</label>
		<?=$this->formSelect( "state" , null , null , $this->state ) ?>

        <br /><br />
        
        <label><?=$this->translate("workplace")?>:</label>
		<?=$this->formSelect( "workplace" , null , null , $this->workplace ) ?>
        
        <label><?=$this->translate("status")?>:</label>
		<?=$this->formSelect( "status" , null , null , $this->status ) ?>
        
		<input type="submit" name="Submit" class="select" value=" OK " />
	</form>
	<br />
	<hr>
	<?php $letters = array( 'a' , 'b' , 'c' , 'd' , 'e' , 'd' , 'f' , 'g' , 'h' , 'i' , 'j' , 'k' , 'l' , 'm' , 'n' , 'o' , 'p' , 'q' , 'r' , 's' , 't' , 'u' , 'v' , 'w' , 'x' , 'y' , 'z' ); ?>
	
	<?php foreach( $letters as $letter ): ?>
		<?=$this->ajax( strtoupper( $letter ) , 'list_person' , '/form/formfielddata/find/letter/' . $letter ); ?> 
	<?php endforeach; ?>
</div>
<script type="text/javascript">
    jQuery('#country').change( function(){
        jQuery('#state').val('');
        jQuery('#workplace').val('');
    });

    jQuery('#state').change( function(){
        jQuery('#country').val('');
        jQuery('#workplace').val('');
    });

    jQuery('#workplace').change( function(){
        jQuery('#country').val('');
        jQuery('#state').val('');
    });

    jQuery('#findPerson-course > select').change( function(){
        if(jQuery(this).val()){
            new Preceptor.util.AjaxUpdate( 'findPerson-discipline' , '<?=$this->url?>/form/formfielddata/selected-find/course_id/' + jQuery(this).val() );
        }else{
           jQuery('#findPerson-discipline, #findPerson-group').html('')
        }
    });

	YAHOO.util.Event.on( "findPerson" , "submit" , function( ev ){
		new Preceptor.util.AjaxUpdate( 'list_person' , '<?=$this->url?>/form/formfielddata/find/' , { formId:"findPerson" } );
		YAHOO.util.Event.stopEvent( ev );
	});
</script>