<b>Nome:</b>&nbsp;<?=$this->person->name ?><br />
<b>E-mail:</b>&nbsp;<?=$this->person->email ?>
<br /><br />
<?php foreach ( $this->form as $formGroup ) : ?>
	<?php if ( $formGroup->form_group_id != -1 ) : ?>
		<fieldset>
		<legend><?=$formGroup->name ?></legend>
		<br />
		<?php $legend = "<br /><br /> </fieldset>" ?> 
	<?php endif; ?>
	
	<?php foreach( $formGroup->findManyToManyRowset( 'FormField' , 'FormGroupField' , null , null , $formGroup->getTable()->select()->order('form_field_id') ) as $formField ) : ?>
		<?php foreach ( $formField->findDependentRowset( 'FormFieldData' , null , $formGroup->getTable()->select()->where( 'person_id =?' , $this->person->id ) ) as $fieldData ) : ?>
			<b><?=$formField->label ?>:</b>&nbsp;<?=nl2br( $fieldData->value ) ?><br /><br />
		<?php endforeach; ?>
	<?php endforeach; ?>
	
	<?=$legend ?>
	<br />
<?php endforeach; ?>