<div>
<?php
	echo $this->element()->startForm()
						 ->formHidden( "id" , null , array( "printLabel" => false ) )
						 ->formHidden( "folder_id" , $this->folder_id , array( "printLabel" => false ) );

	if( !isset($this->data->id) ){
		echo "<label>{$this->translate( 'file' )}:</label>";
		echo $this->formFile( "file" );
	}else{
		echo $this->element()->formText( "title" ) ;
	}

	echo $this->element()->formText( "author"  )
              		 	 ->formTextarea( "ds" )
                       	 ->formSubmit( "save" , $this->translate("save") , array( "printLabel" => false ) )
                         ->endForm();

?>
</div>
<script>
	file_model_file.success = function(){
        new Preceptor.util.AjaxUpdate( 'file-file' , '<?=$this->url?>/file/file/save-file/' , { isUpload:true , formId:"File_Model_File" } );
    }
</script>