<div>
	<?php
		echo $this->element()->startForm( array( "id" => "File_Model_Folder" ) )
							 ->formHidden( "id" , $this->data->id , array( "printLabel" => false , "model" => "File_Model_Folder" ) )
							 ->formHidden( "number_call_bread_crumbs" , $this->numberCallBreadCrumbs , array( "printLabel" => false , "model" => "File_Model_Folder" ) )
							 ->formHidden( "folder_id" , $this->data->folder_id , array( "printLabel" => false , "model" => "File_Model_Folder" ) )
							 ->formHidden( "module" , File_Model_Folder::FLAG_FILE , array( "printLabel" => false , "model" => "File_Model_Folder" ) )
	  						 ->formText( "title" , $this->data->title , array( "model" => "File_Model_Folder" ) );
	?>


	<input type="checkbox" name="data[File_Model_Folder][visibility]" value="<?=$this->visible?>" id="visibility_<?=$this->suffix?>" <?=(isset($this->data->visibility) && $this->data->visibility == 'P' )?("checked='checked'"):"";?> />
	<label for="visibility_<?=$this->suffix?>" class="inline"><?=$this->translate( "visible to all?")?></label>

	<?php
	  	echo $this->element()->formSubmit( "save" , $this->translate("save") , array( "printLabel" => false ) )
	                       	 ->endForm();
	?>
</div>
<script>
	file_model_folder.success = function(){
        new Preceptor.util.AjaxUpdate( 'file-file' , '<?=$this->url?>/file/file/save/' , { formId:"File_Model_Folder" } );
    }
</script>