<div id="edit">
	<form action="#" id="formGroup_<?=$this->suffix?>" >
		
		<?=$this->formHidden( "id" , $this->data->id , array( "id" => "id_" . $this->suffix ) )?>
		
		<label for="name_<?=$this->suffix?>"><?=$this->translate("form legend")?>:</label>
		<?=$this->formText( "name" , $this->data->name , array( "id" => "name_" . $this->suffix ) )?>
		
		<br /><br />
		<input type="submit" value="Salvar" />
	</form>
</div>
<script>
	Preceptor.util.Validate.prototype.onsubmit = function(){ 
		YAHOO.util.Event.on( 'formGroup_<?=$this->suffix?>' , 'submit' , function( ev ){
			
			if( this.verify( $( 'formGroup_<?=$this->suffix?>' ) ) )
			{
				new Preceptor.util.AjaxUpdate( this.div , this.url , { formId: this.formId } );
			}
			
			YAHOO.util.Event.stopEvent( ev );
			
		} , this , true );
	}
</script>

<?=$this->validate( "formGroup_{$this->suffix}" , $this->jsonValidate , $this->suffix , "/form/formgroup/save/" , "category"  ); ?>
