<?php if( $this->getPermission( "input" ) ): ?>
    <div class="right"><?=$this->ajax( $this->translate( "new" ) , "bibliography-bibliography" , $this->url . "/bibliography/bibliography/input/" , 2 );?></div>
<?php endif ?>
<div class="clear"></div>
<br />
<div class="clear"></div>
<?php if( $this->rs->count() ):?>
	<table class="tablesorter">
        <thead>
            <tr>
                <th><?=$this->translate("basic");?></th>
                    <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                        <th></th>
                    <?php endif;?>
            </tr>
        </thead>

        <tbody>
			<?php foreach( $this->rs as $key => $result ):?>
				<?php $content = nl2br( $result->title ); ?>
				<?php $class   = $this->changeClass( $this->rs->key() , array( "even" , "odd" ) );?>

				<?php if( $this->getPermission( "input" ) ): ?>
					<?php $edit	   = $this->ajax( $this->translate("edit") , "bibliography-bibliography" , $this->url . "/bibliography/bibliography/input/id/" . $result->id . "/type/" . $result->type  ); ?>
				<?php endif; ?>

				<?php if( $this->getPermission( "delete" ) ): ?>
					<?php $delete  = $this->ajax( $this->translate("delete") , "bibliography-bibliography" , $this->url . "/bibliography/bibliography/delete/id/" . $result->id , 1 , $this->translate("want to delete?") ); ?>
				<?php endif; ?>

			<tr class="<?=$class?>">
				<td><?=$content;?></td>
				<?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
					<td nowrap="nowrap" width="77"><?=$edit . " " . $delete?></td>
				<?php endif;?>
			</tr>
			<?php endforeach;?>
        </tbody>
    </table>
<?php else: ?>
    <div class="clear"></div>
    <div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif;?>

<br />

<?php if( $this->rsComplement->count() ):?>
    <table class="tablesorter">
        <thead>
            <tr>
                <th><?=$this->translate("complement");?></th>
                    <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                        <th></th>
                    <?php endif;?>
            </tr>
        </thead>

        <tbody>
            <?php foreach( $this->rsComplement as $key => $resultComplement ): ?>
                <?php $content = nl2br( $resultComplement->title ); ?>
                <?php $class   = $this->changeClass( $this->rsComplement->key() , array( "even" , "odd" ) );?>

                <?php if( $this->getPermission( "input" ) ): ?>
                    <?php $edit = $this->ajax( $this->translate("edit")   , "bibliography-bibliography" , $this->url . "/bibliography/bibliography/input/id/"  . $resultComplement->id . "/type/" . $resultComplement->type   ); ?>
                <?php endif;?>

                <?php if( $this->getPermission( "delete" ) ): ?>
                    <?php $delete = $this->ajax( $this->translate("delete") , "bibliography-bibliography" , $this->url . "/bibliography/bibliography/delete/id/" . $resultComplement->id , 1 , $this->translate("want to delete?") ); ?>
                <?php endif;?>

                <tr class="<?=$class?>">
                    <td nowrap="nowrap"><?=$content;?></td>
                        <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                            <td nowrap="nowrap" width="77"><?=$edit . " " . $delete?></td>
                        <?php endif;?>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
<?php else: ?>
    <div class="clear"></div>
    <div class="message-table-sorter"><?=$this->translate( "there are no records" ) ?></div>
<?php endif;?>
