<div class="right">
	<?php if( $this->getPermission( "input" ) ): ?>
		<?=$this->ajax( $this->translate("new") , "form" , "/form/form/input" , 2 ) ?>
	<?php endif; ?>
</div>
<div><h2>Formulário de inscrição</h2></div>
<br /><br />
<?php if( $this->rs->count() ):?>
	<table class="datatable">
		<tr>
			<th width="70%"><?=$this->translate("name")?></th>
			<th width="10%">Link</th>
            <th width="10%">Campos</th>
			<?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
				<th width="10%"></th>
			<?php endif;?>
		</tr>
		<?php foreach( $this->rs as $rs ): ?>
			<?php $class  = $this->changeClass( $this->rs->key() , array( "light_gray" , "white" ) );?>
			
			<?php if( $this->getPermission( "input" ) ): ?>
				<?php $edit = $this->ajax( $this->translate("edit") , 'form' , '/form/form/input/id/' . $rs->id );?>	
			<?php endif;?>
				
			<?php if( $this->getPermission( "delete" ) ): ?>
				<?php //$delete = $this->ajax( $this->translate("delete") , 'form' , "/form/form/delete/id/{$rs->id}" , 1 , $this->translate("want to delete?") );?>
			<?php endif;?>
			
			<tr class="<?=$class?>">
				<td nowrap="nowrap"><?=$rs->name ?></td>
                <td><a href="<?=$this->url?>/form/formfielddata/indexguest" target="_blank"><?=$this->translate('access')?></a></td>
                <td><?=$this->ajax( $this->translate("manage") , 'form' , "/form/formfield/input/id/{$rs->id}" );?></td>
                <?php if( $this->getPermission( "input" ) || $this->getPermission( "delete" ) ): ?>
                    <td nowrap="nowrap"><?=$edit . " " . $delete?></td>
                <?php endif;?>
			</tr>
		<?php endforeach;?>
	</table>  
<?php else:?>
	<?=$this->translate( "there are no records" );?>
<?php endif;?>