<form action="#" id="formForm_<?=$this->suffix?>" >
	
	<?=$this->formHidden( 'id' , $this->data->id )?>
	<?=$this->formHidden( "course_period" )?>
	
	<label for="name_<?=$this->suffix?>"><?=$this->translate("title")?>:</label>
	<?=$this->formText( "name" , $this->data->name , array( "id" => "name_" . $this->suffix ) )?>
	
	<br /><br />
	
	<?php if ( $this->data->status == "PB" ) : ?>
		<?php $checked = "checked='checked'"; ?>
	<?php endif; ?>
	<input type="checkbox" name="status" value="PB" <?=$checked ?> >
	<?=$this->translate("the public form")?>
	
	<br /><br />
	
	<fieldset>
		<legend>&nbsp;<?=$this->translate("period")?>&nbsp;</legend>
		
		<div class="right">
			<input type="button" id="manager_period" value="<?=$this->translate("period manage")?>" />
		</div>
			
		<label for="course_period_<?=$this->suffix?>"><?=$this->translate("select course and period for form registered")?>:</label>
		
		<br />
		
		<a name="focus"></a>
		<div id="treeviewRelationForm"></div>
		
		<br />
	</fieldset>
	
	<fieldset>
		<legend>&nbsp;<?=$this->translate("email information")?>&nbsp;</legend>
		
		<!-- 
		<label for="email_<?//=$this->suffix?>"><?//=$this->translate("receive email are informaition")?>:</label>
		<?//=$this->formText( "email" , $this->data->email , array( "id" => "email_" . $this->suffix ) )?>
		 -->
		 
		<label for="subject_<?=$this->suffix?>"><?=$this->translate("subject")?>:</label>
		<?=$this->formText( "subject" , $this->data->subject , array( "id" => "subject_" . $this->suffix ) )?>
		
		<label for="ds_email_<?=$this->suffix?>"><?=$this->translate("text of the email to be sent to users")?>:</label>
		<?=$this->formTextarea( "ds_email" ,  $this->data->ds_email , array( "id" => "ds_email_" . $this->suffix ) )?>
		
		<br /><br />
	</fieldset>
		
	<input type="submit" value="<?=$this->translate("save")?>" />
</form>
	
<script>
	
	YAHOO.util.Event.on( "manager_period" , "click" , function(ev){
		var div = Lightbox.create();
		div.style.border = 'solid 1px black';
			
		new Preceptor.util.AjaxUpdate( 'category' , "<?=$this->url?>/period/period/index/formId/<?=$this->data->id?>" );
		window.location = '#category';
	});
	
	treeRelationForm = new YAHOO.widget.TreeView( "treeviewRelationForm" );
	var controllerTree;
	<?php foreach( $this->relation as $courses  ): ?>
		courseTree = new Preceptor.util.TaskNode( "<?=$courses['course']['title']?>" , treeRelationForm.getRoot(), false , false , <?=$courses['course']['id'] ?> );
		<?php foreach( $courses['period'] as $period  ): ?>
			<?php $checked = "false"; ?>
			<?php foreach ($period->getTable()->fetchFormCoursePeriod($this->form_id, $courses['course']['id']) as $checked )
			{
				if ($checked->period_id = $period->id)
					$checked = "true"; 
			}
			?>
			var tempNode = new Preceptor.util.TaskNode( '<?=$period->entered . " " . $this->translate('a') . " " . $period->expired?>' , courseTree , false , <?=$checked?> , <?=$period->id ?> );
		<?php endforeach; ?>
	<?php endforeach; ?>
       
	treeRelationForm.draw();
	
	var Editor_<?=$this->suffix?> = new Preceptor.widget.Editor( "ds_email_<?=$this->suffix ?>" );
	
	Preceptor.util.Validate.prototype.onsubmit = function(){ 
		YAHOO.util.Event.on( 'formForm_<?=$this->suffix?>' , 'submit' , function( ev ){
			Editor_<?=$this->suffix?>.saveHTML();
			
			if( this.verify( $( 'formForm_<?=$this->suffix?>' ) ) )
			{
				runRelationForm( this.div , this.url , this.formId );
			}
			
			YAHOO.util.Event.stopEvent( ev );
			
		} , this , true );
	}
</script>
<?=$this->validate( "formForm_{$this->suffix}" , $this->jsonValidate , $this->suffix , "/form/form/save/" , "form"  ); ?>
