
<script>
	treeRelationForm = new YAHOO.widget.TreeView( "treeviewRelationForm" );
	var controllerTree;
	<?php foreach( $this->relation as $courses  ): ?>
		courseTree = new Preceptor.util.TaskNode( "<?=$courses['course']['title']?>" , treeRelationForm.getRoot(), false , false , <?=$courses['course']['id'] ?> );
		<?php foreach( $courses['period'] as $period  ): ?>
			<?php $checked = "false"; ?>
			<?php foreach ( $period->findManyToManyRowset( "Form" , "FormCoursePeriod" , null , null , $period->getTable()->select()->where( 'form_id =?' , $this->form_id )->where( 'course_id =?' , $courses['course']['id'] ) ) as $checked )
			{
				if ( $checked->period_id = $period->id )
					$checked = "true"; 
			}
			?>
			var tempNode = new Preceptor.util.TaskNode( '<?=$this->date( $period->entered ) . " " . $this->translate('a') . " " . $this->date( $period->expired ) ?>' , courseTree , false , <?=$checked?> , <?=$period->id ?> );
		<?php endforeach; ?>
	<?php endforeach; ?>
       
	treeRelationForm.draw();
</script>