<table class="tablesorter">
    <thead>
        <tr>
            <th><?=$this->translate("name");?></th>
            <th><?=$this->translate("percentage");?></th>
        </tr>
    </thead>

    <tbody>
    <?php foreach( $this->rs as $key => $rs ): ?>
        <?php
            $total = ceil( ( 100 * $this->ContentAccess->countByPerson( $this->discipline_id , $rs->id ) ) / $this->Content->count( array( "discipline_id = ?" => $this->discipline_id , "NOT ds IS NULL" => "" ) ) );
            if( $total > 100 ) $total = 100;
        ?>
        <tr class="<?=$this->changeClass( $key , array( "even" , "odd" ) )?>">
            <td><?=$rs->name?></td>
            <td>
                <?php if( $total ): ?>
                    <div style='width:100px; border: 1px solid black; overflow:hidden'><p style='padding:0; margin: 0; text-align: center; width: <?=$total?>px; background: #407DA9; color: white;'><?=$total?>%</p></div>
                <?php else:?>
                    <?php $total = 0;?>
                    <div style='width:100px; border: 1px solid black; overflow:hidden'><p style='padding:0; margin: 0; text-align: center; width: <?=$total?>px; background: #407DA9; color: black;'><?=$total?>%</p></div>
                <?php endif ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>