<form id="formAccesslog" action="#">
	<div>
		<div class="left_access">
			<label><?=$this->translate('group') ?></label>
			<?=$this->formSelect( "group_id" , null , array( 'style' => 'width:165px' , 'id' => 'group_access' ) , $this->groups ) ?>
		</div>
		<div class="left_access">
			<label><?=$this->translate('users') ?></label>
            <span id="span_person_id"><?=$this->formSelect( "person_id" , null , array( 'style' => 'width:165px' , 'id' => 'user_access' ) , $this->users ) ?></span>
		</div>
		
		<div class="left_access">	
			<label><?=$this->translate('module') ?></label>
			<?=$this->formSelect( "controller" , null , array( 'style' => 'width:165px' , 'id' => 'controller_access' ) , $this->modules ) ?>
		</div>
		<div class="left_access">
			<label><?=$this->translate('action') ?></label>
			<span id="span_action"><?=$this->formSelect( "action" , null , array( 'style' => 'width:165px' , 'id' => 'action_access' ) , $this->actions ) ?></span>
		</div>
		
		<div class="left_access">
			<label><?=$this->translate('begin date')?></label>
			<?=$this->formText( "started" , null , array( 'style' => 'width:162px' , 'id' => 'dt_init_access' ) ) ?>
		</div>
		
		<div class="left_access">
			<label><?=$this->translate('end date')?></label>
			<?=$this->formText( "finish" , null , array( 'style' => 'width:162px' , 'id' => 'dt_end_access' ) ) ?>
		
			<input type="submit" id="access_submit" value="OK">
		</div>

        <div class="clear">&nbsp;</div>
	</div>
</form>
<div id="access_result"></div>
<script type="text/javascript">
	
	var AccessValidate =  new Validator('formAccesslog');

    AccessValidate.add( 'dt_init_access' , Validate.date	, '<?=$this->translate("date invalid")?>' );
    AccessValidate.add( 'dt_end_access'  , Validate.date	, '<?=$this->translate("date invalid")?>' );
    //AccessValidate.addValidate( 'dt_init_access' , AccessValidate.dateDependency , <?=Zend_Json::encode( array ( 'date' => $this->translate("date invalid") ) )?>  ,['dependent','dt_end_access'], 'date' );

	YAHOO.util.Event.on( 'group_access' , 'change' , function( ev ){
		new Preceptor.util.AjaxUpdate( 'span_person_id' , '<?=$this->url?>/report/access/select/type/person/q/' + this.value );
		YAHOO.util.Event.stopEvent( ev );
	});
	
	YAHOO.util.Event.on( 'controller_access' , 'change' , function( ev ){
		new Preceptor.util.AjaxUpdate( 'span_action' , '<?=$this->url?>/report/access/select/type/action/q/' + this.value );
		YAHOO.util.Event.stopEvent( ev );
	});
	
	
	AccessValidate.success = function(){
		new Preceptor.util.AjaxUpdate( 'access_result' , '<?=$this->url?>/report/access/find' , { formId: 'formAccesslog' } );
		$('#dt_init_access').val() = "";
        $('#dt_end_access').val() = "";
	}
	
</script>