<div>
	<?php if( count( $this->rs ) ): ?>
	<form action="#" id="form_organizer_<?=$this->suffix?>">
		<ul class="organizer" id="organizer_<?=$this->suffix?>">
			<?php foreach( $this->rs as $rs ): ?>
				<li id="organizer_li_<?=$rs['id']?>"><?=$this->ajax( $rs['title'] , "organizer" , "/composer/organizer/index/id/" . $rs['id'] )?></li>
			<?php endforeach; ?>
		</ul>
		<br />
		<input type="hidden" name="json" id="organizer_hidden_<?=$this->suffix?>" value="<?=$this->translate("save")?>">
		
		<input type="submit" id="organizer_submit_<?=$this->suffix?>" value="<?=$this->translate("save")?>">
		
	</form>
	<?php else: ?>
		<p><?=$this->translate( "there are no records" );?></p>
	<?php endif; ?>
</div>
<?php if( count( $this->rs ) ): ?>
<script>
	YAHOO.util.Event.onDOMReady( function(){
		YAHOO.util.DDM.handleOnAvailable = true;
        YAHOO.util.DDM.mode = 1;
            
		var ul = $("organizer_<?=$this->suffix?>");
		var lis = ul.getElementsByTagName("li");
		
		new YAHOO.util.DDTarget( "organizer_<?=$this->suffix?>" );

		for( var i = 0; i < lis.length; i++ ){
        	new Preceptor.widget.Organizer( lis[i].id , "DDorganizer" );
        }
        
        YAHOO.util.Event.on( "form_organizer_<?=$this->suffix?>" , "submit" , function( ev ){
        	var data  = [];
        	var value = {};
        	
        	for( var i = 0; i < lis.length; i++ ){
        		value = { id: 0 , position: 0 };
        		value.id = lis[i].id.replace( "organizer_li_" , "" );
        		value.position = i + 1;
        		data.push( value );
        	}
        	
        	var json = YAHOO.lang.JSON.stringify( data );
        	$( "organizer_hidden_<?=$this->suffix?>" ).value = json;
        	new Preceptor.util.AjaxUpdate( "organizer" , "<?=$this->url?>/composer/organizer/save/id/<?=$this->content?>" , { formId:"form_organizer_<?=$this->suffix?>" } )
        	
        	YAHOO.util.Event.stopEvent( ev );
        });
	});
</script>
<?php endif; ?>