<label><?=$this->translate("group legend")?>:</label>
<?=$this->formSelect( 'group' , null , null , $this->group ) ?>
<td><input type="button" id="group_legend" value="<?=$this->translate("group manage")?>" > </td>

<script>
	YAHOO.util.Event.on( "group_legend" , "click" , function(ev){
		var div = Lightbox.create();
		div.style.border = 'solid 1px black';
			
		new Preceptor.util.AjaxUpdate( 'category' , "<?=$this->url?>/form/formgroup" );
		window.location = '#category';
	});
</script>