<div class="search">
    <div class='left'>
		<form action="selection-process/index/list-pre-registration" method="get" id='query'>
			<span class="ui-icon ui-icon-search magnifier"></span>	
	        <input type="text" name="query" value="<?php echo $this->params['query']?>" />
	        <input type="submit" value="<?php echo $this->translate('Search')?>" />
	    </form>
	</div>
	<p class='clear'></p>
</div>
<br />
<div>
    <?php if (count($this->data)): ?>
		<table class="datatable">
	        <tr>
				<th></th>
	            <th><?php echo $this->translate('Name')?></th>
	            <th><?php echo $this->translate('Date')?></th>
				<th><?php echo $this->translate('course') . ' / ' . $this->translate('classroom')?></th>
	            <th><?php echo $this->translate('justify')?></th>
				<th><?php echo $this->translate('Status')?></th>
	        </tr>
	        <?php foreach ($this->data as $data): ?>
	            <tr class='<?php echo $data->status ?>'>
					<td>
						<label for='user-<?php echo $data->uid ?>'><img alt="<?php echo $data->uname ?>" title="<?php echo $data->uname ?>" width="" src="upload/<?php echo $this->thumbnail($data->image, 'small') ?>" /></label>
					</td>
	                <td>
						<?php echo $data->uname?>
					</td>
	                <td><?php echo $this->date($data->date, true)?></td>
	                <td><?php echo $data->coname . ' / ' . $data->cname?></td>
					<td><?php echo $data->justify?></td>
					<td><?php echo $this->translate($data->status)?></td>
	            </tr>
	        <?php endforeach; ?>
	    </table>
        <?php echo $this->paginationControl($this->data, null, null, $this->params); ?>
    <?php else:?>
        <p><?php echo $this->translate('there are no records')?></p>
    <?php endif;?>
</div>
<script type="text/javascript">
	$('input[type=button]').click( function(){
		formAction = $('#pre-registration').attr('action');
		formAction += this.id;
		$('#pre-registration').attr('action', formAction).submit();
    });
	
    $('input[type=button], input[type=submit]').button();
</script>