<?php if($this->isAllowed('form')): ?>	
	<div class="right"><?=$this->ajax("new", 'file/index/form/', 2); ?></div>
<?php endif; ?>	
<div class="left">
    <form id="formFindFile" action="#">
        <input type="text" name="q" id="qFile" style="width: 16em" />
        <input type="submit" value="OK" /> &nbsp;&nbsp;&nbsp;
    </form>
</div>
<div class="clear">&nbsp;</div>

<?php if (count($this->data)):?>
    <table class="datatable">
        <?php foreach ($this->data as $data): ?>
            <tr>
                <td><a href="file/index/download/file/<?php echo $data->location?>/name/<?php echo $data->name?>"><?php echo $data->name?></a></td>
                <td><?php echo $this->date($data->created)?></td>
                <td nowrap="nowrap">
                    <?php if($this->isAllowed("delete")): ?>
                        <?php echo $this->ajax("delete", 'file/index/delete/location/'. $data->location . '/id/' . $data->id, 2 , "want to delete?");?>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <div id="file-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
<?php else:?>
    <p><?=$this->translate( "there are no records" );?></p>
<?php endif;?>
<script type="text/javascript">
    $('.file-show').click(function(){
        $(this.target).toggle();
        return false;
    });

    $('#file-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $("#formFindFile").submit(function(ev) {
		$(this).parents('.content').load('file/index/index/q/' + $('#qFile').val());
        return false;
	});
</script>